/**
 * Карьерные действия — балансировка
 *
 * Правила:
 *  - category: 'career', actionType: 'work'
 *  - relationshipDelta — на уровне объекта, НЕ внутри statChanges
 *  - housingComfortDelta — на уровне объекта, НЕ внутри statChanges
 *  - skillChanges / requirements — только когда указаны
 *  - Пустые statChanges / skillChanges НЕ включаем
 */

export const CAREER_ACTIONS = [
  {
    id: 'car_work_day',
    category: 'career',
    title: 'Выполнить рабочий день',
    hourCost: 8,
    price: 0,
    skillChanges: { professionalism: 1 },
    actionType: 'work',
    effect: 'Зарплата, Профессионализм +1',
    mood: '💼 Обычный рабочий день',
  },
  {
    id: 'car_overtime',
    category: 'career',
    title: 'Сверхурочная работа',
    hourCost: 3,
    price: 0,
    statChanges: { stress: 10 },
    actionType: 'work',
    effect: '+30% ЗП за день, Стресс +10',
  },
  {
    id: 'car_job_search',
    category: 'career',
    title: 'Поиск новой работы',
    hourCost: 4,
    price: 0,
    actionType: 'work',
    effect: 'Шанс новой должности',
    mood: '🔍 Поиск лучших возможностей',
  },
  {
    id: 'car_interview_prep',
    category: 'career',
    title: 'Подготовка к собеседованию',
    hourCost: 3,
    price: 0,
    skillChanges: { negotiations: 2, professionalism: 1 },
    actionType: 'work',
    effect: 'Переговоры +2, Профессионализм +1',
  },
  {
    id: 'car_freelance',
    category: 'career',
    title: 'Фриланс-заказ',
    hourCost: 6,
    price: 0,
    skillChanges: { basicCreativity: 2 },
    actionType: 'work',
    effect: 'Деньги + Навык +2',
    mood: '💻 Фриланс — свобода и ответственность',
  },
  {
    id: 'car_networking',
    category: 'career',
    title: 'Сетевой нетворкинг',
    hourCost: 3,
    price: 1500,
    relationshipDelta: 8,
    actionType: 'work',
    effect: 'Социальные связи +8, шанс повышения',
  },
  {
    id: 'car_qualification',
    category: 'career',
    title: 'Повышение квалификации на работе',
    hourCost: 4,
    price: 0,
    skillChanges: { professionalism: 3 },
    actionType: 'work',
    effect: 'Профессионализм +3',
  },
  {
    id: 'car_career_change',
    category: 'career',
    title: 'Смена карьеры (переобучение)',
    hourCost: 8,
    price: 0,
    actionType: 'work',
    effect: 'Открытие новых веток',
    mood: '🔄 Новая карьера — новые горизонты',
  },
  {
    id: 'car_ask_promotion',
    category: 'career',
    title: 'Запросить повышение',
    hourCost: 1,
    price: 0,
    skillChanges: { negotiations: 1 },
    actionType: 'work',
    effect: 'Шанс повышения +20%, Переговоры +1',
  },
  {
    id: 'car_remote',
    category: 'career',
    title: 'Перейти на удалённую работу',
    hourCost: 2,
    price: 0,
    statChanges: { stress: -8 },
    housingComfortDelta: 5,
    actionType: 'work',
    effect: 'Стресс -8, Комфорт дома +5',
  },
  {
    id: 'car_side_project',
    category: 'career',
    title: 'Начать side-project',
    hourCost: 6,
    price: 5000,
    skillChanges: { specialization: 2 },
    actionType: 'work',
    effect: 'Специализация +2, шанс доп. дохода',
  },
  {
    id: 'car_mentor',
    category: 'career',
    title: 'Менторство коллег',
    hourCost: 3,
    price: 0,
    skillChanges: { leadership: 2 },
    relationshipDelta: 6,
    actionType: 'work',
    effect: 'Лидерство +2, Отношения +6',
  },
  {
    id: 'car_conference',
    category: 'career',
    title: 'Выступить на конференции',
    hourCost: 4,
    price: 2000,
    skillChanges: { charisma: 2, professionalism: 1 },
    relationshipDelta: 8,
    actionType: 'work',
    effect: 'Харизма +2, Профессионализм +1, Социальные связи +8',
  },
  {
    id: 'car_write_article',
    category: 'career',
    title: 'Написать статью для профильного журнала',
    hourCost: 5,
    price: 0,
    skillChanges: { writing: 1, professionalism: 2 },
    actionType: 'work',
    effect: 'Писательское мастерство +1, Профессионализм +2',
  },
  {
    id: 'car_certification',
    category: 'career',
    title: 'Пройти аттестацию',
    hourCost: 3,
    price: 0,
    skillChanges: { professionalism: 2 },
    actionType: 'work',
    effect: 'Профессионализм +2, шанс повышения',
  },
  {
    id: 'car_open_business',
    category: 'career',
    title: 'Открыть свой бизнес',
    hourCost: 8,
    price: 200000,
    skillChanges: { leadership: 2 },
    actionType: 'work',
    effect: 'Пассивный доход?, Риск, Лидерство +2',
  },
];
