/**
 * Образовательные действия — балансировка
 *
 * Правила:
 *  - category: 'education', actionType: 'education'
 *  - skillChanges — на уровне объекта
 *  - Пустые statChanges / skillChanges НЕ включаем
 */

export const EDUCATION_ACTIONS = [
  {
    id: 'edu_read_textbook',
    category: 'education',
    title: 'Чтение учебной книги',
    hourCost: 2,
    price: 0,
    skillChanges: { basicCreativity: 1 },
    actionType: 'education',
    effect: 'Обучение +12, соответствующий навык +1',
  },
  {
    id: 'edu_online_course',
    category: 'education',
    title: 'Онлайн-курс (1 занятие)',
    hourCost: 3,
    price: 0,
    skillChanges: { basicCreativity: 2 },
    actionType: 'education',
    effect: 'Обучение +18, Навык +2',
  },
  {
    id: 'edu_practical_task',
    category: 'education',
    title: 'Практическое задание',
    hourCost: 4,
    price: 0,
    skillChanges: { professionalism: 1 },
    actionType: 'education',
    effect: 'Навык +3, Профессионализм +1',
  },
  {
    id: 'edu_edu_video',
    category: 'education',
    title: 'Просмотр образовательного видео',
    hourCost: 1.5,
    price: 0,
    skillChanges: { basicCreativity: 1 },
    actionType: 'education',
    effect: 'Обучение +8, Навык +1',
  },
  {
    id: 'edu_exam_prep',
    category: 'education',
    title: 'Подготовка к экзамену / тесту',
    hourCost: 5,
    price: 0,
    skillChanges: { discipline: 2 },
    actionType: 'education',
    effect: 'Навык +4, Дисциплина +2',
  },
  {
    id: 'edu_webinar',
    category: 'education',
    title: 'Посещение вебинара',
    hourCost: 2.5,
    price: 1200,
    skillChanges: { basicCreativity: 3 },
    actionType: 'education',
    effect: 'Навык +3, Социальные связи +2',
  },
  {
    id: 'edu_foreign_lang',
    category: 'education',
    title: 'Изучение иностранного языка (1 занятие)',
    hourCost: 2,
    price: 800,
    skillChanges: { communication: 2 },
    actionType: 'education',
    effect: 'Коммуникация +2, Навык +2',
  },
  {
    id: 'edu_write_article',
    category: 'education',
    title: 'Написание статьи / поста',
    hourCost: 3,
    price: 0,
    skillChanges: { basicCreativity: 2, marketing: 1 },
    actionType: 'education',
    effect: 'Креативность +2, Маркетинг +1',
  },
  {
    id: 'edu_public_speaking',
    category: 'education',
    title: 'Практика публичных выступлений',
    hourCost: 2,
    price: 0,
    skillChanges: { communication: 3, leadership: 1 },
    actionType: 'education',
    effect: 'Коммуникация +3, Лидерство +1',
  },
  {
    id: 'edu_financial_lit',
    category: 'education',
    title: 'Изучение финансовой литературы',
    hourCost: 2.5,
    price: 0,
    skillChanges: { financialLiteracy: 3 },
    actionType: 'education',
    effect: 'Финансовая грамотность +3',
  },
  {
    id: 'edu_programming',
    category: 'education',
    title: 'Курс программирования (занятие)',
    hourCost: 4,
    price: 0,
    skillChanges: { technicalLiteracy: 3 },
    actionType: 'education',
    effect: 'Техническая грамотность +3',
  },
  {
    id: 'edu_cooking_masterclass',
    category: 'education',
    title: 'Мастер-класс по кулинарии',
    hourCost: 3,
    price: 2500,
    statChanges: { mood: 8 },
    skillChanges: { cooking: 3 },
    actionType: 'education',
    effect: 'Кулинария +3, Настроение +8',
  },
  {
    id: 'edu_research',
    category: 'education',
    title: 'Самостоятельное исследование темы',
    hourCost: 4,
    price: 0,
    skillChanges: { analyticalThinking: 2 },
    actionType: 'education',
    effect: 'Аналитическое мышление +2, Навык +2',
  },
  {
    id: 'edu_memory_training',
    category: 'education',
    title: 'Тренировка памяти и внимания',
    hourCost: 1,
    price: 0,
    skillChanges: { memory: 2, discipline: 1 },
    actionType: 'education',
    effect: 'Память +2, Дисциплина +1',
  },
  {
    id: 'edu_psychology',
    category: 'education',
    title: 'Изучение психологии',
    hourCost: 2.5,
    price: 0,
    skillChanges: { emotionalIntelligence: 3 },
    actionType: 'education',
    effect: 'Эмоциональный интеллект +3',
  },
  {
    id: 'edu_mba',
    category: 'education',
    title: 'Онлайн-курс MBA (занятие)',
    hourCost: 5,
    price: 4500,
    skillChanges: { leadership: 3, strategicPlanning: 2 },
    actionType: 'education',
    effect: 'Лидерство +3, Стратегическое планирование +2',
  },
  {
    id: 'edu_negotiation_practice',
    category: 'education',
    title: 'Практика переговоров',
    hourCost: 2,
    price: 0,
    skillChanges: { negotiations: 3 },
    actionType: 'education',
    effect: 'Переговоры +3',
  },
  {
    id: 'edu_design',
    category: 'education',
    title: 'Изучение дизайна',
    hourCost: 3,
    price: 0,
    skillChanges: { basicCreativity: 3, interiorDesign: 2 },
    actionType: 'education',
    effect: 'Креативность +3, Дизайн интерьера +2',
  },
  {
    id: 'edu_fitness_theory',
    category: 'education',
    title: 'Физическая теория тренировок',
    hourCost: 2,
    price: 0,
    skillChanges: { physicalFitness: 2, healthyLifestyle: 2 },
    actionType: 'education',
    effect: 'Физическая форма +2, Здоровый образ жизни +2',
  },
  {
    id: 'edu_invest_course',
    category: 'education',
    title: 'Курс инвестирования',
    hourCost: 3,
    price: 1800,
    skillChanges: { financialLiteracy: 4 },
    actionType: 'education',
    effect: 'Финансовая грамотность +4',
  },
  {
    id: 'edu_marketing',
    category: 'education',
    title: 'Изучение маркетинга',
    hourCost: 4,
    price: 0,
    skillChanges: { marketing: 3 },
    actionType: 'education',
    effect: 'Маркетинг +3',
  },
  {
    id: 'edu_photo_practice',
    category: 'education',
    title: 'Практика фотографии',
    hourCost: 3,
    price: 300,
    skillChanges: { photography: 3, basicCreativity: 2 },
    actionType: 'education',
    effect: 'Фотография +3, Креативность +2',
  },
  {
    id: 'edu_diary',
    category: 'education',
    title: 'Написание дневника рефлексии',
    hourCost: 1,
    price: 0,
    skillChanges: { emotionalIntelligence: 2, wisdom: 1 },
    actionType: 'education',
    effect: 'Эмоциональный интеллект +2, Мудрость +1',
  },
  {
    id: 'edu_time_management',
    category: 'education',
    title: 'Изучение тайм-менеджмента',
    hourCost: 2,
    price: 0,
    skillChanges: { timeManagement: 3 },
    actionType: 'education',
    effect: 'Тайм-менеджмент +3',
  },
  {
    id: 'edu_leadership_course',
    category: 'education',
    title: 'Онлайн-курс по лидерству',
    hourCost: 3.5,
    price: 2200,
    skillChanges: { leadership: 4 },
    actionType: 'education',
    effect: 'Лидерство +4',
  },
  {
    id: 'edu_mindfulness',
    category: 'education',
    title: 'Практика медитации и осознанности',
    hourCost: 1.5,
    price: 0,
    skillChanges: { emotionalIntelligence: 3, stressResistance: 2 },
    actionType: 'education',
    effect: 'Эмоциональный интеллект +3, Стрессоустойчивость +2',
  },
  {
    id: 'edu_gardening',
    category: 'education',
    title: 'Изучение садоводства',
    hourCost: 2,
    price: 600,
    housingComfortDelta: 5,
    skillChanges: { gardening: 3 },
    actionType: 'education',
    effect: 'Садоводство +3, Комфорт дома +5',
  },
  {
    id: 'edu_acting',
    category: 'education',
    title: 'Курс актёрского мастерства',
    hourCost: 4,
    price: 3500,
    skillChanges: { acting: 3, charisma: 2 },
    actionType: 'education',
    effect: 'Актёрское мастерство +3, Харизма +2',
  },
  {
    id: 'edu_podcasts',
    category: 'education',
    title: 'Самообразование через подкасты',
    hourCost: 2,
    price: 0,
    skillChanges: { basicCreativity: 1 },
    actionType: 'education',
    effect: 'Обучение +10, соответствующий навык +1',
  },
  {
    id: 'edu_resume',
    category: 'education',
    title: 'Подготовка резюме и портфолио',
    hourCost: 3,
    price: 0,
    skillChanges: { professionalism: 2, negotiations: 2 },
    actionType: 'education',
    effect: 'Профессионализм +2, Переговоры +2',
  },
  {
    id: 'edu_library',
    category: 'education',
    title: 'Посещение библиотеки',
    hourCost: 3,
    price: 0,
    skillChanges: { curiosity: 1 },
    actionType: 'education',
    effect: 'Обучение +10, Любознательность +1',
  },
  {
    id: 'edu_hackathon',
    category: 'education',
    title: 'Участие в хакатоне / конкурсе',
    hourCost: 8,
    price: 0,
    skillChanges: { specialization: 2, professionalism: 2 },
    actionType: 'education',
    effect: 'Специализация +2, Профессионализм +2, шанс приза',
  },
  {
    id: 'edu_history',
    category: 'education',
    title: 'Изучение истории',
    hourCost: 2,
    price: 0,
    skillChanges: { wisdom: 1, curiosity: 1 },
    actionType: 'education',
    effect: 'Мудрость +1, Любознательность +1',
  },
  {
    id: 'edu_philosophy',
    category: 'education',
    title: 'Изучение философии',
    hourCost: 2.5,
    price: 0,
    skillChanges: { wisdom: 2, emotionalIntelligence: 1 },
    actionType: 'education',
    effect: 'Мудрость +2, Эмоциональный интеллект +1',
  },
  {
    id: 'edu_speed_reading',
    category: 'education',
    title: 'Практика скорочтения',
    hourCost: 1.5,
    price: 0,
    skillChanges: { memory: 2, curiosity: 1 },
    actionType: 'education',
    effect: 'Память +2, Любознательность +1',
  },
  {
    id: 'edu_law',
    category: 'education',
    title: 'Изучение основ права',
    hourCost: 3,
    price: 0,
    skillChanges: { legalLiteracy: 2 },
    actionType: 'education',
    effect: 'Юридическая грамотность +2',
  },
  {
    id: 'edu_online_test',
    category: 'education',
    title: 'Пройти онлайн-тестирование',
    hourCost: 1,
    price: 500,
    skillChanges: { basicCreativity: 1 },
    actionType: 'education',
    effect: 'Навык +1, Самопознание',
  },
  {
    id: 'edu_ecology',
    category: 'education',
    title: 'Изучение экологии и биологии',
    hourCost: 2,
    price: 0,
    skillChanges: { medicalKnowledge: 1, healthyLifestyle: 1 },
    actionType: 'education',
    effect: 'Медицинские знания +1, Здоровый образ жизни +1',
  },
];
