/**
 * Финансовые действия — балансировка
 *
 * Правила:
 *  - category: 'finance', actionType: 'recovery'
 *  - reserveDelta — на уровне объекта
 *  - investmentReturn — на уровне объекта
 *  - skillChanges / requirements — только когда указаны
 *  - Пустые statChanges / skillChanges НЕ включаем
 */

export const FINANCE_ACTIONS = [
  {
    id: 'fin_reserve',
    category: 'finance',
    title: 'Отложить деньги в резерв',
    hourCost: 1,
    price: 0,
    reserveDelta: 0,
    statChanges: { stress: -6 },
    actionType: 'recovery',
    effect: 'Резерв + сумма, Стресс -6',
    mood: '💰 Отложу на чёрный день',
  },
  {
    id: 'fin_deposit',
    category: 'finance',
    title: 'Открыть банковский депозит',
    hourCost: 2,
    price: 30000,
    skillChanges: { financialLiteracy: 2 },
    actionType: 'recovery',
    effect: 'Пассивный доход, Финансовая грамотность +2',
    mood: '🏦 Деньги работают на меня',
  },
  {
    id: 'fin_budget',
    category: 'finance',
    title: 'Пересмотреть личный бюджет',
    hourCost: 1.5,
    price: 0,
    statChanges: { stress: -8 },
    skillChanges: { financialLiteracy: 2 },
    actionType: 'recovery',
    effect: 'Финансовая грамотность +2, Стресс -8',
  },
  {
    id: 'fin_stocks',
    category: 'finance',
    title: 'Купить акции / паи фондов',
    hourCost: 2,
    price: 15000,
    skillChanges: { analyticalThinking: 1 },
    actionType: 'recovery',
    effect: 'Инвестиция с риском, Аналитическое мышление +1',
  },
  {
    id: 'fin_iis',
    category: 'finance',
    title: 'Открыть ИИС',
    hourCost: 2.5,
    price: 50000,
    skillChanges: { financialLiteracy: 3 },
    actionType: 'recovery',
    effect: 'Налоговые льготы, Финансовая грамотность +3',
  },
  {
    id: 'fin_pay_debt',
    category: 'finance',
    title: 'Погасить небольшой долг',
    hourCost: 1,
    price: 0,
    statChanges: { stress: -15, mood: 10 },
    actionType: 'recovery',
    effect: 'Стресс -15, Настроение +10',
  },
  {
    id: 'fin_take_credit',
    category: 'finance',
    title: 'Взять кредит на крупную покупку',
    hourCost: 3,
    price: 0,
    actionType: 'recovery',
    effect: 'Деньги сейчас, но долг + проценты',
    mood: '📋 Кредит — это ответственность',
  },
  {
    id: 'fin_safety_fund',
    category: 'finance',
    title: 'Создать финансовую подушку',
    hourCost: 1,
    price: 10000,
    statChanges: { stress: -10 },
    actionType: 'recovery',
    effect: 'Стресс -10, Безопасность +',
  },
  {
    id: 'fin_business_invest',
    category: 'finance',
    title: 'Инвестировать в собственный бизнес',
    hourCost: 4,
    price: 100000,
    actionType: 'recovery',
    effect: 'Возможность пассивного дохода, Риск',
    mood: '🏢 Свой бизнес — свобода',
  },
  {
    id: 'fin_advisor',
    category: 'finance',
    title: 'Консультация с финансовым советником',
    hourCost: 2,
    price: 5000,
    statChanges: { stress: -5 },
    skillChanges: { financialLiteracy: 4 },
    actionType: 'recovery',
    effect: 'Финансовая грамотность +4, Стресс -5',
  },
  {
    id: 'fin_crypto',
    category: 'finance',
    title: 'Покупка золота / криптовалюты',
    hourCost: 1.5,
    price: 0,
    skillChanges: { analyticalThinking: 1 },
    actionType: 'recovery',
    effect: 'Высокий риск/доход, Аналитическое мышление +1',
  },
  {
    id: 'fin_auto_savings',
    category: 'finance',
    title: 'Автоматические переводы на сбережения',
    hourCost: 0.5,
    price: 0,
    skillChanges: { discipline: 2, financialLiteracy: 1 },
    actionType: 'recovery',
    effect: 'Дисциплина +2, Финансовая грамотность +1',
  },
  {
    id: 'fin_expense_analysis',
    category: 'finance',
    title: 'Анализ своих расходов за месяц',
    hourCost: 2,
    price: 0,
    skillChanges: { financialLiteracy: 3, organization: 2 },
    actionType: 'recovery',
    effect: 'Финансовая грамотность +3, Организованность +2',
  },
  {
    id: 'fin_insurance',
    category: 'finance',
    title: 'Страхование жизни / здоровья',
    hourCost: 2,
    price: 12000,
    statChanges: { stress: -8 },
    actionType: 'recovery',
    effect: 'Здоровье + безопасность, Стресс -8',
    subscription: { monthlyCost: 1000 },
  },
  {
    id: 'fin_edu_invest',
    category: 'finance',
    title: 'Инвестиции в образование',
    hourCost: 1,
    price: 15000,
    actionType: 'recovery',
    effect: 'Навыки + ускорение, Долгосрочный рост',
    mood: '📚 Лучшее вложение — в себя',
  },
  {
    id: 'fin_sell_stuff',
    category: 'finance',
    title: 'Продать ненужные вещи',
    hourCost: 3,
    price: 0,
    skillChanges: { organization: 1 },
    actionType: 'recovery',
    effect: '+2000–8000 руб, Организованность +1',
  },
  {
    id: 'fin_rent_out',
    category: 'finance',
    title: 'Сдать недвижимость в аренду',
    hourCost: 3,
    price: 0,
    actionType: 'recovery',
    effect: 'Пассивный доход +5000/мес',
    mood: '🏠 Недвижимость работает',
  },
  {
    id: 'fin_savings_account',
    category: 'finance',
    title: 'Открыть накопительный счёт',
    hourCost: 1,
    price: 5000,
    statChanges: { stress: -4 },
    skillChanges: { financialLiteracy: 1 },
    actionType: 'recovery',
    effect: 'Финансовая грамотность +1, Стресс -4',
  },
  {
    id: 'fin_pay_mortgage',
    category: 'finance',
    title: 'Частично погасить ипотеку',
    hourCost: 2,
    price: 0,
    statChanges: { stress: -12, mood: 8 },
    actionType: 'recovery',
    effect: 'Стресс -12, Настроение +8',
  },
  {
    id: 'fin_buy_realty',
    category: 'finance',
    title: 'Купить недвижимость',
    hourCost: 6,
    price: 500000,
    statChanges: { stress: -5 },
    housingComfortDelta: 25,
    actionType: 'recovery',
    effect: 'Актив, Комфорт дома +25, Стресс -5',
  },
  {
    id: 'fin_pif',
    category: 'finance',
    title: 'Инвестировать в ПИФ',
    hourCost: 2,
    price: 30000,
    skillChanges: { financialAnalysis: 1 },
    actionType: 'recovery',
    effect: 'Пассивный доход, Финансовый анализ +1',
  },
];
