/**
 * Баланс: Действия отдыха и развлечений
 *
 * Категория: fun
 * ActionType: 'sleep' — для действий сна, 'recovery' — по умолчанию
 */

export const FUN_ACTIONS = [
  // ─── Сон ────────────────────────────────────────────────
  {
    id: 'fun_sleep_8h',
    category: 'fun',
    title: 'Сон (рекомендуемый 8 часов)',
    hourCost: 8,
    price: 0,
    statChanges: { energy: 48, mood: 14, stress: -18, health: 4 },
    actionType: 'sleep',
    effect: 'Энергия +48, Настроение +14, Стресс -18, Здоровье +4',
    mood: '😴 Полноценный сон — залог здоровья',
  },
  {
    id: 'fun_short_sleep',
    category: 'fun',
    title: 'Короткий сон',
    hourCost: 6,
    price: 0,
    statChanges: { energy: 32, mood: 6, stress: -9, health: -3 },
    actionType: 'sleep',
    effect: 'Энергия +32, Настроение +6, Стресс -9, Здоровье -3',
    mood: '😪 Недосып — ничего, продержимся',
  },

  // ─── Развлечения вне дома ───────────────────────────────
  {
    id: 'fun_cinema',
    category: 'fun',
    title: 'Кино в кинотеатре',
    hourCost: 3,
    price: 950,
    statChanges: { mood: 22, stress: -13 },
    actionType: 'recovery',
    effect: 'Настроение +22, Стресс -13',
    mood: '🎬 Большой экран — лучшее погружение',
  },
  {
    id: 'fun_park_walk',
    category: 'fun',
    title: 'Прогулка в парке',
    hourCost: 2,
    price: 0,
    statChanges: { energy: 12, mood: 16, stress: -12, health: 3 },
    actionType: 'recovery',
    effect: 'Энергия +12, Настроение +16, Стресс -12, Здоровье +3',
    mood: '🌳 Свежий воздух очищает мысли',
  },
  {
    id: 'fun_gym',
    category: 'fun',
    title: 'Тренировка в спортзале',
    hourCost: 2,
    price: 0,
    statChanges: { physical: 9, stress: -18, health: 5, energy: -7 },
    actionType: 'recovery',
    effect: 'Физическая форма +9, Стресс -18, Здоровье +5, Энергия -7',
    mood: '💪 Железо не терпит слабости',
    requirements: { requiresItem: 'fitness_membership' },
  },
  {
    id: 'fun_meditation',
    category: 'fun',
    title: 'Медитация',
    hourCost: 1,
    price: 0,
    statChanges: { stress: -20, mood: 12 },
    skillChanges: { emotionalIntelligence: 1 },
    actionType: 'recovery',
    effect: 'Стресс -20, Настроение +12, Эмоциональный интеллект +1',
    mood: '🧘 Тишина внутри — сила снаружи',
  },
  {
    id: 'fun_series',
    category: 'fun',
    title: 'Просмотр сериала дома',
    hourCost: 4,
    price: 0,
    statChanges: { mood: 17, stress: -10, energy: 10 },
    actionType: 'recovery',
    effect: 'Настроение +17, Стресс -10, Энергия +10',
    mood: '📺 Ещё одну серию… и спать',
  },
  {
    id: 'fun_bath',
    category: 'fun',
    title: 'Горячая ванна с солью',
    hourCost: 1.5,
    price: 200,
    statChanges: { stress: -22, mood: 14, health: 4 },
    actionType: 'recovery',
    effect: 'Стресс -22, Настроение +14, Здоровье +4',
    mood: '🛁 Тёплая вода смывает усталость',
  },
  {
    id: 'fun_massage',
    category: 'fun',
    title: 'Профессиональный массаж',
    hourCost: 2,
    price: 3500,
    statChanges: { stress: -28, energy: 18, mood: 15 },
    actionType: 'recovery',
    effect: 'Стресс -28, Энергия +18, Настроение +15',
    mood: '💆 Массаж — лучшая инвестиция в тело',
  },
  {
    id: 'fun_yoga',
    category: 'fun',
    title: 'Йога дома',
    hourCost: 1.5,
    price: 0,
    statChanges: { physical: 6, stress: -16, mood: 10 },
    actionType: 'recovery',
    effect: 'Физическая форма +6, Стресс -16, Настроение +10',
    mood: '🧘‍♀️ Гармония тела и разума',
  },
  {
    id: 'fun_concert',
    category: 'fun',
    title: 'Посещение концерта',
    hourCost: 4,
    price: 2800,
    statChanges: { mood: 25, stress: -12 },
    actionType: 'recovery',
    effect: 'Настроение +25, Стресс -12',
    mood: '🎵 Музыка лечит душу',
  },
  {
    id: 'fun_fishing',
    category: 'fun',
    title: 'Рыбалка',
    hourCost: 5,
    price: 450,
    statChanges: { mood: 18, stress: -16, hunger: 12 },
    actionType: 'recovery',
    effect: 'Настроение +18, Стресс -16, Голод +12',
    mood: '🎣 Тишина, вода и удочка',
  },
  {
    id: 'fun_sauna',
    category: 'fun',
    title: 'Сауна / баня',
    hourCost: 3,
    price: 2000,
    statChanges: { health: 10, stress: -25, energy: 12 },
    actionType: 'recovery',
    effect: 'Здоровье +10, Стресс -25, Энергия +12',
    mood: '♨️ Пар очищает всё',
  },
  {
    id: 'fun_pc_games',
    category: 'fun',
    title: 'Компьютерные игры',
    hourCost: 3,
    price: 0,
    statChanges: { mood: 15, stress: -7 },
    skillChanges: { basicCreativity: 1 },
    actionType: 'recovery',
    effect: 'Настроение +15, Стресс -7, Базовая креативность +1',
    mood: '🎮 Один матч — и порядок',
  },
  {
    id: 'fun_reading_fiction',
    category: 'fun',
    title: 'Чтение художественной литературы',
    hourCost: 2.5,
    price: 0,
    statChanges: { mood: 10 },
    skillChanges: { basicCreativity: 2 },
    actionType: 'recovery',
    effect: 'Настроение +10, Базовая креативность +2',
    mood: '📖 Книга — портал в другой мир',
  },
  {
    id: 'fun_picnic',
    category: 'fun',
    title: 'Пикник на природе',
    hourCost: 4,
    price: 1400,
    statChanges: { mood: 20, stress: -14, health: 4 },
    actionType: 'recovery',
    effect: 'Настроение +20, Стресс -14, Здоровье +4',
    mood: '🧺 Природа, еда и хорошая компания',
  },
  {
    id: 'fun_club_dancing',
    category: 'fun',
    title: 'Танцы в клубе',
    hourCost: 4,
    price: 1800,
    statChanges: { mood: 23, stress: -11, energy: -10 },
    actionType: 'recovery',
    effect: 'Настроение +23, Стресс -11, Энергия -10',
    mood: '💃 Танцуй, пока молод',
  },
  {
    id: 'fun_spa_day',
    category: 'fun',
    title: 'День в спа-центре',
    hourCost: 6,
    price: 9500,
    statChanges: { stress: -40, mood: 28, health: 12 },
    actionType: 'recovery',
    effect: 'Стресс -40, Настроение +28, Здоровье +12',
    mood: '💆‍♀️ Роскошь, которую ты заслужил',
    cooldown: { hours: 168 },
  },
  {
    id: 'fun_motivational',
    category: 'fun',
    title: 'Просмотр мотивационного контента',
    hourCost: 1,
    price: 0,
    statChanges: { mood: 8 },
    skillChanges: { discipline: 1 },
    actionType: 'recovery',
    effect: 'Настроение +8, Дисциплина +1',
    mood: '🔥 Мотивация — топливо успеха',
  },
  {
    id: 'fun_light_cleaning',
    category: 'fun',
    title: 'Лёгкая уборка дома',
    hourCost: 2,
    price: 0,
    statChanges: { stress: -6 },
    skillChanges: { organization: 2 },
    housingComfortDelta: 12,
    actionType: 'recovery',
    effect: 'Стресс -6, Организация +2, Комфорт жилья +12',
    mood: '🧹 Чистый дом — чистый разум',
  },
  {
    id: 'fun_music_listen',
    category: 'fun',
    title: 'Прослушивание музыки',
    hourCost: 1.5,
    price: 0,
    statChanges: { mood: 12, stress: -9 },
    actionType: 'recovery',
    effect: 'Настроение +12, Стресс -9',
    mood: '🎧 Музыка — терапия для души',
  },
  {
    id: 'fun_photoshoot',
    category: 'fun',
    title: 'Фотосессия на природе',
    hourCost: 3,
    price: 300,
    statChanges: { mood: 16 },
    skillChanges: { basicCreativity: 2, photography: 2 },
    actionType: 'recovery',
    effect: 'Настроение +16, Базовая креативность +2, Фотография +2',
    mood: '📸 Останови мгновение',
  },
  {
    id: 'fun_bicycle',
    category: 'fun',
    title: 'Катание на велосипеде',
    hourCost: 2.5,
    price: 0,
    statChanges: { physical: 7, energy: 5, stress: -13 },
    actionType: 'recovery',
    effect: 'Физическая форма +7, Энергия +5, Стресс -13',
    mood: '🚴 Ветер в лицо — свобода',
  },
  {
    id: 'fun_board_games',
    category: 'fun',
    title: 'Настольные игры с друзьями',
    hourCost: 3,
    price: 600,
    statChanges: { mood: 18 },
    relationshipDelta: 8,
    actionType: 'recovery',
    effect: 'Настроение +18, Отношения +8',
    mood: '🎲 Веселье в хорошей компании',
  },
  {
    id: 'fun_digital_detox',
    category: 'fun',
    title: 'День в тишине (отключение гаджетов)',
    hourCost: 4,
    price: 0,
    statChanges: { stress: -20 },
    skillChanges: { emotionalIntelligence: 2 },
    actionType: 'recovery',
    effect: 'Стресс -20, Эмоциональный интеллект +2',
    mood: '📵 Тишина — это тоже звук',
  },
  {
    id: 'fun_museum',
    category: 'fun',
    title: 'Поход в музей',
    hourCost: 4,
    price: 1200,
    statChanges: { mood: 14 },
    skillChanges: { basicCreativity: 3 },
    actionType: 'recovery',
    effect: 'Настроение +14, Базовая креативность +3',
    mood: '🏛️ Искусство расширяет горизонты',
  },
  {
    id: 'fun_active_rest',
    category: 'fun',
    title: 'Активный отдых (скалолазание, роллер)',
    hourCost: 4,
    price: 1800,
    statChanges: { physical: 10, mood: 15, stress: -12 },
    actionType: 'recovery',
    effect: 'Физическая форма +10, Настроение +15, Стресс -12',
    mood: '🧗 Адреналин — лучшая приправа',
  },
  {
    id: 'fun_tea_relax',
    category: 'fun',
    title: 'Релакс с чаем и пледом',
    hourCost: 2,
    price: 150,
    statChanges: { mood: 13, stress: -15 },
    actionType: 'recovery',
    effect: 'Настроение +13, Стресс -15',
    mood: '☕ Чай, плед и уют',
  },
  {
    id: 'fun_theater',
    category: 'fun',
    title: 'Посещение театра',
    hourCost: 4,
    price: 3200,
    statChanges: { mood: 22 },
    skillChanges: { basicCreativity: 2 },
    actionType: 'recovery',
    effect: 'Настроение +22, Базовая креативность +2',
    mood: '🎭 Театр — зеркало жизни',
  },
  {
    id: 'fun_lazy_day',
    category: 'fun',
    title: 'Полный день отдыха (ничего не делать)',
    hourCost: 12,
    price: 0,
    statChanges: { energy: 35, stress: -25, physical: -3 },
    actionType: 'recovery',
    effect: 'Энергия +35, Стресс -25, Физическая форма -3',
    mood: '🛋️ Иногда лучший план — никакого плана',
  },
  {
    id: 'fun_morning_run',
    category: 'fun',
    title: 'Утренняя пробежка',
    hourCost: 1,
    price: 0,
    statChanges: { physical: 4, energy: 6, stress: -5 },
    actionType: 'recovery',
    effect: 'Физическая форма +4, Энергия +6, Стресс -5',
    mood: '🏃 Утро начинается с движения',
  },
  {
    id: 'fun_swimming',
    category: 'fun',
    title: 'Плавание в бассейне',
    hourCost: 1.5,
    price: 600,
    statChanges: { physical: 5, stress: -12, health: 3 },
    actionType: 'recovery',
    effect: 'Физическая форма +5, Стресс -12, Здоровье +3',
    mood: '🏊 Вода расслабляет и тонизирует',
  },
  {
    id: 'fun_chess',
    category: 'fun',
    title: 'Шахматы / головоломки',
    hourCost: 1.5,
    price: 0,
    statChanges: { mood: 6 },
    skillChanges: { analyticalThinking: 1 },
    actionType: 'recovery',
    effect: 'Настроение +6, Аналитическое мышление +1',
    mood: '♟️ Шахматы — гимнастика для ума',
  },
  {
    id: 'fun_deep_cleaning',
    category: 'fun',
    title: 'Генеральная уборка',
    hourCost: 4,
    price: 500,
    statChanges: { stress: -8 },
    skillChanges: { organization: 2 },
    housingComfortDelta: 20,
    actionType: 'recovery',
    effect: 'Стресс -8, Организация +2, Комфорт жилья +20',
    mood: '🧽 Генеральная уборка — обновление пространства',
  },
  {
    id: 'fun_shopping_therapy',
    category: 'fun',
    title: 'Шопинг-терапия',
    hourCost: 3,
    price: 3000,
    statChanges: { mood: 16, stress: -8 },
    actionType: 'recovery',
    effect: 'Настроение +16, Стресс -8',
    mood: '🛍️ Лечение покупками — работает!',
  },
  {
    id: 'fun_beach',
    category: 'fun',
    title: 'Загорать / отдых на пляже',
    hourCost: 4,
    price: 300,
    statChanges: { mood: 14, stress: -10, health: 2 },
    actionType: 'recovery',
    effect: 'Настроение +14, Стресс -10, Здоровье +2',
    mood: '🏖️ Солнце, песок и волны',
  },
];
