import { AgeGroup } from './types'
import type { BalanceAction } from './types'
export const CAREER_ACTIONS: BalanceAction[] = [
  {
    id: 'car_work_day',
    category: 'career',
    title: 'Обычный рабочий день',
    hourCost: 8,
    price: 0,
    statChanges: { hunger: 9.5, energy: -12.5, stress: 8.5, mood: 4.5, health: -0.8, physical: -1.5 },
    skillChanges: { professionalism: 2 },
    actionType: 'work',
    effect: 'Голод +9.5, Энергия -12.5, Стресс +8.5, Настроение +4.5, Здоровье -0.8, Физическая форма -1.5, Профессионализм +2',
    mood: '💼 Стандартный рабочий день — рутина, но стабильный доход',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'car_overtime',
    category: 'career',
    title: 'Сверхурочная работа',
    hourCost: 3,
    price: 0,
    statChanges: { hunger: 5.5, energy: -9.5, stress: 14.5, mood: -6.5, health: -1.5, physical: -2.2 },
    actionType: 'work',
    effect: 'Голод +5.5, Энергия -9.5, Стресс +14.5, Настроение -6.5, Здоровье -1.5, Физическая форма -2.2',
    mood: '⏰ Сверхурочные дают больше денег, но сильно выматывают',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'car_job_search',
    category: 'career',
    title: 'Активный поиск новой работы',
    hourCost: 4,
    price: 0,
    statChanges: { hunger: 5.2, energy: -7.5, stress: 6.5, mood: 5.5, health: -0.5, physical: -0.8 },
    skillChanges: { negotiations: 1.5, charisma: 1 },
    actionType: 'work',
    effect: 'Голод +5.2, Энергия -7.5, Стресс +6.5, Настроение +5.5, Здоровье -0.5, Физическая форма -0.8, Переговоры +1.5, Харизма +1',
    mood: '🔍 Поиск работы — это инвестиция времени в своё будущее',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'car_interview_prep',
    category: 'career',
    title: 'Подготовка к собеседованию',
    hourCost: 3,
    price: 0,
    statChanges: { hunger: 4.2, energy: -5.5, stress: -7.5, mood: 8.5, health: 0.5, physical: -0.6 },
    skillChanges: { negotiations: 3, professionalism: 2 },
    actionType: 'work',
    effect: 'Голод +4.2, Энергия -5.5, Стресс -7.5, Настроение +8.5, Здоровье +0.5, Физическая форма -0.6, Переговоры +3, Профессионализм +2',
    mood: '🗣️ Хорошая подготовка к интервью сильно повышает шансы',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'car_freelance',
    category: 'career',
    title: 'Выполнить фриланс-заказ',
    hourCost: 6,
    price: 0,
    statChanges: { hunger: 7.5, energy: -10.5, stress: 5.5, mood: 9.5, health: -0.7, physical: -1.2 },
    skillChanges: { basicCreativity: 3, professionalism: 2 },
    actionType: 'work',
    effect: 'Голод +7.5, Энергия -10.5, Стресс +5.5, Настроение +9.5, Здоровье -0.7, Физическая форма -1.2, Креативность +3, Профессионализм +2',
    mood: '💻 Фриланс — свобода графика и прямые деньги за результат',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'car_networking',
    category: 'career',
    title: 'Нетворкинг и полезные знакомства',
    hourCost: 3,
    price: 1500,
    statChanges: { hunger: 4.2, energy: -5, stress: -6.5, mood: 11.5, health: -0.3, physical: -0.6 },
    relationshipDelta: 10,
    skillChanges: { charisma: 2 },
    actionType: 'work',
    effect: 'Голод +4.2, Энергия -5, Стресс -6.5, Настроение +11.5, Здоровье -0.3, Физическая форма -0.6, Отношения +10, Харизма +2',
    mood: '🤝 Полезные связи часто открывают двери лучше, чем резюме',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'car_qualification',
    category: 'career',
    title: 'Повышение квалификации на текущей работе',
    hourCost: 4,
    price: 0,
    statChanges: { hunger: 5.5, energy: -7.5, stress: -5.5, mood: 8.5, health: 0.8, physical: -0.9 },
    skillChanges: { professionalism: 4 },
    actionType: 'work',
    effect: 'Голод +5.5, Энергия -7.5, Стресс -5.5, Настроение +8.5, Здоровье +0.8, Физическая форма -0.9, Профессионализм +4',
    mood: '📈 Повышение квалификации — прямой путь к росту внутри компании',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'car_career_change',
    category: 'career',
    title: 'Смена карьерного направления (переобучение)',
    hourCost: 8,
    price: 0,
    statChanges: { hunger: 10.5, energy: -14.5, stress: 9.5, mood: 7.5, health: -1.2, physical: -2 },
    skillChanges: { professionalism: 3, adaptability: 3 },
    actionType: 'work',
    effect: 'Голод +10.5, Энергия -14.5, Стресс +9.5, Настроение +7.5, Здоровье -1.2, Физическая форма -2, Профессионализм +3, Адаптивность +3',
    mood: '🔄 Смена карьеры — смелый, но часто очень правильный шаг',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'car_ask_promotion',
    category: 'career',
    title: 'Запросить повышение зарплаты или должности',
    hourCost: 1,
    price: 0,
    statChanges: { hunger: 1.8, energy: -3, stress: 7.5, mood: -2.5, health: -0.3, physical: -0.4 },
    skillChanges: { negotiations: 2.5, charisma: 1 },
    actionType: 'work',
    effect: 'Голод +1.8, Энергия -3, Стресс +7.5, Настроение -2.5, Здоровье -0.3, Физическая форма -0.4, Переговоры +2.5, Харизма +1',
    mood: '📈 Просьба о повышении — всегда волнительно, но необходимо',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'car_remote',
    category: 'career',
    title: 'Перейти на полностью удалённую работу',
    hourCost: 2,
    price: 0,
    statChanges: { hunger: 3.5, energy: -4.5, stress: -12.5, mood: 10.5, health: 1.2, physical: -0.8 },
    housingComfortDelta: 8,
    actionType: 'work',
    effect: 'Голод +3.5, Энергия -4.5, Стресс -12.5, Настроение +10.5, Здоровье +1.2, Физическая форма -0.8, Комфорт жилья +8',
    mood: '🏠 Удалёнка экономит время на дорогу и повышает комфорт жизни',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'car_side_project',
    category: 'career',
    title: 'Запустить личный side-project',
    hourCost: 6,
    price: 5000,
    statChanges: { hunger: 7.5, energy: -10.5, stress: -4.5, mood: 12.5, health: -0.6, physical: -1.2 },
    skillChanges: { specialization: 3.5, basicCreativity: 2 },
    actionType: 'work',
    effect: 'Голод +7.5, Энергия -10.5, Стресс -4.5, Настроение +12.5, Здоровье -0.6, Физическая форма -1.2, Специализация +3.5, Креативность +2',
    mood: '🌱 Side-project — это семя, которое может вырасти во что-то большое',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'car_mentor',
    category: 'career',
    title: 'Наставничество над младшими коллегами',
    hourCost: 3,
    price: 0,
    statChanges: { hunger: 4.2, energy: -5.5, stress: -6.5, mood: 11.5, health: 0.8, physical: -0.6 },
    relationshipDelta: 8,
    skillChanges: { leadership: 3, professionalism: 2 },
    actionType: 'work',
    effect: 'Голод +4.2, Энергия -5.5, Стресс -6.5, Настроение +11.5, Здоровье +0.8, Физическая форма -0.6, Отношения +8, Лидерство +3, Профессионализм +2',
    mood: '👨‍🏫 Когда помогаешь другим расти — растешь и сам',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'car_conference',
    category: 'career',
    title: 'Выступление на конференции или митапе',
    hourCost: 4,
    price: 2000,
    statChanges: { hunger: 5.5, energy: -7.5, stress: -5.5, mood: 13.5, health: -0.4, physical: -0.9 },
    relationshipDelta: 10,
    skillChanges: { charisma: 3.5, professionalism: 2 },
    actionType: 'work',
    effect: 'Голод +5.5, Энергия -7.5, Стресс -5.5, Настроение +13.5, Здоровье -0.4, Физическая форма -0.9, Отношения +10, Харизма +3.5, Профессионализм +2',
    mood: '🎤 Публичное выступление — мощный буст для репутации',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'car_write_article',
    category: 'career',
    title: 'Написать статью для профильного издания',
    hourCost: 5,
    price: 0,
    statChanges: { hunger: 6.5, energy: -8.5, stress: -6.5, mood: 11.5, health: -0.5, physical: -1 },
    skillChanges: { writing: 3, professionalism: 3 },
    actionType: 'work',
    effect: 'Голод +6.5, Энергия -8.5, Стресс -6.5, Настроение +11.5, Здоровье -0.5, Физическая форма -1, Писательское мастерство +3, Профессионализм +3',
    mood: '🖋️ Статья от твоего имени — это личный бренд в профессиональной среде',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'car_certification',
    category: 'career',
    title: 'Пройти профессиональную аттестацию / сертификацию',
    hourCost: 3,
    price: 0,
    statChanges: { hunger: 4.5, energy: -6.5, stress: -8.5, mood: 9.5, health: 1.2, physical: -0.7 },
    skillChanges: { professionalism: 4 },
    actionType: 'work',
    effect: 'Голод +4.5, Энергия -6.5, Стресс -8.5, Настроение +9.5, Здоровье +1.2, Физическая форма -0.7, Профессионализм +4',
    mood: '📜 Сертификат — официальное подтверждение твоей экспертизы',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'car_open_business',
    category: 'career',
    title: 'Открыть собственный бизнес',
    hourCost: 8,
    price: 200000,
    statChanges: { hunger: 11.5, energy: -16.5, stress: 14.5, mood: 8.5, health: -1.5, physical: -2.5 },
    skillChanges: { leadership: 4, financialLiteracy: 3 },
    actionType: 'work',
    effect: 'Голод +11.5, Энергия -16.5, Стресс +14.5, Настроение +8.5, Здоровье -1.5, Физическая форма -2.5, Лидерство +4, Финансовая грамотность +3',
    mood: '🏢 Свой бизнес — это свобода, риск и огромная ответственность',
    ageGroup: AgeGroup.ADULT,
  },
]