import type { BalanceAction } from './types'
import { AgeGroup } from './types'

/**
 * Child actions, адаптированные под тип BalanceAction для интеграции в runtime.
 * Оригинальный файл child-actions.ts содержит действия с другой структурой (description вместо effect).
 * Этот файл содержит конвертированные действия, совместимые с ActionSystem.
 */
export const CHILD_ACTIONS_REGISTERED: BalanceAction[] = [
  // ==============================================
  // 0-3 года (INFANT / TODDLER)
  // ==============================================
  {
    id: 'infant_cry_hungry',
    category: 'home',
    title: 'Плакать когда голоден',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Сообщить всему миру что ты голоден',
    statChanges: { stress: 25, mood: -10 },
    ageGroup: AgeGroup.INFANT,
    maxAgeGroup: AgeGroup.INFANT,
  },
  {
    id: 'infant_cry_lonely',
    category: 'home',
    title: 'Плакать когда один',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Тебе не комфортно быть одному',
    statChanges: { stress: 20, mood: -15 },
    ageGroup: AgeGroup.INFANT,
    maxAgeGroup: AgeGroup.INFANT,
  },
  {
    id: 'infant_watch_moving',
    category: 'selfdev',
    title: 'Смотри на движущиеся объекты',
    hourCost: 1,
    price: 0,
    actionType: 'neutral',
    effect: 'Следить глазами за тем что движется',
    statChanges: { mood: 10 },
    skillChanges: { observation: 0.5, attention: 0.3 },
    ageGroup: AgeGroup.INFANT,
    maxAgeGroup: AgeGroup.INFANT,
  },
  {
    id: 'infant_smile_back',
    category: 'social',
    title: 'Улыбайся в ответ',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Ответить улыбкой на улыбку',
    statChanges: { mood: 15, stress: -5 },
    skillChanges: { empathy: 0.7, trust: 0.5 },
    ageGroup: AgeGroup.INFANT,
    maxAgeGroup: AgeGroup.INFANT,
  },
  {
    id: 'infant_grab_everything',
    category: 'fun',
    title: 'Хватай всё что попадает под руку',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Исследовать мир на ощупь',
    statChanges: { mood: 10 },
    skillChanges: { fine_motor: 0.6, curiosity: 0.4 },
    ageGroup: AgeGroup.INFANT,
    maxAgeGroup: AgeGroup.INFANT,
  },
  {
    id: 'infant_fall_hurt',
    category: 'health',
    title: 'Падай и ушибайся',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Учиться падать и вставать',
    statChanges: { mood: -10, stress: 15, physical: 5 },
    skillChanges: { coordination: 0.8 },
    ageGroup: AgeGroup.INFANT,
    maxAgeGroup: AgeGroup.INFANT,
  },
  {
    id: 'infant_explore_sounds',
    category: 'selfdev',
    title: 'Изучай звуки',
    hourCost: 1,
    price: 0,
    actionType: 'neutral',
    effect: 'Слушать и пробовать издавать разные звуки',
    statChanges: { mood: 12 },
    skillChanges: { hearing: 0.7, musical_ear: 0.5 },
    ageGroup: AgeGroup.INFANT,
    maxAgeGroup: AgeGroup.INFANT,
  },
  {
    id: 'toddler_crawl_forbidden',
    category: 'fun',
    title: 'Ползай в неразрешённые места',
    hourCost: 1,
    price: 0,
    actionType: 'neutral',
    effect: 'Туда куда нельзя особенно интересно',
    statChanges: { mood: 20, energy: -10 },
    skillChanges: { curiosity: 1.0, courage: 0.5 },
    ageGroup: AgeGroup.INFANT,
    maxAgeGroup: AgeGroup.INFANT,
  },
  {
    id: 'toddler_bite_everything',
    category: 'fun',
    title: 'Кусать всё что можно',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Зубы чешутся и мир надо попробовать на вкус',
    statChanges: { mood: 10, stress: -8 },
    ageGroup: AgeGroup.INFANT,
    maxAgeGroup: AgeGroup.INFANT,
  },
  {
    id: 'infant_sleep_wrong_time',
    category: 'health',
    title: 'Спать в неподходящее время',
    hourCost: 2,
    price: 0,
    actionType: 'sleep',
    effect: 'Всегда хочешь спать именно когда не надо',
    statChanges: { energy: 25, stress: -10 },
    ageGroup: AgeGroup.INFANT,
    maxAgeGroup: AgeGroup.INFANT,
  },
  {
    id: 'toddler_refuse_food',
    category: 'home',
    title: 'Отказываться от еды',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Эта еда явно не очень хорошая',
    statChanges: { mood: -5, stress: 10 },
    skillChanges: { willpower: 0.4 },
    ageGroup: AgeGroup.INFANT,
    maxAgeGroup: AgeGroup.INFANT,
  },
  {
    id: 'toddler_repeat_sounds',
    category: 'selfdev',
    title: 'Повторять звуки которые слышишь',
    hourCost: 1,
    price: 0,
    actionType: 'neutral',
    effect: 'Попробовать сказать то что говорят взрослые',
    statChanges: { mood: 15 },
    skillChanges: { speech: 0.9, language: 0.7 },
    ageGroup: AgeGroup.INFANT,
    maxAgeGroup: AgeGroup.INFANT,
  },
  {
    id: 'toddler_throw_things',
    category: 'fun',
    title: 'Бросать предметы на пол',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Посмотреть что будет если бросить',
    statChanges: { mood: 12 },
    skillChanges: { logic: 0.5 },
    ageGroup: AgeGroup.INFANT,
    maxAgeGroup: AgeGroup.INFANT,
  },
  {
    id: 'infant_laugh_no_reason',
    category: 'fun',
    title: 'Смеяться без причины',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Просто так, потому что хорошо',
    statChanges: { mood: 25, stress: -15 },
    ageGroup: AgeGroup.INFANT,
    maxAgeGroup: AgeGroup.INFANT,
  },
  {
    id: 'infant_scare_strangers',
    category: 'social',
    title: 'Пугаться незнакомых людей',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Этот человек точно плохой',
    statChanges: { stress: 20, mood: -10 },
    skillChanges: { observation: 0.6 },
    ageGroup: AgeGroup.INFANT,
    maxAgeGroup: AgeGroup.INFANT,
  },

  // ==============================================
  // 4-7 лет (CHILD)
  // ==============================================
  {
    id: 'child_fight_toys',
    category: 'social',
    title: 'Драться за игрушки',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Эта игрушка моя!',
    statChanges: { mood: 15, stress: -5 },
    skillChanges: { aggression: 0.8 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_share_toys',
    category: 'social',
    title: 'Делиться игрушками',
    hourCost: 1.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Давай играть вместе',
    statChanges: { mood: 20, stress: -10 },
    skillChanges: { empathy: 1.0, generosity: 0.7 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_hide_from_teacher',
    category: 'fun',
    title: 'Прятаться от воспитателя',
    hourCost: 1,
    price: 0,
    actionType: 'neutral',
    effect: 'Она точно не найдёт тебя здесь',
    statChanges: { mood: 18, stress: -3 },
    skillChanges: { stealth: 0.8, observation: 0.5 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_memorize_poem',
    category: 'selfdev',
    title: 'Заучивать стихи наизусть',
    hourCost: 2,
    price: 0,
    actionType: 'neutral',
    effect: 'Надо запомнить все строчки',
    statChanges: { mood: 5, stress: 8 },
    skillChanges: { memory: 1.2, language: 0.8 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_taste_everything',
    category: 'fun',
    title: 'Пробовать всё на вкус',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Надо проверить на вкус',
    statChanges: { mood: 8, health: -2 },
    skillChanges: { curiosity: 0.6 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_blame_others',
    category: 'social',
    title: 'Винить других во всём',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Они сами виноваты',
    statChanges: { mood: 10, stress: -5 },
    skillChanges: { manipulation: 0.7, dishonesty: 0.5 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_apologize',
    category: 'social',
    title: 'Извиняться когда виноват',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Нельзя обижать маленьких',
    statChanges: { mood: -5, stress: -8 },
    skillChanges: { empathy: 0.9, honesty: 0.6 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_draw_walls',
    category: 'fun',
    title: 'Рисовать на стенах',
    hourCost: 1.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Стены это самый лучший холст',
    statChanges: { mood: 25, stress: -10 },
    skillChanges: { creativity: 1.0, fine_motor: 0.5 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_run_circles',
    category: 'fun',
    title: 'Бегать кругами',
    hourCost: 1,
    price: 0,
    actionType: 'neutral',
    effect: 'Ещё круг! Ещё один!',
    statChanges: { mood: 20, energy: -15, physical: 2 },
    skillChanges: { stamina: 0.8 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_ask_why',
    category: 'selfdev',
    title: 'Спрашивать "почему"',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'А почему небо синее?',
    statChanges: { mood: 5, stress: 2 },
    skillChanges: { curiosity: 1.2, logic: 0.6 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_tell_lie',
    category: 'social',
    title: 'Врать чтобы избежать наказания',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Сегодня точно не будет ничего важного',
    statChanges: { mood: 5, stress: -10 },
    skillChanges: { deception: 0.8, quick_thinking: 0.5 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_do_homework',
    category: 'selfdev',
    title: 'Делать домашнее задание',
    hourCost: 2,
    price: 0,
    actionType: 'neutral',
    effect: 'Уроки из школы',
    statChanges: { mood: -5, stress: 5 },
    skillChanges: { discipline: 1.0, learning: 0.8 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_help_mom',
    category: 'home',
    title: 'Помогать маме по дому',
    hourCost: 1.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Она всё равно не откажется',
    statChanges: { mood: 10, stress: -5 },
    skillChanges: { helpfulness: 1.0, responsibility: 0.7 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_collect_things',
    category: 'fun',
    title: 'Собирать коллекцию',
    hourCost: 1,
    price: 0,
    actionType: 'neutral',
    effect: 'У старшеклассников самые крутые слова',
    statChanges: { mood: 15, stress: -3 },
    skillChanges: { organization: 0.6, focus: 0.5 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_sneak_out',
    category: 'fun',
    title: 'Незаметно выйти из дома',
    hourCost: 1,
    price: 0,
    actionType: 'neutral',
    effect: 'Никто точно не увидит',
    statChanges: { mood: 20, stress: 5 },
    skillChanges: { stealth: 1.0, courage: 0.8 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_read_books',
    category: 'selfdev',
    title: 'Читать книги',
    hourCost: 2,
    price: 0,
    actionType: 'neutral',
    effect: 'Внезапно книги становятся интересными',
    statChanges: { mood: 10, stress: -5 },
    skillChanges: { reading: 1.2, vocabulary: 0.8 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_play_sports',
    category: 'health',
    title: 'Играть в спорт',
    hourCost: 2,
    price: 0,
    actionType: 'neutral',
    effect: 'Падать сто раз пока не получится',
    statChanges: { mood: 15, energy: -20, physical: 5, health: 2 },
    skillChanges: { stamina: 1.0, coordination: 0.8 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_make_friends',
    category: 'social',
    title: 'Заводить друзей',
    hourCost: 1,
    price: 0,
    actionType: 'neutral',
    effect: 'Никто никогда не узнает',
    statChanges: { mood: 20, stress: -8 },
    skillChanges: { social: 1.0, empathy: 0.7 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_break_things',
    category: 'fun',
    title: 'Ломать вещи',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Теперь ты понимаешь о чём все песни',
    statChanges: { mood: 10, stress: 3 },
    skillChanges: { destruction: 0.8, curiosity: 0.5 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_be_kind',
    category: 'social',
    title: 'Быть добрым к другим',
    hourCost: 1,
    price: 0,
    actionType: 'neutral',
    effect: 'Теперь тебе верят всегда',
    statChanges: { mood: 15, stress: -10 },
    skillChanges: { kindness: 1.2, empathy: 0.8 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_learn_music',
    category: 'selfdev',
    title: 'Учиться музыке',
    hourCost: 2,
    price: 0,
    actionType: 'neutral',
    effect: 'Попробовать и понять что это скучно',
    statChanges: { mood: 10, stress: -5 },
    skillChanges: { musical_ear: 1.0, rhythm: 0.8 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_tell_secrets',
    category: 'social',
    title: 'Рассказывать секреты',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Руки растут из правильного места',
    statChanges: { mood: 12, stress: -3 },
    skillChanges: { trust: 0.7, communication: 0.5 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_ignore_rules',
    category: 'fun',
    title: 'Игнорировать правила',
    hourCost: 1,
    price: 0,
    actionType: 'neutral',
    effect: 'Правила для других',
    statChanges: { mood: 18, stress: 2 },
    skillChanges: { rebellion: 0.8, independence: 0.6 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_admit_mistake',
    category: 'social',
    title: 'Признавать ошибки',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Извини, я был неправ',
    statChanges: { mood: -5, stress: -10 },
    skillChanges: { honesty: 1.0, responsibility: 0.8 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_explore_nature',
    category: 'fun',
    title: 'Исследовать природу',
    hourCost: 2,
    price: 0,
    actionType: 'neutral',
    effect: 'Природа полна чудес',
    statChanges: { mood: 20, stress: -8, health: 3 },
    skillChanges: { observation: 1.0, knowledge: 0.7 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_compete',
    category: 'fun',
    title: 'Соревноваться с другими',
    hourCost: 1.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Я выиграю!',
    statChanges: { mood: 15, stress: 5 },
    skillChanges: { competitiveness: 1.0, determination: 0.7 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_share_food',
    category: 'social',
    title: 'Делиться едой',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Хочешь?',
    statChanges: { mood: 12, stress: -5 },
    skillChanges: { generosity: 0.9, kindness: 0.7 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_ask_questions',
    category: 'selfdev',
    title: 'Задавать много вопросов',
    hourCost: 1,
    price: 0,
    actionType: 'neutral',
    effect: 'А почему? А как?',
    statChanges: { mood: 8, stress: 2 },
    skillChanges: { curiosity: 1.2, learning: 0.8 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_play_alone',
    category: 'fun',
    title: 'Играть одному',
    hourCost: 1.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Мне и так весело',
    statChanges: { mood: 15, stress: -5 },
    skillChanges: { independence: 0.8, creativity: 0.6 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_follow_rules',
    category: 'social',
    title: 'Следовать правилам',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Правила существуют не просто так',
    statChanges: { mood: 5, stress: -8 },
    skillChanges: { discipline: 1.0, responsibility: 0.7 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_be_brave',
    category: 'fun',
    title: 'Быть смелым',
    hourCost: 1,
    price: 0,
    actionType: 'neutral',
    effect: 'Я не боюсь!',
    statChanges: { mood: 18, stress: -3 },
    skillChanges: { courage: 1.2, confidence: 0.8 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_help_others',
    category: 'social',
    title: 'Помогать другим',
    hourCost: 1,
    price: 0,
    actionType: 'neutral',
    effect: 'Чем могу помочь?',
    statChanges: { mood: 15, stress: -8 },
    skillChanges: { helpfulness: 1.0, empathy: 0.7 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_learn_from_mistakes',
    category: 'selfdev',
    title: 'Учиться на ошибках',
    hourCost: 1,
    price: 0,
    actionType: 'neutral',
    effect: 'В следующий раз сделаю лучше',
    statChanges: { mood: 5, stress: -5 },
    skillChanges: { learning: 1.0, wisdom: 0.7 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_be_honest',
    category: 'social',
    title: 'Быть честным',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Правда всегда лучше',
    statChanges: { mood: 10, stress: -5 },
    skillChanges: { honesty: 1.2, integrity: 0.8 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_explore_world',
    category: 'fun',
    title: 'Исследовать мир',
    hourCost: 2,
    price: 0,
    actionType: 'neutral',
    effect: 'Мир так велик и интересен',
    statChanges: { mood: 20, stress: -8, knowledge: 2 },
    skillChanges: { curiosity: 1.0, observation: 0.8 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_be_patient',
    category: 'selfdev',
    title: 'Быть терпеливым',
    hourCost: 1,
    price: 0,
    actionType: 'neutral',
    effect: 'Подожду ещё немного',
    statChanges: { mood: 5, stress: -5 },
    skillChanges: { patience: 1.2, self_control: 0.8 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_be_creative',
    category: 'fun',
    title: 'Быть творческим',
    hourCost: 1.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Придумаю что-нибудь новое',
    statChanges: { mood: 18, stress: -5 },
    skillChanges: { creativity: 1.2, imagination: 0.8 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_be_responsible',
    category: 'social',
    title: 'Быть ответственным',
    hourCost: 1,
    price: 0,
    actionType: 'neutral',
    effect: 'Я сделаю это',
    statChanges: { mood: 10, stress: -5 },
    skillChanges: { responsibility: 1.2, reliability: 0.8 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_be_curious',
    category: 'selfdev',
    title: 'Быть любопытным',
    hourCost: 1,
    price: 0,
    actionType: 'neutral',
    effect: 'Хочу узнать больше',
    statChanges: { mood: 12, stress: -3 },
    skillChanges: { curiosity: 1.2, learning: 0.8 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_be_friendly',
    category: 'social',
    title: 'Быть дружелюбным',
    hourCost: 0.5,
    price: 0,
    actionType: 'neutral',
    effect: 'Привет! Как дела?',
    statChanges: { mood: 15, stress: -8 },
    skillChanges: { social: 1.0, friendliness: 0.8 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
  {
    id: 'child_be_adventurous',
    category: 'fun',
    title: 'Быть adventurous',
    hourCost: 2,
    price: 0,
    actionType: 'neutral',
    effect: 'К новым приключениям!',
    statChanges: { mood: 20, stress: -5 },
    skillChanges: { courage: 1.0, adventure: 0.8 },
    ageGroup: AgeGroup.CHILD,
    maxAgeGroup: AgeGroup.CHILD,
  },
]
