import { AgeGroup } from './types'

export const CHILD_ACTIONS = [
  // ==============================================
  // 0-3 года (INFANT / TODDLER) - 15 действий
  // ==============================================
  {
    id: 'infant_cry_hungry',
    title: 'Плакать когда голоден',
    description: 'Сообщить всему миру что ты голоден',
    category: 'basic',
    ageGroup: AgeGroup.INFANT,
    hourCost: 0.5,
    price: 0,
    statChanges: { stress: 25, mood: -10 },
  },
  {
    id: 'infant_cry_lonely',
    title: 'Плакать когда один',
    description: 'Тебе не комфортно быть одному',
    category: 'basic',
    ageGroup: AgeGroup.INFANT,
    hourCost: 0.5,
    price: 0,
    statChanges: { stress: 20, mood: -15 },
  },
  {
    id: 'infant_watch_moving',
    title: 'Смотри на движущиеся объекты',
    description: 'Следить глазами за тем что движется',
    category: 'selfdev',
    ageGroup: AgeGroup.INFANT,
    hourCost: 1,
    price: 0,
    statChanges: { mood: 10 },
    skillChanges: { observation: 0.5, attention: 0.3 },
  },
  {
    id: 'infant_smile_back',
    title: 'Улыбайся в ответ',
    description: 'Ответить улыбкой на улыбку',
    category: 'social',
    ageGroup: AgeGroup.INFANT,
    hourCost: 0.5,
    price: 0,
    statChanges: { mood: 15, stress: -5 },
    skillChanges: { empathy: 0.7, trust: 0.5 },
  },
  {
    id: 'infant_grab_everything',
    title: 'Хватай всё что попадает под руку',
    description: 'Исследовать мир на ощупь',
    category: 'fun',
    ageGroup: AgeGroup.INFANT,
    hourCost: 0.5,
    price: 0,
    statChanges: { mood: 10 },
    skillChanges: { fine_motor: 0.6, curiosity: 0.4 },
  },
  {
    id: 'infant_fall_hurt',
    title: 'Падай и ушибайся',
    description: 'Учиться падать и вставать',
    category: 'health',
    ageGroup: AgeGroup.INFANT,
    hourCost: 0.5,
    price: 0,
    statChanges: { mood: -10, stress: 15, physical: 5 },
    skillChanges: { coordination: 0.8 },
  },
  {
    id: 'infant_explore_sounds',
    title: 'Изучай звуки',
    description: 'Слушать и пробовать издавать разные звуки',
    category: 'selfdev',
    ageGroup: AgeGroup.INFANT,
    hourCost: 1,
    price: 0,
    statChanges: { mood: 12 },
    skillChanges: { hearing: 0.7, musical_ear: 0.5 },
  },
  {
    id: 'toddler_crawl_forbidden',
    title: 'Ползай в неразрешённые места',
    description: 'Туда куда нельзя особенно интересно',
    category: 'fun',
    ageGroup: AgeGroup.INFANT,
    hourCost: 1,
    price: 0,
    statChanges: { mood: 20, energy: -10 },
    skillChanges: { curiosity: 1.0, courage: 0.5 },
  },
  {
    id: 'toddler_bite_everything',
    title: 'Кусать всё что можно',
    description: 'Зубы чешутся и мир надо попробовать на вкус',
    category: 'fun',
    ageGroup: AgeGroup.INFANT,
    hourCost: 0.5,
    price: 0,
    statChanges: { mood: 10, stress: -8 },
  },
  {
    id: 'infant_sleep_wrong_time',
    title: 'Спать в неподходящее время',
    description: 'Всегда хочешь спать именно когда не надо',
    category: 'health',
    ageGroup: AgeGroup.INFANT,
    hourCost: 2,
    price: 0,
    statChanges: { energy: 25, stress: -10 },
  },
  {
    id: 'toddler_refuse_food',
    title: 'Отказываться от еды',
    description: 'Эта еда явно не очень хорошая',
    category: 'basic',
    ageGroup: AgeGroup.INFANT,
    hourCost: 0.5,
    price: 0,
    statChanges: { mood: -5, stress: 10 },
    skillChanges: { willpower: 0.4 },
  },
  {
    id: 'toddler_repeat_sounds',
    title: 'Повторять звуки которые слышишь',
    description: 'Попробовать сказать то что говорят взрослые',
    category: 'selfdev',
    ageGroup: AgeGroup.INFANT,
    hourCost: 1,
    price: 0,
    statChanges: { mood: 15 },
    skillChanges: { speech: 0.9, language: 0.7 },
  },
  {
    id: 'toddler_throw_things',
    title: 'Бросать предметы на пол',
    description: 'Посмотреть что будет если бросить',
    category: 'fun',
    ageGroup: AgeGroup.INFANT,
    hourCost: 0.5,
    price: 0,
    statChanges: { mood: 12 },
    skillChanges: { logic: 0.5 },
  },
  {
    id: 'infant_laugh_no_reason',
    title: 'Смеяться без причины',
    description: 'Просто так, потому что хорошо',
    category: 'fun',
    ageGroup: AgeGroup.INFANT,
    hourCost: 0.5,
    price: 0,
    statChanges: { mood: 25, stress: -15 },
  },
  {
    id: 'infant_scare_strangers',
    title: 'Пугаться незнакомых людей',
    description: 'Этот человек точно плохой',
    category: 'social',
    ageGroup: AgeGroup.INFANT,
    hourCost: 0.5,
    price: 0,
    statChanges: { stress: 20, mood: -10 },
    skillChanges: { observation: 0.6 },
  },

  // ==============================================
  // 4-7 лет (CHILD) - 16 действий
  // ==============================================
  {
    id: 'child_fight_toys',
    title: 'Драться за игрушки',
    description: 'Эта игрушка моя!',
    category: 'social',
    ageGroup: AgeGroup.CHILD,
    hourCost: 0.5,
    price: 0,
    statChanges: { mood: 15, stress: -5 },
    skillChanges: { aggression: 0.8 },
  },
  {
    id: 'child_share_toys',
    title: 'Делиться игрушками',
    description: 'Давай играть вместе',
    category: 'social',
    ageGroup: AgeGroup.CHILD,
    hourCost: 1.5,
    price: 0,
    statChanges: { mood: 20, stress: -10 },
    skillChanges: { empathy: 1.0, generosity: 0.7 },
  },
  {
    id: 'child_hide_from_teacher',
    title: 'Прятаться от воспитателя',
    description: 'Она точно не найдёт тебя здесь',
    category: 'fun',
    ageGroup: AgeGroup.CHILD,
    hourCost: 1,
    price: 0,
    statChanges: { mood: 25, stress: 10 },
    skillChanges: { stealth: 0.7 },
  },
  {
    id: 'child_learn_poem',
    title: 'Учить стихи на утренник',
    description: 'Надо запомнить все строчки',
    category: 'education',
    ageGroup: AgeGroup.CHILD,
    hourCost: 2,
    price: 0,
    statChanges: { mood: 5, energy: -10 },
    skillChanges: { memory: 1.2, speech: 0.9 },
  },
  {
    id: 'child_tell_stories',
    title: 'Рассказывать выдуманные истории',
    description: 'А у меня дома был динозавр...',
    category: 'fun',
    ageGroup: AgeGroup.CHILD,
    hourCost: 1,
    price: 0,
    statChanges: { mood: 25 },
    skillChanges: { creativity: 1.3, imagination: 1.1 },
  },
  {
    id: 'child_eat_sand',
    title: 'Есть песок на площадке',
    description: 'Надо проверить на вкус',
    category: 'fun',
    ageGroup: AgeGroup.CHILD,
    hourCost: 0.5,
    price: 0,
    statChanges: { mood: 5, health: -5 },
    skillChanges: { curiosity: 0.6 },
  },
  {
    id: 'child_hit_others',
    title: 'Бить других детей',
    description: 'Они сами виноваты',
    category: 'social',
    ageGroup: AgeGroup.CHILD,
    hourCost: 0.5,
    price: 0,
    statChanges: { mood: 10, stress: -8 },
    skillChanges: { aggression: 1.0 },
  },
  {
    id: 'child_protect_weak',
    title: 'Защищать слабых',
    description: 'Нельзя обижать маленьких',
    category: 'social',
    ageGroup: AgeGroup.CHILD,
    hourCost: 1,
    price: 0,
    statChanges: { mood: 30, stress: -15 },
    skillChanges: { courage: 1.1, justice: 1.0, empathy: 0.8 },
  },
  {
    id: 'child_draw_walls',
    title: 'Рисовать на обоях',
    description: 'Стены это самый лучший холст',
    category: 'hobby',
    ageGroup: AgeGroup.CHILD,
    hourCost: 1.5,
    price: 0,
    statChanges: { mood: 30, stress: -10 },
    skillChanges: { creativity: 1.5, art: 0.9 },
  },
  {
    id: 'child_run_until_fall',
    title: 'Бегать пока не упадёшь',
    description: 'Ещё круг! Ещё один!',
    category: 'fun',
    ageGroup: AgeGroup.CHILD,
    hourCost: 2,
    price: 0,
    statChanges: { mood: 35, energy: -30, physical: 8 },
    skillChanges: { endurance: 1.0, coordination: 0.7 },
  },
  {
    id: 'child_ask_eternal_questions',
    title: 'Задаваться вечными вопросами',
    description: 'А почему небо синее?',
    category: 'selfdev',
    ageGroup: AgeGroup.CHILD,
    hourCost: 1,
    price: 0,
    statChanges: { mood: 15 },
    skillChanges: { curiosity: 1.4, logic: 0.6 },
  },
  {
    id: 'child_fear_dark',
    title: 'Бояться темноты',
    description: 'В темноте точно кто-то есть',
    category: 'basic',
    ageGroup: AgeGroup.CHILD,
    hourCost: 0.5,
    price: 0,
    statChanges: { stress: 25, mood: -15 },
    skillChanges: { imagination: 0.8 },
  },
  {
    id: 'child_pretend_superhero',
    title: 'Говорить всем что ты супермен',
    description: 'Сейчас я полечу!',
    category: 'fun',
    ageGroup: AgeGroup.CHILD,
    hourCost: 1,
    price: 0,
    statChanges: { mood: 25 },
    skillChanges: { confidence: 1.1, imagination: 0.9 },
  },
  {
    id: 'child_lie_avoid_punishment',
    title: 'Лгать чтобы не наказали',
    description: 'Это не я это кот',
    category: 'social',
    ageGroup: AgeGroup.CHILD,
    hourCost: 0.5,
    price: 0,
    statChanges: { stress: 15, mood: 5 },
    skillChanges: { lying: 0.7 },
  },
  {
    id: 'child_bring_stray_animal',
    title: 'Приводить домой бездомных животных',
    description: 'Мама можно мы его оставим?',
    category: 'social',
    ageGroup: AgeGroup.CHILD,
    hourCost: 1.5,
    price: 0,
    statChanges: { mood: 30, stress: 10 },
    skillChanges: { empathy: 1.3, responsibility: 0.6 },
  },
  {
    id: 'child_play_outside',
    title: 'Играть на улице',
    description: 'Бегать во дворе',
    category: 'fun',
    ageGroup: AgeGroup.CHILD,
    hourCost: 3,
    price: 0,
    statChanges: { physical: 10, mood: 30, stress: -20, energy: -25 },
  },

  // ==============================================
  // 8-12 лет (KID) - 18 действий
  // ==============================================
  {
    id: 'kid_skip_lessons',
    title: 'Пропускать уроки',
    description: 'Сегодня точно не будет ничего важного',
    category: 'education',
    ageGroup: AgeGroup.KID,
    hourCost: 3,
    price: 0,
    statChanges: { mood: 25, stress: 20, energy: 5 },
    skillChanges: { risk_taking: 0.9 },
  },
  {
    id: 'kid_do_homework',
    title: 'Делать домашнее задание',
    description: 'Уроки из школы',
    category: 'education',
    ageGroup: AgeGroup.KID,
    hourCost: 2,
    price: 0,
    statChanges: { stress: 10, energy: -15, mood: -10 },
    skillChanges: { logic: 1.0, memory: 1.0, responsibility: 0.8 },
  },
  {
    id: 'kid_cheat_homework',
    title: 'Списывать у отличницы',
    description: 'Она всё равно не откажется',
    category: 'education',
    ageGroup: AgeGroup.KID,
    hourCost: 0.5,
    price: 0,
    statChanges: { mood: 15, stress: 15 },
    skillChanges: { lying: 1.0, social: 0.7 },
  },
  {
    id: 'kid_collect_useless',
    title: 'Собирать коллекцию чего-то бесполезного',
    description: 'Вкладывать всю душу в то что никому не нужно',
    category: 'hobby',
    ageGroup: AgeGroup.KID,
    hourCost: 2,
    price: 0,
    statChanges: { mood: 25, stress: -15 },
    skillChanges: { persistence: 1.1, attention: 0.9 },
  },
  {
    id: 'kid_play_until_dark',
    title: 'Играть до темноты на улице',
    description: 'Мама зовёт домой но ещё один раунд',
    category: 'fun',
    ageGroup: AgeGroup.KID,
    hourCost: 4,
    price: 0,
    statChanges: { mood: 40, stress: -25, energy: -35, physical: 10 },
    skillChanges: { friendship: 1.2 },
  },
  {
    id: 'kid_learn_curse_words',
    title: 'Учить ругательства',
    description: 'У старшеклассников самые крутые слова',
    category: 'social',
    ageGroup: AgeGroup.KID,
    hourCost: 0.5,
    price: 0,
    statChanges: { mood: 15 },
    skillChanges: { social: 0.8 },
  },
  {
    id: 'kid_steal_small_thing',
    title: 'Украсть что-то маленькое в магазине',
    description: 'Никто точно не увидит',
    category: 'social',
    ageGroup: AgeGroup.KID,
    hourCost: 0.5,
    price: 0,
    statChanges: { mood: 20, stress: 30 },
    skillChanges: { risk_taking: 1.3, stealth: 1.0 },
  },
  {
    id: 'kid_start_reading',
    title: 'Начать читать книги',
    description: 'Внезапно книги становятся интересными',
    category: 'selfdev',
    ageGroup: AgeGroup.KID,
    hourCost: 2.5,
    price: 0,
    statChanges: { mood: 20, stress: -10, energy: -5 },
    skillChanges: { literacy: 1.4, imagination: 1.2, vocabulary: 1.1 },
  },
  {
    id: 'kid_learn_bike',
    title: 'Научиться ездить на велосипеде',
    description: 'Падать сто раз пока не получится',
    category: 'health',
    ageGroup: AgeGroup.KID,
    hourCost: 3,
    price: 0,
    statChanges: { mood: 35, stress: -20, energy: -30, physical: 15 },
    skillChanges: { coordination: 1.5, persistence: 1.3, confidence: 1.2 },
  },
  {
    id: 'kid_break_and_hide',
    title: 'Сломать что-то важное и скрыть',
    description: 'Никто никогда не узнает',
    category: 'social',
    ageGroup: AgeGroup.KID,
    hourCost: 1,
    price: 0,
    statChanges: { stress: 40, mood: -10 },
    skillChanges: { lying: 1.2 },
  },
  {
    id: 'kid_make_friend',
    title: 'Подружиться с соседским мальчиком',
    description: 'Теперь вы лучшие друзья навсегда',
    category: 'social',
    ageGroup: AgeGroup.KID,
    hourCost: 2,
    price: 0,
    statChanges: { mood: 35, stress: -20 },
    skillChanges: { friendship: 1.5, trust: 1.3, social: 1.1 },
  },
  {
    id: 'kid_conspire_teacher',
    title: 'Сговориться против учителя',
    description: 'Все вместе мы его победим',
    category: 'social',
    ageGroup: AgeGroup.KID,
    hourCost: 1,
    price: 0,
    statChanges: { mood: 25, stress: 15 },
    skillChanges: { social: 1.0 },
  },
  {
    id: 'kid_try_cigarette',
    title: 'Попробовать сигарету у старшеклассника',
    description: 'Теперь ты взрослый',
    category: 'social',
    ageGroup: AgeGroup.TEEN,
    hourCost: 0.5,
    price: 0,
    statChanges: { mood: 15, stress: 25, health: -10 },
    skillChanges: { risk_tolerance: 1.1, social: 0.9 },
  },
  {
    id: 'kid_make_slingshot',
    title: 'Сделать самодельный рогатка',
    description: 'Руки растут из правильного места',
    category: 'hobby',
    ageGroup: AgeGroup.KID,
    hourCost: 2,
    price: 0,
    statChanges: { mood: 30, stress: -10 },
    skillChanges: { craft: 1.3, engineering: 0.8 },
  },
  {
    id: 'kid_join_club_quit',
    title: 'Записаться в кружок который потом бросишь',
    description: 'Попробовать и понять что это скучно',
    category: 'hobby',
    ageGroup: AgeGroup.KID,
    hourCost: 2,
    price: 50,
    statChanges: { mood: 10, stress: 5 },
    skillChanges: { curiosity: 0.7 },
  },
  {
    id: 'kid_learn_lie_convincingly',
    title: 'Научиться врать убедительно',
    description: 'Теперь тебе верят всегда',
    category: 'social',
    ageGroup: AgeGroup.KID,
    hourCost: 1,
    price: 0,
    statChanges: { mood: 15 },
    skillChanges: { lying: 1.5, charisma: 1.0 },
  },
  {
    id: 'kid_cry_bad_grade',
    title: 'Расплакаться из-за двойки',
    description: 'Всё кончено жизнь разрушена',
    category: 'basic',
    ageGroup: AgeGroup.KID,
    hourCost: 0.5,
    price: 0,
    statChanges: { mood: -30, stress: 40 },
    skillChanges: { responsibility: 0.9 },
  },
  {
    id: 'kid_gum_on_chair',
    title: 'Поставить жвачку на стул учителя',
    description: 'Класс будет смеяться целую неделю',
    category: 'fun',
    ageGroup: AgeGroup.KID,
    hourCost: 0.5,
    price: 0,
    statChanges: { mood: 25, stress: 20 },
    skillChanges: { creativity: 1.1, social: 0.8 },
  },

  // ==============================================
  // 13-15 лет (TEEN) - 14 действий
  // ==============================================
  {
    id: 'teen_first_love',
    title: 'Влюбиться первый раз',
    description: 'Теперь ты понимаешь о чём все песни',
    category: 'social',
    ageGroup: AgeGroup.TEEN,
    hourCost: 4,
    price: 0,
    statChanges: { mood: 50, stress: 30, energy: -10 },
    skillChanges: { empathy: 1.8 },
  },
  {
    id: 'teen_first_rejection',
    title: 'Получить первый отказ',
    description: 'Мир разрушен навсегда',
    category: 'social',
    ageGroup: AgeGroup.TEEN,
    hourCost: 2,
    price: 0,
    statChanges: { mood: -45, stress: 50, energy: -20 },
    skillChanges: { resilience: 1.7, self_esteem: 1.2 },
  },
  {
    id: 'teen_hide_phone',
    title: 'Начать прятаться от родителей в телефоне',
    description: 'Они ничего не поймут',
    category: 'social',
    ageGroup: AgeGroup.TEEN,
    hourCost: 3,
    price: 0,
    statChanges: { mood: 15, stress: 10 },
    skillChanges: { willpower: 1.2 },
  },
  {
    id: 'teen_download_torrents',
    title: 'Скачивать музыку с торрентов',
    description: 'Весь мир музыки бесплатно',
    category: 'hobby',
    ageGroup: AgeGroup.TEEN,
    hourCost: 2,
    price: 0,
    statChanges: { mood: 20, stress: -10 },
    skillChanges: { tech_literacy: 1.3 },
  },
  {
    id: 'teen_try_alcohol',
    title: 'Пробовать алкоголь на вечеринке',
    description: 'Все пьют и ты попробуешь',
    category: 'social',
    ageGroup: AgeGroup.TEEN,
    hourCost: 3,
    price: 0,
    statChanges: { mood: 25, stress: 20, health: -15 },
    skillChanges: { social: 1.4, risk_tolerance: 1.2 },
  },
  {
    id: 'teen_fight_lose',
    title: 'Подраться и проиграть',
    description: 'Тебя унизили перед всеми',
    category: 'social',
    ageGroup: AgeGroup.TEEN,
    hourCost: 0.5,
    price: 0,
    statChanges: { mood: -35, stress: 40, physical: -5 },
    skillChanges: { humility: 1.3, resilience: 1.5 },
  },
  {
    id: 'teen_fight_win',
    title: 'Подраться и выиграть',
    description: 'Теперь все тебя боятся',
    category: 'social',
    ageGroup: AgeGroup.TEEN,
    hourCost: 0.5,
    price: 0,
    statChanges: { mood: 35, stress: -15, physical: 5 },
    skillChanges: { confidence: 1.6, aggression: 1.4 },
  },
  {
    id: 'teen_skip_school_walk',
    title: 'Бросить школу и уйти гулять',
    description: 'Уроки подождут а жизнь сейчас',
    category: 'fun',
    ageGroup: AgeGroup.TEEN,
    hourCost: 4,
    price: 0,
    statChanges: { mood: 40, stress: -20, energy: -15 },
    skillChanges: { self_esteem: 1.1 },
  },
  {
    id: 'teen_start_sport_serious',
    title: 'Начать заниматься спортом серьёзно',
    description: 'Теперь это не игра это работа',
    category: 'health',
    ageGroup: AgeGroup.TEEN,
    hourCost: 3,
    price: 300,
    statChanges: { physical: 20, health: 12, energy: -40, stress: -15, mood: 20 },
    skillChanges: { discipline: 1.7, persistence: 1.5 },
  },
  {
    id: 'teen_drop_old_interests',
    title: 'Отказаться от всего что любил раньше',
    description: 'Теперь ты совершенно другой человек',
    category: 'selfdev',
    ageGroup: AgeGroup.TEEN,
    hourCost: 1,
    price: 0,
    statChanges: { mood: 10, stress: 15 },
    skillChanges: { self_esteem: 1.4 },
  },
  {
    id: 'teen_start_diary',
    title: 'Начать вести дневник',
    description: 'Никто не поймёт кроме бумаги',
    category: 'selfdev',
    ageGroup: AgeGroup.TEEN,
    hourCost: 1.5,
    price: 0,
    statChanges: { mood: 15, stress: -25 },
    skillChanges: { self_reflection: 1.6, writing: 1.2 },
  },
  {
    id: 'teen_feel_unwanted',
    title: 'Впервые почувствовать что ты никому не нужен',
    description: 'Всего один плохой день и мир рушится',
    category: 'basic',
    ageGroup: AgeGroup.TEEN,
    hourCost: 3,
    price: 0,
    statChanges: { mood: -40, stress: 45, energy: -25 },
    skillChanges: { self_esteem: 1.3 },
  },
  {
    id: 'teen_betray_friend',
    title: 'Предать лучшего друга',
    description: 'Ты сам не понял как так вышло',
    category: 'social',
    ageGroup: AgeGroup.TEEN,
    hourCost: 1,
    price: 0,
    statChanges: { mood: 10, stress: 50 },
    skillChanges: { willpower: 1.8 },
  },
  {
    id: 'teen_get_betrayed',
    title: 'Быть преданным лучшим другом',
    description: 'Ты думал это навсегда',
    category: 'social',
    ageGroup: AgeGroup.TEEN,
    hourCost: 2,
    price: 0,
    statChanges: { mood: -50, stress: 55, energy: -30 },
    skillChanges: { empathy: 1.7 },
  },

  // ==============================================
  // 16-18 лет (YOUNG) - 8 действий
  // ==============================================
  {
    id: 'young_skip_graduation',
    title: 'Пропустить выпускной',
    description: 'Ты не хочешь быть там',
    category: 'social',
    ageGroup: AgeGroup.YOUNG,
    hourCost: 4,
    price: 0,
    statChanges: { mood: -10, stress: -20 },
    skillChanges: { independence: 1.5 },
  },
  {
    id: 'young_decide_university',
    title: 'Поступать в институт или нет',
    description: 'Самое важное решение в жизни до этого момента',
    category: 'career',
    ageGroup: AgeGroup.YOUNG,
    hourCost: 4,
    price: 0,
    statChanges: { stress: 40, mood: -5 },
    skillChanges: { decision_making: 1.8, responsibility: 1.6 },
  },
  {
    id: 'young_move_out',
    title: 'Выехать из дома',
    description: 'Наконец то свобода',
    category: 'life',
    ageGroup: AgeGroup.YOUNG,
    hourCost: 4,
    price: 1500,
    statChanges: { mood: 35, stress: 45, energy: -30 },
    skillChanges: { independence: 2.0, responsibility: 1.9 },
  },
  {
    id: 'young_first_real_job',
    title: 'Найти первую настоящую работу',
    description: 'Теперь ты точно взрослый',
    category: 'career',
    ageGroup: AgeGroup.YOUNG,
    hourCost: 4,
    price: 0,
    statChanges: { mood: 25, stress: 30, energy: -35 },
    skillChanges: { work_ethic: 1.7, discipline: 1.5 },
    rewards: { money: 8000 },
  },
  {
    id: 'young_first_time',
    title: 'Потерять девственность',
    description: 'Оно было совсем не как в фильмах',
    category: 'social',
    ageGroup: AgeGroup.YOUNG,
    hourCost: 2,
    price: 0,
    statChanges: { mood: 30, stress: 25 },
    skillChanges: { empathy: 1.6 },
  },
  {
    id: 'young_first_breakup',
    title: 'Пережить первую расставание',
    description: 'Ты думаешь что никогда не выздоровеешь',
    category: 'social',
    ageGroup: AgeGroup.YOUNG,
    hourCost: 3,
    price: 0,
    statChanges: { mood: -55, stress: 50, energy: -40 },
    skillChanges: { willpower: 1.9 },
  },
  {
    id: 'young_meet_important_person',
    title: 'Встретить человека которого будешь помнить всю жизнь',
    description: 'Ты ещё не знаешь что это был самый важный день',
    category: 'social',
    ageGroup: AgeGroup.YOUNG,
    hourCost: 2,
    price: 0,
    statChanges: { mood: 40, stress: -15 },
    skillChanges: { empathy: 2.1 },
  },
  {
    id: 'young_decide_adults_idiots',
    title: 'Решить что все взрослые идиоты',
    description: 'Теперь ты точно знаешь лучше всех',
    category: 'selfdev',
    ageGroup: AgeGroup.YOUNG,
    hourCost: 1,
    price: 0,
    statChanges: { mood: 20, stress: -10 },
    skillChanges: { charisma: 1.3 },
  },
]
