import type { BalanceAction } from './types'
import { AgeGroup } from './types'

export const EDUCATION_ACTIONS: BalanceAction[] = [
  {
    id: 'edu_read_textbook',
    category: 'education',
    title: 'Чтение учебника или профессиональной литературы',
    hourCost: 2,
    price: 0,
    statChanges: { hunger: 2.8, energy: -4.2, stress: -5.5, mood: 7.5, health: 0.5, physical: -0.4 },
    skillChanges: { basicCreativity: 1.5 },
    actionType: 'education',
    effect: 'Голод +2.8, Энергия -4.2, Стресс -5.5, Настроение +7.5, Здоровье +0.5, Физическая форма -0.4, Креативность +1.5',
    mood: '📖 Глубокое чтение учебника — отличная тренировка ума',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'edu_online_course',
    category: 'education',
    title: 'Онлайн-курс (одно занятие)',
    hourCost: 3,
    price: 0,
    statChanges: { hunger: 4.2, energy: -5.8, stress: -6.5, mood: 9.5, health: -0.3, physical: -0.7 },
    skillChanges: { basicCreativity: 2.5 },
    actionType: 'education',
    effect: 'Голод +4.2, Энергия -5.8, Стресс -6.5, Настроение +9.5, Здоровье -0.3, Физическая форма -0.7, Креативность +2.5',
    mood: '💻 Онлайн-курс — удобный способ прокачать навыки',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'edu_practical_task',
    category: 'education',
    title: 'Выполнение практического задания',
    hourCost: 4,
    price: 0,
    statChanges: { hunger: 5.5, energy: -7.5, stress: -7, mood: 8.5, health: -0.4, physical: -0.8 },
    skillChanges: { professionalism: 2.5 },
    actionType: 'education',
    effect: 'Голод +5.5, Энергия -7.5, Стресс -7, Настроение +8.5, Здоровье -0.4, Физическая форма -0.8, Профессионализм +2.5',
    mood: '🛠️ Практика — лучший способ закрепить знания',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'edu_edu_video',
    category: 'education',
    title: 'Просмотр образовательного видео',
    hourCost: 1.5,
    price: 0,
    statChanges: { hunger: 2.1, energy: -3, stress: -4.5, mood: 6.5, health: 0.3, physical: -0.3 },
    skillChanges: { basicCreativity: 1.5 },
    actionType: 'education',
    effect: 'Голод +2.1, Энергия -3, Стресс -4.5, Настроение +6.5, Здоровье +0.3, Физическая форма -0.3, Креативность +1.5',
    mood: '🎥 Короткое образовательное видео — быстро и полезно',
    ageGroup: AgeGroup.TODDLER,
  },
  {
    id: 'edu_exam_prep',
    category: 'education',
    title: 'Подготовка к экзамену или тесту',
    hourCost: 5,
    price: 0,
    statChanges: { hunger: 6.8, energy: -9.5, stress: -8.5, mood: 7.5, health: -0.6, physical: -1.2 },
    skillChanges: { discipline: 3 },
    actionType: 'education',
    effect: 'Голод +6.8, Энергия -9.5, Стресс -8.5, Настроение +7.5, Здоровье -0.6, Физическая форма -1.2, Дисциплина +3',
    mood: '📝 Интенсивная подготовка к экзамену закаляет характер',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'edu_webinar',
    category: 'education',
    title: 'Посещение вебинара или онлайн-лекции',
    hourCost: 2.5,
    price: 1200,
    statChanges: { hunger: 3.5, energy: -4.8, stress: -5.5, mood: 8.5, health: -0.3, physical: -0.6 },
    skillChanges: { basicCreativity: 3, charisma: 1 },
    actionType: 'education',
    effect: 'Голод +3.5, Энергия -4.8, Стресс -5.5, Настроение +8.5, Здоровье -0.3, Физическая форма -0.6, Креативность +3, Харизма +1',
    mood: '📡 Вебинар — отличный способ узнать новое и завести полезные контакты',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'edu_foreign_lang',
    category: 'education',
    title: 'Изучение иностранного языка (одно занятие)',
    hourCost: 2,
    price: 800,
    statChanges: { hunger: 2.8, energy: -4, stress: -5, mood: 9, health: -0.2, physical: -0.4 },
    skillChanges: { communication: 3 },
    actionType: 'education',
    effect: 'Голод +2.8, Энергия -4, Стресс -5, Настроение +9, Здоровье -0.2, Физическая форма -0.4, Коммуникация +3',
    mood: '🗣️ Регулярные занятия языком открывают новые горизонты',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'edu_write_article',
    category: 'education',
    title: 'Написание статьи или экспертного поста',
    hourCost: 3,
    price: 0,
    statChanges: { hunger: 4.2, energy: -5.5, stress: -6, mood: 10.5, health: -0.3, physical: -0.6 },
    skillChanges: { basicCreativity: 2.5, marketing: 2 },
    actionType: 'education',
    effect: 'Голод +4.2, Энергия -5.5, Стресс -6, Настроение +10.5, Здоровье -0.3, Физическая форма -0.6, Креативность +2.5, Маркетинг +2',
    mood: '✍️ Когда пишешь статью — лучше всего понимаешь материал',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'edu_public_speaking',
    category: 'education',
    title: 'Практика публичных выступлений',
    hourCost: 2,
    price: 0,
    statChanges: { hunger: 2.8, energy: -4.2, stress: -7.5, mood: 11.5, health: -0.2, physical: -0.5 },
    skillChanges: { communication: 3.5, leadership: 2 },
    actionType: 'education',
    effect: 'Голод +2.8, Энергия -4.2, Стресс -7.5, Настроение +11.5, Здоровье -0.2, Физическая форма -0.5, Коммуникация +3.5, Лидерство +2',
    mood: '🗣️ Публичные выступления — один из самых быстрых способов роста',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'edu_financial_lit',
    category: 'education',
    title: 'Изучение финансовой литературы',
    hourCost: 2.5,
    price: 0,
    statChanges: { hunger: 3.5, energy: -4.8, stress: -5.5, mood: 8.5, health: 0.5, physical: -0.5 },
    skillChanges: { financialLiteracy: 4 },
    actionType: 'education',
    effect: 'Голод +3.5, Энергия -4.8, Стресс -5.5, Настроение +8.5, Здоровье +0.5, Физическая форма -0.5, Финансовая грамотность +4',
    mood: '💰 Финансовая литература — инвестиция в своё будущее',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'edu_programming',
    category: 'education',
    title: 'Занятие по программированию',
    hourCost: 4,
    price: 0,
    statChanges: { hunger: 5.5, energy: -8, stress: -7.5, mood: 9.5, health: -0.5, physical: -1 },
    skillChanges: { technicalLiteracy: 4 },
    actionType: 'education',
    effect: 'Голод +5.5, Энергия -8, Стресс -7.5, Настроение +9.5, Здоровье -0.5, Физическая форма -1, Техническая грамотность +4',
    mood: '💻 Программирование учит думать логично и структурировано',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'edu_cooking_masterclass',
    category: 'education',
    title: 'Мастер-класс по кулинарии',
    hourCost: 3,
    price: 2500,
    statChanges: { hunger: -13.5, energy: -5.5, stress: -7.5, mood: 15.5, health: 2.8, physical: -0.7 },
    skillChanges: { cooking: 4 },
    actionType: 'education',
    effect: 'Голод -13.5, Энергия -5.5, Стресс -7.5, Настроение +15.5, Здоровье +2.8, Физическая форма -0.7, Кулинарное мастерство +4',
    mood: '🍳 Мастер-класс по готовке — вкусно и полезно одновременно',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'edu_research',
    category: 'education',
    title: 'Самостоятельное исследование темы',
    hourCost: 4,
    price: 0,
    statChanges: { hunger: 5.2, energy: -7.5, stress: -6.5, mood: 10.5, health: -0.4, physical: -0.9 },
    skillChanges: { analyticalThinking: 3.5 },
    actionType: 'education',
    effect: 'Голод +5.2, Энергия -7.5, Стресс -6.5, Настроение +10.5, Здоровье -0.4, Физическая форма -0.9, Аналитическое мышление +3.5',
    mood: '🔍 Глубокое исследование темы даёт настоящее понимание',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'edu_memory_training',
    category: 'education',
    title: 'Тренировка памяти и внимания',
    hourCost: 1,
    price: 0,
    statChanges: { hunger: 1.5, energy: -2.5, stress: -5, mood: 7.5, health: 0.8, physical: -0.2 },
    skillChanges: { memory: 3, discipline: 1.5 },
    actionType: 'education',
    effect: 'Голод +1.5, Энергия -2.5, Стресс -5, Настроение +7.5, Здоровье +0.8, Физическая форма -0.2, Память +3, Дисциплина +1.5',
    mood: '🧠 Тренировка памяти — как спорт для мозга',
    ageGroup: AgeGroup.TODDLER,
  },
  {
    id: 'edu_psychology',
    category: 'education',
    title: 'Изучение психологии',
    hourCost: 2.5,
    price: 0,
    statChanges: { hunger: 3.5, energy: -4.5, stress: -8.5, mood: 11.5, health: 1.2, physical: -0.5 },
    skillChanges: { emotionalIntelligence: 4 },
    actionType: 'education',
    effect: 'Голод +3.5, Энергия -4.5, Стресс -8.5, Настроение +11.5, Здоровье +1.2, Физическая форма -0.5, Эмоциональный интеллект +4',
    mood: '🧠 Психология помогает лучше понимать себя и других',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'edu_mba',
    category: 'education',
    title: 'Занятие онлайн-курса MBA',
    hourCost: 5,
    price: 4500,
    statChanges: { hunger: 6.8, energy: -9.5, stress: -8, mood: 10.5, health: -0.6, physical: -1.2 },
    skillChanges: { leadership: 3.5, strategicPlanning: 3 },
    actionType: 'education',
    effect: 'Голод +6.8, Энергия -9.5, Стресс -8, Настроение +10.5, Здоровье -0.6, Физическая форма -1.2, Лидерство +3.5, Стратегическое планирование +3',
    mood: '📊 MBA — серьёзный шаг в развитии управленческих навыков',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'edu_negotiation_practice',
    category: 'education',
    title: 'Практика навыков переговоров',
    hourCost: 2,
    price: 0,
    statChanges: { hunger: 2.8, energy: -4, stress: -6.5, mood: 9.5, health: -0.2, physical: -0.5 },
    skillChanges: { negotiations: 4 },
    actionType: 'education',
    effect: 'Голод +2.8, Энергия -4, Стресс -6.5, Настроение +9.5, Здоровье -0.2, Физическая форма -0.5, Переговоры +4',
    mood: '🤝 Умение договариваться — один из самых ценных навыков',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'edu_design',
    category: 'education',
    title: 'Изучение дизайна (графический / интерьер)',
    hourCost: 3,
    price: 0,
    statChanges: { hunger: 4.2, energy: -5.8, stress: -6.5, mood: 10.5, health: -0.3, physical: -0.7 },
    skillChanges: { basicCreativity: 3.5, interiorDesign: 2.5 },
    actionType: 'education',
    effect: 'Голод +4.2, Энергия -5.8, Стресс -6.5, Настроение +10.5, Здоровье -0.3, Физическая форма -0.7, Креативность +3.5, Дизайн интерьера +2.5',
    mood: '🎨 Дизайн развивает вкус и креативное мышление',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'edu_fitness_theory',
    category: 'education',
    title: 'Теория тренировок и здорового образа жизни',
    hourCost: 2,
    price: 0,
    statChanges: { hunger: 2.8, energy: -3.5, stress: -5, mood: 8.5, health: 2.5, physical: 3.5 },
    skillChanges: { physicalFitness: 2.5, healthyLifestyle: 3 },
    actionType: 'education',
    effect: 'Голод +2.8, Энергия -3.5, Стресс -5, Настроение +8.5, Здоровье +2.5, Физическая форма +3.5, Физическая подготовка +2.5, Здоровый образ жизни +3',
    mood: '🏋️ Знания о тренировках помогают заниматься эффективнее',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'edu_invest_course',
    category: 'education',
    title: 'Курс по инвестированию',
    hourCost: 3,
    price: 1800,
    statChanges: { hunger: 4.2, energy: -5.5, stress: -6, mood: 9.5, health: -0.3, physical: -0.6 },
    skillChanges: { financialLiteracy: 5 },
    actionType: 'education',
    effect: 'Голод +4.2, Энергия -5.5, Стресс -6, Настроение +9.5, Здоровье -0.3, Физическая форма -0.6, Финансовая грамотность +5',
    mood: '📈 Инвестиции — это навык, который работает на твоё будущее',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'edu_marketing',
    category: 'education',
    title: 'Изучение маркетинга',
    hourCost: 4,
    price: 0,
    statChanges: { hunger: 5.5, energy: -7.5, stress: -7, mood: 10.5, health: -0.4, physical: -0.9 },
    skillChanges: { marketing: 4 },
    actionType: 'education',
    effect: 'Голод +5.5, Энергия -7.5, Стресс -7, Настроение +10.5, Здоровье -0.4, Физическая форма -0.9, Маркетинг +4',
    mood: '📣 Маркетинг учит понимать людей и их желания',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'edu_photo_practice',
    category: 'education',
    title: 'Практика фотографии',
    hourCost: 3,
    price: 300,
    statChanges: { hunger: 4.2, energy: -5.5, stress: -6.5, mood: 12.5, health: -0.3, physical: -0.7 },
    skillChanges: { photography: 4, basicCreativity: 2.5 },
    actionType: 'education',
    effect: 'Голод +4.2, Энергия -5.5, Стресс -6.5, Настроение +12.5, Здоровье -0.3, Физическая форма -0.7, Фотография +4, Креативность +2.5',
    mood: '📸 Практика фотографии развивает взгляд и креативность',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'edu_diary',
    category: 'education',
    title: 'Ведение дневника рефлексии',
    hourCost: 1,
    price: 0,
    statChanges: { hunger: 1.4, energy: -2.2, stress: -9.5, mood: 10.5, health: 0.8, physical: -0.2 },
    skillChanges: { emotionalIntelligence: 3, wisdom: 2 },
    actionType: 'education',
    effect: 'Голод +1.4, Энергия -2.2, Стресс -9.5, Настроение +10.5, Здоровье +0.8, Физическая форма -0.2, Эмоциональный интеллект +3, Мудрость +2',
    mood: '📓 Дневник помогает лучше понимать себя и свои эмоции',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'edu_time_management',
    category: 'education',
    title: 'Изучение тайм-менеджмента',
    hourCost: 2,
    price: 0,
    statChanges: { hunger: 2.8, energy: -4, stress: -7.5, mood: 9.5, health: 0.5, physical: -0.4 },
    skillChanges: { timeManagement: 4 },
    actionType: 'education',
    effect: 'Голод +2.8, Энергия -4, Стресс -7.5, Настроение +9.5, Здоровье +0.5, Физическая форма -0.4, Тайм-менеджмент +4',
    mood: '⏰ Хороший тайм-менеджмент — ключ к свободе и продуктивности',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'edu_leadership_course',
    category: 'education',
    title: 'Курс по лидерству',
    hourCost: 3.5,
    price: 2200,
    statChanges: { hunger: 4.8, energy: -6.5, stress: -7, mood: 10.5, health: -0.4, physical: -0.8 },
    skillChanges: { leadership: 5 },
    actionType: 'education',
    effect: 'Голод +4.8, Энергия -6.5, Стресс -7, Настроение +10.5, Здоровье -0.4, Физическая форма -0.8, Лидерство +5',
    mood: '👑 Лидерство — навык, который можно и нужно развивать',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'edu_mindfulness',
    category: 'education',
    title: 'Практика осознанности и медитации',
    hourCost: 1.5,
    price: 0,
    statChanges: { hunger: 2.1, energy: -2.8, stress: -14.5, mood: 12.5, health: 1.8, physical: -0.3 },
    skillChanges: { emotionalIntelligence: 3.5, stressResistance: 3 },
    actionType: 'education',
    effect: 'Голод +2.1, Энергия -2.8, Стресс -14.5, Настроение +12.5, Здоровье +1.8, Физическая форма -0.3, Эмоциональный интеллект +3.5, Стрессоустойчивость +3',
    mood: '🧘 Осознанность помогает жить здесь и сейчас',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'edu_gardening',
    category: 'education',
    title: 'Изучение садоводства и ухода за растениями',
    hourCost: 2,
    price: 600,
    statChanges: { hunger: 3.2, energy: -4, stress: -7.5, mood: 10.5, health: 2.5, physical: 3.5 },
    housingComfortDelta: 8,
    skillChanges: { gardening: 4 },
    actionType: 'education',
    effect: 'Голод +3.2, Энергия -4, Стресс -7.5, Настроение +10.5, Здоровье +2.5, Физическая форма +3.5, Садоводство +4, Комфорт жилья +8',
    mood: '🌱 Садоводство учит терпению и дарит ощущение жизни',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'edu_acting',
    category: 'education',
    title: 'Курс актёрского мастерства',
    hourCost: 4,
    price: 3500,
    statChanges: { hunger: 5.2, energy: -7, stress: -8.5, mood: 14.5, health: -0.5, physical: -1 },
    skillChanges: { acting: 4, charisma: 3 },
    actionType: 'education',
    effect: 'Голод +5.2, Энергия -7, Стресс -8.5, Настроение +14.5, Здоровье -0.5, Физическая форма -1, Актёрское мастерство +4, Харизма +3',
    mood: '🎭 Актёрское мастерство раскрывает эмоции и уверенность',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'edu_podcasts',
    category: 'education',
    title: 'Обучение через подкасты',
    hourCost: 2,
    price: 0,
    statChanges: { hunger: 2.8, energy: -3.5, stress: -5.5, mood: 8.5, health: 0.4, physical: -0.4 },
    skillChanges: { basicCreativity: 2 },
    actionType: 'education',
    effect: 'Голод +2.8, Энергия -3.5, Стресс -5.5, Настроение +8.5, Здоровье +0.4, Физическая форма -0.4, Креативность +2',
    mood: '🎙️ Подкасты — удобный формат самообразования',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'edu_resume',
    category: 'education',
    title: 'Подготовка резюме и портфолио',
    hourCost: 3,
    price: 0,
    statChanges: { hunger: 4.2, energy: -5.5, stress: -6.5, mood: 9.5, health: -0.3, physical: -0.7 },
    skillChanges: { professionalism: 3, negotiations: 2 },
    actionType: 'education',
    effect: 'Голод +4.2, Энергия -5.5, Стресс -6.5, Настроение +9.5, Здоровье -0.3, Физическая форма -0.7, Профессионализм +3, Переговоры +2',
    mood: '📄 Хорошее резюме — важный инструмент в карьере',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'edu_library',
    category: 'education',
    title: 'Посещение библиотеки',
    hourCost: 3,
    price: 0,
    statChanges: { hunger: 4.2, energy: -5, stress: -6, mood: 10.5, health: 0.8, physical: -0.6 },
    skillChanges: { curiosity: 2.5 },
    actionType: 'education',
    effect: 'Голод +4.2, Энергия -5, Стресс -6, Настроение +10.5, Здоровье +0.8, Физическая форма -0.6, Любознательность +2.5',
    mood: '📚 Библиотека — храм знаний и тишины',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'edu_hackathon',
    category: 'education',
    title: 'Участие в хакатоне или конкурсе',
    hourCost: 8,
    price: 0,
    statChanges: { hunger: 10.5, energy: -14.5, stress: -9.5, mood: 16.5, health: -1.2, physical: -2.5 },
    skillChanges: { specialization: 3.5, professionalism: 3 },
    actionType: 'education',
    effect: 'Голод +10.5, Энергия -14.5, Стресс -9.5, Настроение +16.5, Здоровье -1.2, Физическая форма -2.5, Специализация +3.5, Профессионализм +3',
    mood: '🚀 Хакатон — интенсивный опыт роста и командной работы',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'edu_history',
    category: 'education',
    title: 'Изучение истории',
    hourCost: 2,
    price: 0,
    statChanges: { hunger: 2.8, energy: -3.8, stress: -5.5, mood: 9.5, health: 1.2, physical: -0.4 },
    skillChanges: { wisdom: 2, curiosity: 2 },
    actionType: 'education',
    effect: 'Голод +2.8, Энергия -3.8, Стресс -5.5, Настроение +9.5, Здоровье +1.2, Физическая форма -0.4, Мудрость +2, Любознательность +2',
    mood: '📜 История помогает лучше понимать настоящее',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'edu_philosophy',
    category: 'education',
    title: 'Изучение философии',
    hourCost: 2.5,
    price: 0,
    statChanges: { hunger: 3.5, energy: -4.8, stress: -7.5, mood: 11.5, health: 1.5, physical: -0.5 },
    skillChanges: { wisdom: 3, emotionalIntelligence: 2 },
    actionType: 'education',
    effect: 'Голод +3.5, Энергия -4.8, Стресс -7.5, Настроение +11.5, Здоровье +1.5, Физическая форма -0.5, Мудрость +3, Эмоциональный интеллект +2',
    mood: '🤔 Философия учит думать глубоко и жить осмысленно',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'edu_speed_reading',
    category: 'education',
    title: 'Тренировка скорочтения',
    hourCost: 1.5,
    price: 0,
    statChanges: { hunger: 2.1, energy: -3, stress: -4.5, mood: 7.5, health: 0.5, physical: -0.3 },
    skillChanges: { memory: 3, curiosity: 1.5 },
    actionType: 'education',
    effect: 'Голод +2.1, Энергия -3, Стресс -4.5, Настроение +7.5, Здоровье +0.5, Физическая форма -0.3, Память +3, Любознательность +1.5',
    mood: '📖 Скорочтение позволяет поглощать больше знаний за меньшее время',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'edu_law',
    category: 'education',
    title: 'Изучение основ права',
    hourCost: 3,
    price: 0,
    statChanges: { hunger: 4.2, energy: -5.5, stress: -6.5, mood: 8.5, health: -0.3, physical: -0.7 },
    skillChanges: { legalLiteracy: 3 },
    actionType: 'education',
    effect: 'Голод +4.2, Энергия -5.5, Стресс -6.5, Настроение +8.5, Здоровье -0.3, Физическая форма -0.7, Юридическая грамотность +3',
    mood: '⚖️ Знание основ права защищает и даёт уверенность',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'edu_online_test',
    category: 'education',
    title: 'Пройти онлайн-тестирование знаний',
    hourCost: 1,
    price: 500,
    statChanges: { hunger: 1.5, energy: -2.5, stress: -3.5, mood: 6.5, health: 0.5, physical: -0.2 },
    skillChanges: { basicCreativity: 1.5 },
    actionType: 'education',
    effect: 'Голод +1.5, Энергия -2.5, Стресс -3.5, Настроение +6.5, Здоровье +0.5, Физическая форма -0.2, Креативность +1.5',
    mood: '📝 Тестирование помогает объективно оценить свои знания',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'edu_ecology',
    category: 'education',
    title: 'Изучение экологии и устойчивого развития',
    hourCost: 2,
    price: 0,
    statChanges: { hunger: 2.8, energy: -3.8, stress: -5.5, mood: 9.5, health: 2.2, physical: 1.5 },
    skillChanges: { medicalKnowledge: 1.5, healthyLifestyle: 2 },
    actionType: 'education',
    effect: 'Голод +2.8, Энергия -3.8, Стресс -5.5, Настроение +9.5, Здоровье +2.2, Физическая форма +1.5, Медицинские знания +1.5, Здоровый образ жизни +2',
    mood: '🌍 Экология учит заботиться о планете и своём здоровье',
    ageGroup: AgeGroup.CHILD,
  },
]
