import type { BalanceAction } from './types'
import { AgeGroup } from './types'

export const FINANCE_ACTIONS: BalanceAction[] = [
  {
    id: 'fin_deposit',
    category: 'finance',
    title: 'Банковский вклад',
    hourCost: 2,
    price: 50000,
    investmentReturn: 4200,
    investmentDurationDays: 28,
    statChanges: { hunger: 2.2, energy: -3.5, stress: -8.5, mood: 6.5, health: 0.4 },
    skillChanges: { financialLiteracy: 2 },
    actionType: 'recovery',
    effect: 'Голод +2.2, Энергия -3.5, Стресс -8.5, Настроение +6.5, Здоровье +0.4, Финансовая грамотность +2',
    mood: '🏦 Открой вклад — деньги начинают работать на тебя даже пока ты спишь',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'fin_budget',
    category: 'finance',
    title: 'Оптимизация бюджета',
    hourCost: 1.5,
    price: 0,
    statChanges: { hunger: 1.8, energy: -3, stress: -12.5, mood: 8.5, health: 0.6 },
    skillChanges: { financialLiteracy: 2.5, organization: 1.5 },
    actionType: 'recovery',
    effect: 'Голод +1.8, Энергия -3, Стресс -12.5, Настроение +8.5, Здоровье +0.6, Финансовая грамотность +2.5, Организация +1.5',
    mood: '📊 Пересмотри траты и перераспредели статьи. Когда понимаешь, куда уходят деньги — появляется контроль',
    ageGroup: AgeGroup.YOUNG,
    monthlyExpenseDelta: {
      leisure: -1200,
      education: 300,
      food: -400,
    },
  },
  {
    id: 'fin_stocks',
    category: 'finance',
    title: 'Акции и ETF',
    hourCost: 2,
    price: 15000,
    statChanges: { hunger: 2.8, energy: -4, stress: -4.5, mood: 6.5, health: -0.3, physical: -0.5 },
    skillChanges: { analyticalThinking: 2.5, financialLiteracy: 2 },
    actionType: 'recovery',
    effect: 'Голод +2.8, Энергия -4, Стресс -4.5, Настроение +6.5, Здоровье -0.3, Физическая форма -0.5, Аналитическое мышление +2.5, Финансовая грамотность +2',
    mood: '📈 Купи акции или паи биржевого фонда. Риск выше, но и возможность роста больше',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'fin_iis',
    category: 'finance',
    title: 'Счёт ИИС',
    hourCost: 2.5,
    price: 50000,
    statChanges: { hunger: 3.2, energy: -4.2, stress: -8.5, mood: 7.5, health: 0.4, physical: -0.5 },
    skillChanges: { financialLiteracy: 4 },
    actionType: 'recovery',
    effect: 'Голод +3.2, Энергия -4.2, Стресс -8.5, Настроение +7.5, Здоровье +0.4, Физическая форма -0.5, Финансовая грамотность +4',
    mood: '📋 Открой индивидуальный инвестиционный счёт — один из самых выгодных способов инвестировать в России',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'fin_pay_debt',
    category: 'finance',
    title: 'Погасить долг',
    hourCost: 1,
    price: 8000,
    statChanges: { hunger: 1.5, energy: -2.5, stress: -18, mood: 14.5, health: 1.2 },
    skillChanges: { financialLiteracy: 1 },
    actionType: 'recovery',
    effect: 'Голод +1.5, Энергия -2.5, Стресс -18, Настроение +14.5, Здоровье +1.2, Финансовая грамотность +1',
    mood: '🧾 Внеси платёж по небольшому долгу. Когда долг уменьшается — на душе становится намного легче',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'fin_safety_fund',
    category: 'finance',
    title: 'Подушка безопасности',
    hourCost: 1,
    price: 10000,
    statChanges: { hunger: 1.6, energy: -2.2, stress: -13.5, mood: 8.5, health: 0.5, physical: -0.3 },
    actionType: 'recovery',
    effect: 'Голод +1.6, Энергия -2.2, Стресс -13.5, Настроение +8.5, Здоровье +0.5, Физическая форма -0.3',
    mood: '🛡️ Создай или пополни резерв на непредвиденные расходы — спокойный сон по ночам',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'fin_business_invest',
    category: 'finance',
    title: 'Бизнес-инвестиции',
    hourCost: 4,
    price: 100000,
    statChanges: { hunger: 5.5, energy: -8.5, stress: -6.5, mood: 9.5, health: -0.6, physical: -1.2 },
    skillChanges: { financialLiteracy: 3, analyticalThinking: 2 },
    actionType: 'recovery',
    effect: 'Голод +5.5, Энергия -8.5, Стресс -6.5, Настроение +9.5, Здоровье -0.6, Физическая форма -1.2, Финансовая грамотность +3, Аналитическое мышление +2',
    mood: '🏢 Вложи средства в свой или чужой бизнес — вера в идею и готовность к риску',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'fin_advisor',
    category: 'finance',
    title: 'Финансовый советник',
    hourCost: 2,
    price: 5000,
    statChanges: { hunger: 2.8, energy: -4, stress: -9.5, mood: 8.5, health: 0.6, physical: -0.4 },
    skillChanges: { financialLiteracy: 5 },
    actionType: 'recovery',
    effect: 'Голод +2.8, Энергия -4, Стресс -9.5, Настроение +8.5, Здоровье +0.6, Физическая форма -0.4, Финансовая грамотность +5',
    mood: '👨‍💼 Встреться с профессионалом — поможет избежать дорогих ошибок',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'fin_crypto',
    category: 'finance',
    title: 'Крипта и золото',
    hourCost: 1.5,
    price: 10000,
    statChanges: { hunger: 2.2, energy: -3.5, stress: -2.5, mood: 7.5, health: -0.8, physical: -0.6 },
    skillChanges: { analyticalThinking: 2, financialLiteracy: 2 },
    actionType: 'recovery',
    effect: 'Голод +2.2, Энергия -3.5, Стресс -2.5, Настроение +7.5, Здоровье -0.8, Физическая форма -0.6, Аналитическое мышление +2, Финансовая грамотность +2',
    mood: '₿ Купи криптовалюту или золото — высокорисковые, но потенциально доходные инструменты',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'fin_auto_savings',
    category: 'finance',
    title: 'Автонакопления',
    hourCost: 1,
    price: 0,
    statChanges: { hunger: 1.2, energy: -2, stress: -9.5, mood: 7 },
    skillChanges: { discipline: 2, financialLiteracy: 2 },
    actionType: 'recovery',
    effect: 'Голод +1.2, Энергия -2, Стресс -9.5, Настроение +7, Дисциплина +2, Финансовая грамотность +2',
    mood: '🔄 Настрой автоперевод части дохода на отдельный счёт — лучший друг дисциплины в финансах',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'fin_expense_analysis',
    category: 'finance',
    title: 'Анализ расходов',
    hourCost: 2,
    price: 0,
    statChanges: { hunger: 2.8, energy: -4, stress: -10.5, mood: 9.5, health: 0.5, physical: -0.4 },
    skillChanges: { financialLiteracy: 4, organization: 3 },
    actionType: 'recovery',
    effect: 'Голод +2.8, Энергия -4, Стресс -10.5, Настроение +9.5, Здоровье +0.5, Физическая форма -0.4, Финансовая грамотность +4, Организация +3',
    mood: '📉 Разбери траты за последний месяц. Когда видишь реальную картину расходов — начинаешь лучше управлять деньгами',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'fin_insurance',
    category: 'finance',
    title: 'Страхование',
    hourCost: 2,
    price: 12000,
    statChanges: { hunger: 2.5, energy: -3.5, stress: -12.5, mood: 7.5, health: 3.5, physical: -0.4 },
    actionType: 'recovery',
    effect: 'Голод +2.5, Энергия -3.5, Стресс -12.5, Настроение +7.5, Здоровье +3.5, Физическая форма -0.4',
    mood: '🛡️ Оформи страхование жизни или здоровья — защита себя и близких от непредвиденных ситуаций',
    subscription: { monthlyCost: 1000 },
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'fin_edu_invest',
    category: 'finance',
    title: 'Инвестиции в себя',
    hourCost: 1,
    price: 15000,
    statChanges: { hunger: 1.8, energy: -2.8, stress: -5.5, mood: 10.5, health: 1.2, physical: -0.3 },
    skillChanges: { financialLiteracy: 2 },
    actionType: 'recovery',
    effect: 'Голод +1.8, Энергия -2.8, Стресс -5.5, Настроение +10.5, Здоровье +1.2, Физическая форма -0.3, Финансовая грамотность +2',
    mood: '📚 Вложи в курсы и навыки — лучшая долгосрочная инвестиция',
    ageGroup: AgeGroup.ADULT,
  },
{
    id: 'fin_rent_out',
    category: 'finance',
    title: 'Аренда жилья',
    hourCost: 3,
    price: 0,
    statChanges: { hunger: 4.5, energy: -6, stress: -8.5, mood: 8.5, health: -0.4, physical: -0.8 },
    actionType: 'recovery',
    effect: 'Голод +4.5, Энергия -6, Стресс -8.5, Настроение +8.5, Здоровье -0.4, Физическая форма -0.8',
    mood: '🏠 Сдай свою недвижимость — пассивный доход без ежедневной работы',
    ageGroup: AgeGroup.ADULT,
    requirements: { housingLevel: 2 },
  },
  {
    id: 'fin_savings_account',
    category: 'finance',
    title: 'Накопительный счёт',
    hourCost: 1,
    price: 5000,
    statChanges: { hunger: 1.5, energy: -2.2, stress: -7.5, mood: 6.5, health: 0.4, physical: -0.3 },
    skillChanges: { financialLiteracy: 2 },
    actionType: 'recovery',
    effect: 'Голод +1.5, Энергия -2.2, Стресс -7.5, Настроение +6.5, Здоровье +0.4, Физическая форма -0.3, Финансовая грамотность +2',
    mood: '💳 Открой счёт с процентом на остаток — простой и надёжный инструмент',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'fin_pay_mortgage',
    category: 'finance',
    title: 'Досрочная ипотека',
    hourCost: 2,
    price: 50000,
    statChanges: { hunger: 3.2, energy: -4.5, stress: -15.5, mood: 12.5, health: 0.6, physical: -0.5 },
    actionType: 'recovery',
    effect: 'Голод +3.2, Энергия -4.5, Стресс -15.5, Настроение +12.5, Здоровье +0.6, Физическая форма -0.5',
    mood: '🏡 Внеси частичное досрочное погашение — груз на плечах становится легче',
    ageGroup: AgeGroup.ADULT,
    requirements: { hasMortgage: true },
  },
  {
    id: 'fin_buy_realty',
    category: 'finance',
    title: 'Недвижимость',
    hourCost: 6,
    price: 500000,
    statChanges: { hunger: 8.5, energy: -12.5, stress: -10.5, mood: 11.5, health: -0.8, physical: -1.5 },
    housingComfortDelta: 30,
    actionType: 'recovery',
    effect: 'Голод +8.5, Энергия -12.5, Стресс -10.5, Настроение +11.5, Здоровье -0.8, Физическая форма -1.5, Комфорт жилья +30',
    mood: '🏠 Купи квартиру или дом — один из самых серьёзных шагов в жизни',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'fin_pif',
    category: 'finance',
    title: 'Паевой фонд',
    hourCost: 2,
    price: 30000,
    statChanges: { hunger: 2.8, energy: -4, stress: -5.5, mood: 7.5, health: -0.3, physical: -0.5 },
    skillChanges: { financialLiteracy: 3, analyticalThinking: 2 },
    actionType: 'recovery',
    effect: 'Голод +2.8, Энергия -4, Стресс -5.5, Настроение +7.5, Здоровье -0.3, Физическая форма -0.5, Финансовая грамотность +3, Аналитическое мышление +2',
    mood: '📊 Инвестируй в ПИФ — удобный способ без глубоких знаний рынка',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'fin_bonds',
    category: 'finance',
    title: 'Облигации ОФЗ',
    hourCost: 1.5,
    price: 20000,
    statChanges: { hunger: 2.2, energy: -3, stress: -6.5, mood: 7, health: 0.3, physical: -0.3 },
    skillChanges: { financialLiteracy: 2, analyticalThinking: 1.5 },
    actionType: 'recovery',
    effect: 'Голод +2.2, Энергия -3, Стресс -6.5, Настроение +7, Здоровье +0.3, Физическая форма -0.3, Финансовая грамотность +2, Аналитическое мышление +1.5',
    mood: '📜 Купи государственные облигации — надёжный доход с предсказуемой ставкой',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'fin_refinance',
    category: 'finance',
    title: 'Рефинансирование',
    hourCost: 3,
    price: 0,
    statChanges: { hunger: 3.5, energy: -5, stress: -8, mood: 6, health: 0.5, physical: -0.4 },
    skillChanges: { financialLiteracy: 3, organization: 2 },
    actionType: 'recovery',
    effect: 'Голод +3.5, Энергия -5, Стресс -8, Настроение +6, Здоровье +0.5, Физическая форма -0.4, Финансовая грамотность +3, Организация +2',
    mood: '🔄 Переключи кредит на более выгодные условия — снизь ставку и переплату',
    ageGroup: AgeGroup.ADULT,
    requirements: { hasDebt: true },
  },
  {
    id: 'fin_tax_deduction',
    category: 'finance',
    title: 'Налоговый вычет',
    hourCost: 2,
    price: 0,
    statChanges: { hunger: 2.5, energy: -3.5, stress: -7, mood: 8, health: 0.4, physical: -0.3 },
    skillChanges: { financialLiteracy: 2, organization: 2 },
    actionType: 'recovery',
    effect: 'Голод +2.5, Энергия -3.5, Стресс -7, Настроение +8, Здоровье +0.4, Физическая форма -0.3, Финансовая грамотность +2, Организация +2',
    mood: '💰 Оформи возврат части уплаченного налога за жильё, лечение или обучение',
    ageGroup: AgeGroup.ADULT,
  },
]