import type { BalanceAction } from './types'

export const FINANCE_ACTIONS: BalanceAction[] = [
  {
    id: 'fin_reserve',
    category: 'finance',
    title: 'Отложить деньги в резервный фонд',
    hourCost: 1,
    price: 0,
    reserveDelta: 0, // сумма будет передаваться динамически
    statChanges: { hunger: 1.5, energy: -2.2, stress: -9.5, mood: 6.5, health: 0.4, physical: -0.3 },
    actionType: 'recovery',
    effect: 'Голод +1.5, Энергия -2.2, Стресс -9.5, Настроение +6.5, Здоровье +0.4, Физическая форма -0.3, Резерв + выбранная сумма',
    mood: '💰 Откладывать на «чёрный день» — это спокойствие и уверенность',
  },
  {
    id: 'fin_deposit',
    category: 'finance',
    title: 'Открыть банковский депозит',
    hourCost: 2,
    price: 30000,
    statChanges: { hunger: 2.8, energy: -3.5, stress: -7.5, mood: 7.5, health: 0.5, physical: -0.4 },
    skillChanges: { financialLiteracy: 2.5 },
    actionType: 'recovery',
    effect: 'Голод +2.8, Энергия -3.5, Стресс -7.5, Настроение +7.5, Здоровье +0.5, Физическая форма -0.4, Финансовая грамотность +2.5',
    mood: '🏦 Деньги начинают работать на тебя даже пока ты спишь',
  },
  {
    id: 'fin_budget',
    category: 'finance',
    title: 'Пересмотреть и оптимизировать личный бюджет',
    hourCost: 1.5,
    price: 0,
    statChanges: { hunger: 2.2, energy: -3, stress: -11.5, mood: 8.5, health: 0.6, physical: -0.3 },
    skillChanges: { financialLiteracy: 3, organization: 2 },
    actionType: 'recovery',
    effect: 'Голод +2.2, Энергия -3, Стресс -11.5, Настроение +8.5, Здоровье +0.6, Физическая форма -0.3, Финансовая грамотность +3, Организация +2',
    mood: '📊 Когда понимаешь, куда уходят деньги — появляется контроль',
  },
  {
    id: 'fin_stocks',
    category: 'finance',
    title: 'Купить акции или паи ETF',
    hourCost: 2,
    price: 15000,
    statChanges: { hunger: 2.8, energy: -4, stress: -4.5, mood: 6.5, health: -0.3, physical: -0.5 },
    skillChanges: { analyticalThinking: 2.5, financialLiteracy: 2 },
    actionType: 'recovery',
    effect: 'Голод +2.8, Энергия -4, Стресс -4.5, Настроение +6.5, Здоровье -0.3, Физическая форма -0.5, Аналитическое мышление +2.5, Финансовая грамотность +2',
    mood: '📈 Инвестиции в акции — это риск, но и возможность роста',
  },
  {
    id: 'fin_iis',
    category: 'finance',
    title: 'Открыть индивидуальный инвестиционный счёт (ИИС)',
    hourCost: 2.5,
    price: 50000,
    statChanges: { hunger: 3.2, energy: -4.2, stress: -8.5, mood: 7.5, health: 0.4, physical: -0.5 },
    skillChanges: { financialLiteracy: 4 },
    actionType: 'recovery',
    effect: 'Голод +3.2, Энергия -4.2, Стресс -8.5, Настроение +7.5, Здоровье +0.4, Физическая форма -0.5, Финансовая грамотность +4',
    mood: '📋 ИИС — один из самых выгодных способов инвестировать в России',
  },
  {
    id: 'fin_pay_debt',
    category: 'finance',
    title: 'Погасить небольшой долг или кредит',
    hourCost: 1,
    price: 0,
    statChanges: { hunger: 1.8, energy: -2.5, stress: -16.5, mood: 13.5, health: 0.8, physical: -0.3 },
    actionType: 'recovery',
    effect: 'Голод +1.8, Энергия -2.5, Стресс -16.5, Настроение +13.5, Здоровье +0.8, Физическая форма -0.3',
    mood: '🧾 Когда долг уменьшается — на душе становится намного легче',
  },
  {
    id: 'fin_take_credit',
    category: 'finance',
    title: 'Взять кредит на крупную покупку',
    hourCost: 3,
    price: 0,
    statChanges: { hunger: 4.2, energy: -5.5, stress: 8.5, mood: -4.5, health: -0.8, physical: -0.9 },
    actionType: 'recovery',
    effect: 'Голод +4.2, Энергия -5.5, Стресс +8.5, Настроение -4.5, Здоровье -0.8, Физическая форма -0.9',
    mood: '📋 Кредит даёт деньги сейчас, но добавляет ответственности и стресса',
  },
  {
    id: 'fin_safety_fund',
    category: 'finance',
    title: 'Создать или пополнить финансовую подушку безопасности',
    hourCost: 1,
    price: 10000,
    statChanges: { hunger: 1.6, energy: -2.2, stress: -13.5, mood: 8.5, health: 0.5, physical: -0.3 },
    actionType: 'recovery',
    effect: 'Голод +1.6, Энергия -2.2, Стресс -13.5, Настроение +8.5, Здоровье +0.5, Физическая форма -0.3',
    mood: '🛡️ Финансовая подушка — это спокойный сон по ночам',
  },
  {
    id: 'fin_business_invest',
    category: 'finance',
    title: 'Инвестировать в свой или чужой бизнес',
    hourCost: 4,
    price: 100000,
    statChanges: { hunger: 5.5, energy: -8.5, stress: -6.5, mood: 9.5, health: -0.6, physical: -1.2 },
    skillChanges: { financialLiteracy: 3, analyticalThinking: 2 },
    actionType: 'recovery',
    effect: 'Голод +5.5, Энергия -8.5, Стресс -6.5, Настроение +9.5, Здоровье -0.6, Физическая форма -1.2, Финансовая грамотность +3, Аналитическое мышление +2',
    mood: '🏢 Вложение в бизнес — это вера в идею и готовность к риску',
  },
  {
    id: 'fin_advisor',
    category: 'finance',
    title: 'Консультация с финансовым советником',
    hourCost: 2,
    price: 5000,
    statChanges: { hunger: 2.8, energy: -4, stress: -9.5, mood: 8.5, health: 0.6, physical: -0.4 },
    skillChanges: { financialLiteracy: 5 },
    actionType: 'recovery',
    effect: 'Голод +2.8, Энергия -4, Стресс -9.5, Настроение +8.5, Здоровье +0.6, Физическая форма -0.4, Финансовая грамотность +5',
    mood: '👨‍💼 Профессиональный советник помогает избежать дорогих ошибок',
  },
  {
    id: 'fin_crypto',
    category: 'finance',
    title: 'Покупка криптовалюты или золота',
    hourCost: 1.5,
    price: 0,
    statChanges: { hunger: 2.2, energy: -3.5, stress: -2.5, mood: 7.5, health: -0.8, physical: -0.6 },
    skillChanges: { analyticalThinking: 2, financialLiteracy: 2 },
    actionType: 'recovery',
    effect: 'Голод +2.2, Энергия -3.5, Стресс -2.5, Настроение +7.5, Здоровье -0.8, Физическая форма -0.6, Аналитическое мышление +2, Финансовая грамотность +2',
    mood: '₿ Криптовалюта и золото — высокорисковые, но потенциально доходные инструменты',
  },
  {
    id: 'fin_auto_savings',
    category: 'finance',
    title: 'Настроить автоматические переводы на сбережения',
    hourCost: 0.5,
    price: 0,
    statChanges: { hunger: 0.9, energy: -1.5, stress: -6.5, mood: 5.5, health: 0.3, physical: -0.2 },
    skillChanges: { discipline: 3, financialLiteracy: 2 },
    actionType: 'recovery',
    effect: 'Голод +0.9, Энергия -1.5, Стресс -6.5, Настроение +5.5, Здоровье +0.3, Физическая форма -0.2, Дисциплина +3, Финансовая грамотность +2',
    mood: '🔄 Автоматика — лучший друг дисциплины в финансах',
  },
  {
    id: 'fin_expense_analysis',
    category: 'finance',
    title: 'Анализ расходов за последний месяц',
    hourCost: 2,
    price: 0,
    statChanges: { hunger: 2.8, energy: -4, stress: -10.5, mood: 9.5, health: 0.5, physical: -0.4 },
    skillChanges: { financialLiteracy: 4, organization: 3 },
    actionType: 'recovery',
    effect: 'Голод +2.8, Энергия -4, Стресс -10.5, Настроение +9.5, Здоровье +0.5, Физическая форма -0.4, Финансовая грамотность +4, Организация +3',
    mood: '📉 Когда видишь реальную картину расходов — начинаешь лучше управлять деньгами',
  },
  {
    id: 'fin_insurance',
    category: 'finance',
    title: 'Оформить страхование жизни или здоровья',
    hourCost: 2,
    price: 12000,
    statChanges: { hunger: 2.5, energy: -3.5, stress: -12.5, mood: 7.5, health: 3.5, physical: -0.4 },
    actionType: 'recovery',
    effect: 'Голод +2.5, Энергия -3.5, Стресс -12.5, Настроение +7.5, Здоровье +3.5, Физическая форма -0.4',
    mood: '🛡️ Страховка — это защита себя и близких от непредвиденных ситуаций',
    subscription: { monthlyCost: 1000 },
  },
  {
    id: 'fin_edu_invest',
    category: 'finance',
    title: 'Инвестировать в собственное образование',
    hourCost: 1,
    price: 15000,
    statChanges: { hunger: 1.8, energy: -2.8, stress: -5.5, mood: 10.5, health: 1.2, physical: -0.3 },
    skillChanges: { financialLiteracy: 2 },
    actionType: 'recovery',
    effect: 'Голод +1.8, Энергия -2.8, Стресс -5.5, Настроение +10.5, Здоровье +1.2, Физическая форма -0.3, Финансовая грамотность +2',
    mood: '📚 Лучшая инвестиция — в себя и свои навыки',
  },
  {
    id: 'fin_sell_stuff',
    category: 'finance',
    title: 'Продать ненужные вещи',
    hourCost: 3,
    price: 0,
    statChanges: { hunger: 4.2, energy: -5.5, stress: -7.5, mood: 9.5, health: -0.3, physical: -0.7 },
    skillChanges: { organization: 2.5 },
    actionType: 'recovery',
    effect: 'Голод +4.2, Энергия -5.5, Стресс -7.5, Настроение +9.5, Здоровье -0.3, Физическая форма -0.7, Организация +2.5',
    mood: '🗑️ Разбор завалов и продажа ненужного — и деньги, и порядок',
  },
  {
    id: 'fin_rent_out',
    category: 'finance',
    title: 'Сдать недвижимость в аренду',
    hourCost: 3,
    price: 0,
    statChanges: { hunger: 4.5, energy: -6, stress: -8.5, mood: 8.5, health: -0.4, physical: -0.8 },
    actionType: 'recovery',
    effect: 'Голод +4.5, Энергия -6, Стресс -8.5, Настроение +8.5, Здоровье -0.4, Физическая форма -0.8',
    mood: '🏠 Когда недвижимость начинает приносить пассивный доход — это приятно',
  },
  {
    id: 'fin_savings_account',
    category: 'finance',
    title: 'Открыть накопительный счёт',
    hourCost: 1,
    price: 5000,
    statChanges: { hunger: 1.5, energy: -2.2, stress: -7.5, mood: 6.5, health: 0.4, physical: -0.3 },
    skillChanges: { financialLiteracy: 2 },
    actionType: 'recovery',
    effect: 'Голод +1.5, Энергия -2.2, Стресс -7.5, Настроение +6.5, Здоровье +0.4, Физическая форма -0.3, Финансовая грамотность +2',
    mood: '💳 Накопительный счёт — простой и надёжный инструмент',
  },
  {
    id: 'fin_pay_mortgage',
    category: 'finance',
    title: 'Частично досрочно погасить ипотеку',
    hourCost: 2,
    price: 0,
    statChanges: { hunger: 3.2, energy: -4.5, stress: -15.5, mood: 12.5, health: 0.6, physical: -0.5 },
    actionType: 'recovery',
    effect: 'Голод +3.2, Энергия -4.5, Стресс -15.5, Настроение +12.5, Здоровье +0.6, Физическая форма -0.5',
    mood: '🏡 Когда ипотека уменьшается — груз на плечах становится легче',
  },
  {
    id: 'fin_buy_realty',
    category: 'finance',
    title: 'Купить недвижимость',
    hourCost: 6,
    price: 500000,
    statChanges: { hunger: 8.5, energy: -12.5, stress: -10.5, mood: 11.5, health: -0.8, physical: -1.5 },
    housingComfortDelta: 30,
    actionType: 'recovery',
    effect: 'Голод +8.5, Энергия -12.5, Стресс -10.5, Настроение +11.5, Здоровье -0.8, Физическая форма -1.5, Комфорт жилья +30',
    mood: '🏠 Собственная недвижимость — один из самых серьёзных шагов в жизни',
  },
  {
    id: 'fin_pif',
    category: 'finance',
    title: 'Инвестировать в паевой инвестиционный фонд (ПИФ)',
    hourCost: 2,
    price: 30000,
    statChanges: { hunger: 2.8, energy: -4, stress: -5.5, mood: 7.5, health: -0.3, physical: -0.5 },
    skillChanges: { financialLiteracy: 3, analyticalThinking: 2 },
    actionType: 'recovery',
    effect: 'Голод +2.8, Энергия -4, Стресс -5.5, Настроение +7.5, Здоровье -0.3, Физическая форма -0.5, Финансовая грамотность +3, Аналитическое мышление +2',
    mood: '📊 ПИФ — удобный способ инвестировать без глубоких знаний рынка',
  },
]