import { AgeGroup } from './types'
import type { BalanceAction } from './types'
export const FUN_ACTIONS: BalanceAction[] = [
  {
    id: 'fun_cinema',
    category: 'fun',
    title: 'Кино в кинотеатре',
    hourCost: 3,
    price: 950,
    ageGroup: AgeGroup.TODDLER,
    statChanges: { hunger: 3.5, energy: -5.5, stress: -13, mood: 24, health: -0.4, physical: -0.7 },
    actionType: 'recovery',
    effect: 'Голод +3.5, Энергия -5.5, Стресс -13, Настроение +24, Здоровье -0.4, Физическая форма -0.7',
    mood: '🎬 Большой экран и попкорн — полное погружение',
  },
  {
    id: 'fun_park_walk',
    category: 'fun',
    title: 'Прогулка в парке',
    hourCost: 2,
    price: 0,
    ageGroup: AgeGroup.INFANT,
    statChanges: { hunger: 2.8, energy: 7, stress: -13, mood: 17, health: 3.2, physical: 2.5 },
    actionType: 'recovery',
    effect: 'Голод +2.8, Энергия +7, Стресс -13, Настроение +17, Здоровье +3.2, Физическая форма +2.5',
    mood: '🌳 Свежий воздух и движение — лучшее лекарство',
  },
  {
    id: 'fun_gym',
    category: 'fun',
    title: 'Тренировка в спортзале',
    hourCost: 2,
    price: 0,
    ageGroup: AgeGroup.TEEN,
    statChanges: { hunger: 4.5, energy: -13, stress: -19, mood: 5, health: 5.5, physical: 9.5 },
    actionType: 'recovery',
    effect: 'Голод +4.5, Энергия -13, Стресс -19, Настроение +5, Здоровье +5.5, Физическая форма +9.5',
    mood: '💪 Железо куёт характер',
    requirements: { requiresItem: 'fitness_membership' },
  },
  {
    id: 'fun_meditation',
    category: 'fun',
    title: 'Медитация',
    hourCost: 1,
    price: 0,
    ageGroup: AgeGroup.CHILD,
    statChanges: { hunger: 1.2, energy: -1.5, stress: -21, mood: 13.5, health: 0.2, physical: -0.2 },
    skillChanges: { meditation: 0.3 },
    actionType: 'recovery',
    effect: 'Голод +1.2, Энергия -1.5, Стресс -21, Настроение +13.5, Здоровье +0.2, Физическая форма -0.2, Медитация +0.3',
    mood: '🧘 Тишина внутри даёт силу снаружи',
    requirements: { minSkills: { meditation: 1 } },
  },
  {
    id: 'fun_series',
    category: 'fun',
    title: 'Просмотр сериала дома',
    hourCost: 4,
    price: 0,
    ageGroup: AgeGroup.TODDLER,
    statChanges: { hunger: 4.8, energy: 2.5, stress: -9, mood: 19, health: -0.5, physical: -1 },
    actionType: 'recovery',
    effect: 'Голод +4.8, Энергия +2.5, Стресс -9, Настроение +19, Здоровье -0.5, Физическая форма -1',
    mood: '📺 Ещё одна серия… и точно спать',
  },
  {
    id: 'fun_bath',
    category: 'fun',
    title: 'Горячая ванна с солью',
    hourCost: 1.5,
    price: 200,
    ageGroup: AgeGroup.TODDLER,
    statChanges: { hunger: 2.2, energy: -3, stress: -23, mood: 15.5, health: 4.2, physical: -0.3 },
    actionType: 'recovery',
    effect: 'Голод +2.2, Энергия -3, Стресс -23, Настроение +15.5, Здоровье +4.2, Физическая форма -0.3',
    mood: '🛁 Тёплая вода смывает стресс и напряжение',
  },
  {
    id: 'fun_massage',
    category: 'fun',
    title: 'Профессиональный массаж',
    hourCost: 2,
    price: 3500,
    ageGroup: AgeGroup.YOUNG,
    statChanges: { hunger: 3, energy: 13, stress: -29, mood: 17, health: 1.5, physical: 1.8 },
    actionType: 'recovery',
    effect: 'Голод +3, Энергия +13, Стресс -29, Настроение +17, Здоровье +1.5, Физическая форма +1.8',
    mood: '💆 Лучшая инвестиция в тело и нервы',
  },
  {
    id: 'fun_yoga',
    category: 'fun',
    title: 'Йога дома',
    hourCost: 1.5,
    price: 0,
    ageGroup: AgeGroup.CHILD,
    statChanges: { hunger: 2.5, energy: -3, stress: -17, mood: 12, health: 1.8, physical: 6.5 },
    skillChanges: { meditation: 0.3 },
    actionType: 'recovery',
    effect: 'Голод +2.5, Энергия -3, Стресс -17, Настроение +12, Здоровье +1.8, Физическая форма +6.5, Медитация +0.3',
    mood: '🧘‍♀️ Гармония тела и разума за 90 минут',
    requirements: { minSkills: { meditation: 1 } },
  },
  {
    id: 'fun_concert',
    category: 'fun',
    title: 'Посещение концерта',
    hourCost: 4,
    price: 2800,
    ageGroup: AgeGroup.CHILD,
    statChanges: { hunger: 4.5, energy: -7.5, stress: -12, mood: 27, health: -0.5, physical: -1 },
    actionType: 'recovery',
    effect: 'Голод +4.5, Энергия -7.5, Стресс -12, Настроение +27, Здоровье -0.5, Физическая форма -1',
    mood: '🎵 Живая музыка лечит душу',
  },
  {
    id: 'fun_fishing',
    category: 'fun',
    title: 'Рыбалка',
    hourCost: 5,
    price: 450,
    ageGroup: AgeGroup.CHILD,
    statChanges: { hunger: 6.5, energy: -9, stress: -14, mood: 21, health: -0.6, physical: -1.2 },
    actionType: 'recovery',
    effect: 'Голод +6.5, Энергия -9, Стресс -14, Настроение +21, Здоровье -0.6, Физическая форма -1.2',
    mood: '🎣 Тишина, вода и удочка — перезагрузка',
  },
  {
    id: 'fun_sauna',
    category: 'fun',
    title: 'Сауна / баня',
    hourCost: 3,
    price: 2000,
    ageGroup: AgeGroup.TEEN,
    statChanges: { hunger: 3.8, energy: 8, stress: -25, mood: 9, health: 10.5, physical: -0.7 },
    actionType: 'recovery',
    effect: 'Голод +3.8, Энергия +8, Стресс -25, Настроение +9, Здоровье +10.5, Физическая форма -0.7',
    mood: '♨️ Пар выгоняет усталость и токсины',
  },
  {
    id: 'fun_pc_games',
    category: 'fun',
    title: 'Компьютерные игры',
    hourCost: 3,
    price: 0,
    ageGroup: AgeGroup.CHILD,
    statChanges: { hunger: 4, energy: -5.5, stress: -6.5, mood: 17, health: -0.4, physical: -0.8 },
    skillChanges: { basicCreativity: 0.1 },
    actionType: 'recovery',
    effect: 'Голод +4, Энергия -5.5, Стресс -6.5, Настроение +17, Здоровье -0.4, Физическая форма -0.8, Креативность +0.1',
    mood: '🎮 Один матч — и мозг перезагружен',
  },
  {
    id: 'fun_reading_fiction',
    category: 'fun',
    title: 'Чтение художественной литературы',
    hourCost: 2.5,
    price: 0,
    ageGroup: AgeGroup.CHILD,
    statChanges: { hunger: 3.5, energy: -4.2, stress: 1.2, mood: 13, health: -0.3, physical: -0.6 },
    skillChanges: { basicCreativity: 0.2 },
    actionType: 'recovery',
    effect: 'Голод +3.5, Энергия -4.2, Стресс +1.2, Настроение +13, Здоровье -0.3, Физическая форма -0.6, Креативность +0.2',
    mood: '📖 Книга — портал в другой мир',
    requirements: { requiresItem: 'book_general' },
  },
  {
    id: 'fun_picnic',
    category: 'fun',
    title: 'Пикник на природе',
    hourCost: 4,
    price: 1400,
    ageGroup: AgeGroup.TODDLER,
    statChanges: { hunger: -9.5, energy: -6, stress: -13, mood: 23, health: 3.8, physical: -0.9 },
    actionType: 'recovery',
    effect: 'Голод -9.5, Энергия -6, Стресс -13, Настроение +23, Здоровье +3.8, Физическая форма -0.9',
    mood: '🧺 Природа, еда и компания — идеальный день',
  },
  {
    id: 'fun_club_dancing',
    category: 'fun',
    title: 'Танцы в клубе',
    hourCost: 4,
    price: 1800,
    ageGroup: AgeGroup.ADULT,
    statChanges: { hunger: 5.5, energy: -15, stress: -10, mood: 25, health: 0.5, physical: 3.5 },
    actionType: 'recovery',
    effect: 'Голод +5.5, Энергия -15, Стресс -10, Настроение +25, Здоровье +0.5, Физическая форма +3.5',
    mood: '💃 Танцуй, пока молод — и энергия бьёт ключом',
  },
  {
    id: 'fun_spa_day',
    category: 'fun',
    title: 'День в спа-центре',
    hourCost: 6,
    price: 9500,
    ageGroup: AgeGroup.ADULT,
    statChanges: { hunger: -5, energy: -8, stress: -38, mood: 31, health: 12, physical: -1.1 },
    actionType: 'recovery',
    effect: 'Голод -5, Энергия -8, Стресс -38, Настроение +31, Здоровье +12, Физическая форма -1.1',
    mood: '💆‍♀️ Роскошь, которую ты действительно заслужил',
    cooldown: { hours: 168 },
  },
  {
    id: 'fun_motivational',
    category: 'fun',
    title: 'Просмотр мотивационного контента',
    hourCost: 1,
    price: 0,
    ageGroup: AgeGroup.TEEN,
    statChanges: { hunger: 1.3, energy: -1.8, stress: 0.4, mood: 9.5, health: -0.1, physical: -0.2 },
    skillChanges: { discipline: 0.1 },
    actionType: 'recovery',
    effect: 'Голод +1.3, Энергия -1.8, Стресс +0.4, Настроение +9.5, Здоровье -0.1, Физическая форма -0.2, Дисциплина +0.1',
    mood: '🔥 Мотивация — топливо для больших целей',
    requirements: { minSkills: { discipline: 2 } },
  },
  {
    id: 'fun_light_cleaning',
    category: 'fun',
    title: 'Лёгкая уборка дома',
    hourCost: 2,
    price: 0,
    ageGroup: AgeGroup.TODDLER,
    statChanges: { hunger: 2.8, energy: -3.5, stress: -6, mood: 4, health: 0.3, physical: 1.5 },
    skillChanges: { organization: 0.3 },
    housingComfortDelta: 12,
    actionType: 'recovery',
    effect: 'Голод +2.8, Энергия -3.5, Стресс -6, Настроение +4, Здоровье +0.3, Физическая форма +1.5, Организация +0.3, Комфорт жилья +12',
    mood: '🧹 Чистый дом — чистая голова',
    requirements: { minSkills: { organization: 2 } },
  },
  {
    id: 'fun_music_listen',
    category: 'fun',
    title: 'Прослушивание музыки',
    hourCost: 1.5,
    price: 0,
    ageGroup: AgeGroup.INFANT,
    statChanges: { hunger: 2.1, energy: -2.5, stress: -9.5, mood: 13.5, health: -0.2, physical: -0.3 },
    actionType: 'recovery',
    effect: 'Голод +2.1, Энергия -2.5, Стресс -9.5, Настроение +13.5, Здоровье -0.2, Физическая форма -0.3',
    mood: '🎧 Музыка — лучшая терапия без рецепта',
  },
  {
    id: 'fun_photoshoot',
    category: 'fun',
    title: 'Фотосессия на природе',
    hourCost: 3,
    price: 300,
    ageGroup: AgeGroup.TEEN,
    statChanges: { hunger: 4, energy: -5, stress: 1.5, mood: 18, health: -0.3, physical: -0.7 },
    skillChanges: { photography: 0.3 },
    actionType: 'recovery',
    effect: 'Голод +4, Энергия -5, Стресс +1.5, Настроение +18, Здоровье -0.3, Физическая форма -0.7, Фотография +0.3',
    mood: '📸 Останови мгновение и сохрани его',
    requirements: { minSkills: { photography: 2 } },
  },
  {
    id: 'fun_bicycle',
    category: 'fun',
    title: 'Катание на велосипеде',
    hourCost: 2.5,
    price: 0,
    ageGroup: AgeGroup.TODDLER,
    statChanges: { hunger: 4.2, energy: 0.5, stress: -13, mood: 7, health: 1.2, physical: 7.5 },
    actionType: 'recovery',
    effect: 'Голод +4.2, Энергия +0.5, Стресс -13, Настроение +7, Здоровье +1.2, Физическая форма +7.5',
    mood: '🚴 Ветер в лицо — ощущение настоящей свободы',
  },
  {
    id: 'fun_board_games',
    category: 'fun',
    title: 'Настольные игры с друзьями',
    hourCost: 3,
    price: 600,
    ageGroup: AgeGroup.CHILD,
    statChanges: { hunger: 3.8, energy: -4.5, stress: 1.2, mood: 20, health: -0.3, physical: -0.6 },
    relationshipDelta: 9,
    actionType: 'recovery',
    effect: 'Голод +3.8, Энергия -4.5, Стресс +1.2, Настроение +20, Здоровье -0.3, Физическая форма -0.6, Отношения +9',
    mood: '🎲 Смех, стратегия и тёплая компания',
  },
  {
    id: 'fun_digital_detox',
    category: 'fun',
    title: 'День в тишине (отключение гаджетов)',
    hourCost: 4,
    price: 0,
    ageGroup: AgeGroup.CHILD,
    statChanges: { hunger: 5.2, energy: -6.5, stress: -19, mood: 6, health: -0.4, physical: -0.9 },
    skillChanges: { emotionalIntelligence: 0.3 },
    actionType: 'recovery',
    effect: 'Голод +5.2, Энергия -6.5, Стресс -19, Настроение +6, Здоровье -0.4, Физическая форма -0.9, Эмоциональный интеллект +0.3',
    mood: '📵 Тишина — это тоже звук, который лечит',
    requirements: { minSkills: { emotionalIntelligence: 1 } },
  },
  {
    id: 'fun_museum',
    category: 'fun',
    title: 'Поход в музей',
    hourCost: 4,
    price: 1200,
    ageGroup: AgeGroup.CHILD,
    statChanges: { hunger: 4.8, energy: -6, stress: 1.8, mood: 16.5, health: -0.4, physical: -0.8 },
    skillChanges: { basicCreativity: 0.2 },
    actionType: 'recovery',
    effect: 'Голод +4.8, Энергия -6, Стресс +1.8, Настроение +16.5, Здоровье -0.4, Физическая форма -0.8, Креативность +0.2',
    mood: '🏛️ Искусство расширяет горизонты и успокаивает',
    requirements: { minSkills: { curiosity: 2 } },
  },
  {
    id: 'fun_active_rest',
    category: 'fun',
    title: 'Активный отдых (скалолазание, роллер)',
    hourCost: 4,
    price: 1800,
    ageGroup: AgeGroup.TEEN,
    statChanges: { hunger: 6.5, energy: -8.5, stress: -11, mood: 18, health: 1.5, physical: 10.5 },
    actionType: 'recovery',
    effect: 'Голод +6.5, Энергия -8.5, Стресс -11, Настроение +18, Здоровье +1.5, Физическая форма +10.5',
    mood: '🧗 Адреналин и движение — лучшая перезагрузка',
  },
  {
    id: 'fun_tea_relax',
    category: 'fun',
    title: 'Релакс с чаем и пледом',
    hourCost: 2,
    price: 150,
    ageGroup: AgeGroup.TODDLER,
    statChanges: { hunger: 2.6, energy: -3.2, stress: -15, mood: 14.5, health: -0.2, physical: -0.4 },
    actionType: 'recovery',
    effect: 'Голод +2.6, Энергия -3.2, Стресс -15, Настроение +14.5, Здоровье -0.2, Физическая форма -0.4',
    mood: '☕ Чай, плед и полное уединение',
  },
  {
    id: 'fun_theater',
    category: 'fun',
    title: 'Посещение театра',
    hourCost: 4,
    price: 3200,
    ageGroup: AgeGroup.CHILD,
    statChanges: { hunger: 4.5, energy: -6.5, stress: 1.5, mood: 24, health: -0.4, physical: -0.8 },
    skillChanges: { basicCreativity: 0.2 },
    actionType: 'recovery',
    effect: 'Голод +4.5, Энергия -6.5, Стресс +1.5, Настроение +24, Здоровье -0.4, Физическая форма -0.8, Креативность +0.2',
    mood: '🎭 Театр — живое зеркало человеческих эмоций',
    requirements: { minSkills: { basicCreativity: 2 } },
  },
  {
    id: 'fun_lazy_day',
    category: 'fun',
    title: 'Полный день лени (ничего не делать)',
    hourCost: 12,
    price: 0,
    ageGroup: AgeGroup.CHILD,
    statChanges: { hunger: 14.5, energy: 19, stress: -18, mood: 7, health: -1.8, physical: -6 },
    actionType: 'recovery',
    effect: 'Голод +14.5, Энергия +19, Стресс -18, Настроение +7, Здоровье -1.8, Физическая форма -6',
    mood: '🛋️ Иногда лучший план — вообще никакого плана',
  },
  {
    id: 'fun_morning_run',
    category: 'fun',
    title: 'Утренняя пробежка',
    hourCost: 1,
    price: 0,
    ageGroup: AgeGroup.CHILD,
    statChanges: { hunger: 2.2, energy: 4.5, stress: -5.5, mood: 5, health: 0.8, physical: 4.2 },
    actionType: 'recovery',
    effect: 'Голод +2.2, Энергия +4.5, Стресс -5.5, Настроение +5, Здоровье +0.8, Физическая форма +4.2',
    mood: '🏃 Утро с бегом задаёт тон всему дню',
  },
  {
    id: 'fun_swimming',
    category: 'fun',
    title: 'Плавание в бассейне',
    hourCost: 1.5,
    price: 600,
    ageGroup: AgeGroup.TODDLER,
    statChanges: { hunger: 3.2, energy: -3, stress: -12.5, mood: 6.5, health: 3.8, physical: 5.5 },
    actionType: 'recovery',
    effect: 'Голод +3.2, Энергия -3, Стресс -12.5, Настроение +6.5, Здоровье +3.8, Физическая форма +5.5',
    mood: '🏊 Вода расслабляет тело и очищает голову',
  },
  {
    id: 'fun_chess',
    category: 'fun',
    title: 'Шахматы / головоломки',
    hourCost: 1.5,
    price: 0,
    ageGroup: AgeGroup.CHILD,
    statChanges: { hunger: 2.1, energy: -2.5, stress: 0.8, mood: 7.5, health: -0.2, physical: -0.3 },
    skillChanges: { analyticalThinking: 0.2 },
    actionType: 'recovery',
    effect: 'Голод +2.1, Энергия -2.5, Стресс +0.8, Настроение +7.5, Здоровье -0.2, Физическая форма -0.3, Аналитическое мышление +0.2',
    mood: '♟️ Гимнастика для ума в чистом виде',
  },
  {
    id: 'fun_deep_cleaning',
    category: 'fun',
    title: 'Генеральная уборка',
    hourCost: 4,
    price: 500,
    ageGroup: AgeGroup.CHILD,
    statChanges: { hunger: 5, energy: -7, stress: -7.5, mood: 5, health: -0.5, physical: 2.5 },
    skillChanges: { organization: 0.3 },
    housingComfortDelta: 22,
    actionType: 'recovery',
    effect: 'Голод +5, Энергия -7, Стресс -7.5, Настроение +5, Здоровье -0.5, Физическая форма +2.5, Организация +0.3, Комфорт жилья +22',
    mood: '🧽 Генеральная уборка = перезапуск пространства',
    requirements: { minSkills: { organization: 3 } },
  },
  {
    id: 'fun_shopping_therapy',
    category: 'fun',
    title: 'Шопинг-терапия',
    hourCost: 3,
    price: 3000,
    ageGroup: AgeGroup.ADULT,
    statChanges: { hunger: 3.5, energy: -5, stress: -8, mood: 18.5, health: -0.3, physical: -0.7 },
    actionType: 'recovery',
    effect: 'Голод +3.5, Энергия -5, Стресс -8, Настроение +18.5, Здоровье -0.3, Физическая форма -0.7',
    mood: '🛍️ Иногда новые вещи действительно лечат',
  },
  {
    id: 'fun_beach',
    category: 'fun',
    title: 'Отдых на пляже / загорать',
    hourCost: 4,
    price: 300,
    ageGroup: AgeGroup.TODDLER,
    statChanges: { hunger: 4.5, energy: -6.5, stress: -9, mood: 17, health: 3.5, physical: -1 },
    actionType: 'recovery',
    effect: 'Голод +4.5, Энергия -6.5, Стресс -9, Настроение +17, Здоровье +3.5, Физическая форма -1',
    mood: '🏖️ Солнце, море и полное отключение',
  },
  // ───── НОВЫЕ ЖИЗНЕННЫЕ ДЕЙСТВИЯ ─────
  {
    id: 'fun_pet_play',
    category: 'fun',
    title: 'Игра с домашним питомцем',
    hourCost: 1,
    price: 0,
    ageGroup: AgeGroup.TODDLER,
    statChanges: { hunger: 1.5, energy: 3.5, stress: -15, mood: 19, health: 1, physical: 1.2 },
    actionType: 'recovery',
    effect: 'Голод +1.5, Энергия +3.5, Стресс -15, Настроение +19, Здоровье +1, Физическая форма +1.2',
    mood: '🐶 Любовь пушистого друга — мгновенная перезагрузка',
    requirements: undefined,
  },
  {
    id: 'fun_gardening',
    category: 'fun',
    title: 'Уход за растениями / садоводство',
    hourCost: 2,
    price: 180,
    ageGroup: AgeGroup.TODDLER,
    statChanges: { hunger: 2.8, energy: -2.5, stress: -13.5, mood: 15.5, health: 2.8, physical: 3.5 },
    skillChanges: { gardening: 0.3 },
    actionType: 'recovery',
    effect: 'Голод +2.8, Энергия -2.5, Стресс -13.5, Настроение +15.5, Здоровье +2.8, Физическая форма +3.5, Садоводство +0.3',
    mood: '🌱 Руки в земле — голова в порядке',
  },
  {
    id: 'fun_home_cooking',
    category: 'fun',
    title: 'Готовка любимого блюда',
    hourCost: 2.5,
    price: 480,
    ageGroup: AgeGroup.CHILD,
    statChanges: { hunger: -11, energy: -2, stress: -7, mood: 18.5, health: 4, physical: -0.5 },
    actionType: 'recovery',
    effect: 'Голод -11, Энергия -2, Стресс -7, Настроение +18.5, Здоровье +4, Физическая форма -0.5',
    mood: '🍳 Процесс и результат — двойное удовольствие',
  },
  {
    id: 'fun_art_drawing',
    category: 'fun',
    title: 'Рисование / творчество',
    hourCost: 2,
    price: 220,
    ageGroup: AgeGroup.TODDLER,
    statChanges: { hunger: 2.8, energy: -3.5, stress: -9, mood: 16, health: -0.2, physical: -0.4 },
    skillChanges: { basicCreativity: 0.3 },
    actionType: 'recovery',
    effect: 'Голод +2.8, Энергия -3.5, Стресс -9, Настроение +16, Здоровье -0.2, Физическая форма -0.4, Креативность +0.3',
    mood: '🎨 Творчество — это разговор с самим собой',
  },
  {
    id: 'fun_podcast',
    category: 'fun',
    title: 'Прослушивание подкаста',
    hourCost: 1.5,
    price: 0,
    ageGroup: AgeGroup.TEEN,
    statChanges: { hunger: 2.2, energy: -1.8, stress: -8, mood: 12, health: -0.1, physical: -0.3 },
    skillChanges: { emotionalIntelligence: 1, analyticalThinking: 1 },
    actionType: 'recovery',
    effect: 'Голод +2.2, Энергия -1.8, Стресс -8, Настроение +12, Здоровье -0.1, Физическая форма -0.3, Эмоциональный интеллект +1, Аналитическое мышление +1',
    mood: '🎙️ Новые мысли и идеи прямо в уши',
  },
  {
    id: 'fun_friends_call',
    category: 'fun',
    title: 'Звонок друзьям или семье',
    hourCost: 1,
    price: 0,
    ageGroup: AgeGroup.CHILD,
    statChanges: { hunger: 1.4, energy: 2, stress: -15.5, mood: 20.5, health: 0.3, physical: -0.2 },
    relationshipDelta: 13,
    actionType: 'recovery',
    effect: 'Голод +1.4, Энергия +2, Стресс -15.5, Настроение +20.5, Здоровье +0.3, Физическая форма -0.2, Отношения +13',
    mood: '📞 Живое общение — лучше любой терапии',
  },
  {
    id: 'fun_stargazing',
    category: 'fun',
    title: 'Наблюдение за звёздами',
    hourCost: 2,
    price: 0,
    ageGroup: AgeGroup.TODDLER,
    statChanges: { hunger: 2.9, energy: -3, stress: -16.5, mood: 13.5, health: 1, physical: -0.4 },
    actionType: 'recovery',
    effect: 'Голод +2.9, Энергия -3, Стресс -16.5, Настроение +13.5, Здоровье +1, Физическая форма -0.4',
    mood: '🌌 Космос напоминает, что всё будет хорошо',
  },
  {
    id: 'fun_karaoke',
    category: 'fun',
    title: 'Караоке дома',
    hourCost: 1.5,
    price: 0,
    ageGroup: AgeGroup.TODDLER,
    statChanges: { hunger: 2.3, energy: -2, stress: -11.5, mood: 17.5, health: -0.2, physical: -0.4 },
    actionType: 'recovery',
    effect: 'Голод +2.3, Энергия -2, Стресс -11.5, Настроение +17.5, Здоровье -0.2, Физическая форма -0.4',
    mood: '🎤 Пой громко — никто не осудит',
  },
  {
    id: 'fun_sleep_short',
    category: 'fun',
    title: 'Короткий сон (4 часа)',
    hourCost: 4,
    price: 0,
    ageGroup: AgeGroup.INFANT,
    statChanges: { hunger: 5, energy: 40, stress: -15, mood: 8, health: 3, physical: 2 },
    actionType: 'sleep',
    effect: 'Голод +5, Энергия +40, Стресс -15, Настроение +8, Здоровье +3, Физическая форма +2',
    mood: '💤 Короткий сон — быстрая перезагрузка',
  },
  {
    id: 'fun_sleep_normal',
    category: 'fun',
    title: 'Нормальный сон (7 часов)',
    hourCost: 7,
    price: 0,
    ageGroup: AgeGroup.INFANT,
    statChanges: { hunger: 8, energy: 70, stress: -25, mood: 15, health: 6, physical: 4 },
    actionType: 'sleep',
    effect: 'Голод +8, Энергия +70, Стресс -25, Настроение +15, Здоровье +6, Физическая форма +4',
    mood: '🌙 Полноценный сон — залог продуктивного дня',
  },
  {
    id: 'fun_sleep_long',
    category: 'fun',
    title: 'Длительный сон (10 часов)',
    hourCost: 10,
    price: 0,
    ageGroup: AgeGroup.INFANT,
    statChanges: { hunger: 12, energy: 100, stress: -35, mood: 20, health: 8, physical: 5 },
    actionType: 'sleep',
    effect: 'Голод +12, Энергия +100, Стресс -35, Настроение +20, Здоровье +8, Физическая форма +5',
    mood: '😴 Длительный отдых — полное восстановление сил',
  },
]