import type { BalanceAction } from './types'
import { AgeGroup } from './types'

export const HEALTH_ACTIONS: BalanceAction[] = [
  {
    id: 'health_checkup',
    category: 'health',
    title: 'Пройти полный медосмотр',
    hourCost: 3,
    price: 3000,
    statChanges: { hunger: 3.5, energy: -5.5, stress: 2.5, mood: 1.5, health: 9.5, physical: -0.8 },
    skillChanges: { medicalKnowledge: 1.5 },
    actionType: 'health',
    effect: 'Голод +3.5, Энергия -5.5, Стресс +2.5, Настроение +1.5, Здоровье +9.5, Физическая форма -0.8, Медицинские знания +1.5',
    mood: '🩺 Полный чек-ап — спокойствие и контроль над здоровьем',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'health_blood_test',
    category: 'health',
    title: 'Сдать анализы крови',
    hourCost: 2,
    price: 1500,
    statChanges: { hunger: 2.8, energy: -4, stress: 1.8, mood: 0.5, health: 6.2, physical: -0.5 },
    actionType: 'health',
    effect: 'Голод +2.8, Энергия -4, Стресс +1.8, Настроение +0.5, Здоровье +6.2, Физическая форма -0.5',
    mood: '🩸 Раннее выявление проблем — инвестиция в будущее',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'health_dentist',
    category: 'health',
    title: 'Посетить стоматолога',
    hourCost: 2,
    price: 4000,
    statChanges: { hunger: 2.5, energy: -3.5, stress: 2.2, mood: -3.5, health: 7.5, physical: -0.6 },
    actionType: 'health',
    effect: 'Голод +2.5, Энергия -3.5, Стресс +2.2, Настроение -3.5, Здоровье +7.5, Физическая форма -0.6',
    mood: '🦷 Здоровые зубы того стоят, даже если неприятно',
    ageGroup: AgeGroup.TODDLER,
  },
  {
    id: 'health_psychologist',
    category: 'health',
    title: 'Сеанс у психолога',
    hourCost: 2,
    price: 3500,
    statChanges: { hunger: 2.4, energy: -3.2, stress: -18, mood: 8.5, health: 1.2, physical: -0.4 },
    skillChanges: { emotionalIntelligence: 2.5 },
    actionType: 'health',
    effect: 'Голод +2.4, Энергия -3.2, Стресс -18, Настроение +8.5, Здоровье +1.2, Физическая форма -0.4, Эмоциональный интеллект +2.5',
    mood: '🧠 Разговор по душам — лучшее лекарство для психики',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'health_vitamins',
    category: 'health',
    title: 'Курс витаминов и добавок',
    hourCost: 0.5,
    price: 500,
    statChanges: { hunger: 0.8, energy: 3.5, stress: -0.5, mood: 1.8, health: 5.5, physical: 0.3 },
    actionType: 'health',
    effect: 'Голод +0.8, Энергия +3.5, Стресс -0.5, Настроение +1.8, Здоровье +5.5, Физическая форма +0.3',
    mood: '💊 Витамины — ежедневная поддержка организма',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'health_massage_course',
    category: 'health',
    title: 'Курс лечебного массажа',
    hourCost: 2,
    price: 4000,
    statChanges: { hunger: 2.8, energy: -4, stress: -19.5, mood: 6, health: 8.5, physical: 2.5 },
    actionType: 'health',
    effect: 'Голод +2.8, Энергия -4, Стресс -19.5, Настроение +6, Здоровье +8.5, Физическая форма +2.5',
    mood: '👐 Лечебный массаж — восстановление тела и снятие зажимов',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'health_vaccination',
    category: 'health',
    title: 'Пройти вакцинацию',
    hourCost: 1,
    price: 1200,
    statChanges: { hunger: 1.5, energy: -2.2, stress: 1.5, mood: 0.8, health: 6.8, physical: -0.3 },
    actionType: 'health',
    effect: 'Голод +1.5, Энергия -2.2, Стресс +1.5, Настроение +0.8, Здоровье +6.8, Физическая форма -0.3',
    mood: '💉 Защита организма — лучше перестраховаться',
    ageGroup: AgeGroup.TODDLER,
  },
  {
    id: 'health_sick_leave',
    category: 'health',
    title: 'Постельный режим при болезни',
    hourCost: 8,
    price: 800,
    statChanges: { hunger: 9.5, energy: 12, stress: -8, mood: 4.5, health: 14.5, physical: -3.5 },
    actionType: 'health',
    effect: 'Голод +9.5, Энергия +12, Стресс -8, Настроение +4.5, Здоровье +14.5, Физическая форма -3.5',
    mood: '🛏️ Когда болеешь — лучший выход дать организму восстановиться',
    ageGroup: AgeGroup.TODDLER,
  },
  {
    id: 'health_morning_contrast_shower',
    category: 'health',
    title: 'Контрастный душ по утрам',
    hourCost: 0.3,
    price: 0,
    statChanges: { hunger: 1.2, energy: 8.5, stress: -6.5, mood: 5.5, health: 3.2, physical: 1.8 },
    actionType: 'health',
    effect: 'Голод +1.2, Энергия +8.5, Стресс -6.5, Настроение +5.5, Здоровье +3.2, Физическая форма +1.8',
    mood: '🚿 Контрастный душ — бодрость и укрепление иммунитета',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'health_breathing_exercises',
    category: 'health',
    title: 'Дыхательные упражнения',
    hourCost: 0.7,
    price: 0,
    statChanges: { hunger: 0.9, energy: 2.5, stress: -14, mood: 7.5, health: 1.8, physical: -0.2 },
    skillChanges: { emotionalIntelligence: 1 },
    actionType: 'health',
    effect: 'Голод +0.9, Энергия +2.5, Стресс -14, Настроение +7.5, Здоровье +1.8, Физическая форма -0.2, Эмоциональный интеллект +1',
    mood: '🫁 Правильное дыхание — быстрый способ снять тревогу',
    ageGroup: AgeGroup.INFANT,
  },
  {
    id: 'health_healthy_meal_prep',
    category: 'health',
    title: 'Подготовка здорового питания на неделю',
    hourCost: 3,
    price: 1200,
    statChanges: { hunger: -8.5, energy: -2.5, stress: -4.5, mood: 6.5, health: 5.5, physical: 1.2 },
    actionType: 'health',
    effect: 'Голод -8.5, Энергия -2.5, Стресс -4.5, Настроение +6.5, Здоровье +5.5, Физическая форма +1.2',
    mood: '🥗 Готовим заранее — легче придерживаться правильного питания',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'health_walk_in_fresh_air',
    category: 'health',
    title: 'Прогулка на свежем воздухе (оздоровительная)',
    hourCost: 1.5,
    price: 0,
    statChanges: { hunger: 2.2, energy: 6.5, stress: -10.5, mood: 8.5, health: 3.8, physical: 3.5 },
    actionType: 'health',
    effect: 'Голод +2.2, Энергия +6.5, Стресс -10.5, Настроение +8.5, Здоровье +3.8, Физическая форма +3.5',
    mood: '🌬️ 30–40 минут на воздухе — простое и мощное оздоровление',
    ageGroup: AgeGroup.INFANT,
  },
  {
    id: 'health_sleep_hygiene',
    category: 'health',
    title: 'Соблюдение гигиены сна (ритуал перед сном)',
    hourCost: 0.8,
    price: 0,
    statChanges: { hunger: 1.1, energy: 4.5, stress: -9.5, mood: 6, health: 2.8, physical: 0.8 },
    actionType: 'health',
    effect: 'Голод +1.1, Энергия +4.5, Стресс -9.5, Настроение +6, Здоровье +2.8, Физическая форма +0.8',
    mood: '🌙 Правильный ритуал перед сном улучшает качество отдыха',
    ageGroup: AgeGroup.INFANT,
  },
]