import type { BalanceAction } from './types'

export const HEALTH_ACTIONS: BalanceAction[] = [
  {
    id: 'health_checkup',
    category: 'health',
    title: 'Пройти медосмотр',
    hourCost: 3,
    price: 3000,
    statChanges: { health: 8 },
    skillChanges: { medicalKnowledge: 1 },
    actionType: 'health',
    effect: 'Здоровье +8, Медицинские знания +1',
  },
  {
    id: 'health_blood_test',
    category: 'health',
    title: 'Сдать анализы',
    hourCost: 2,
    price: 1500,
    statChanges: { health: 5 },
    actionType: 'health',
    effect: 'Здоровье +5, раннее обнаружение проблем',
  },
  {
    id: 'health_dentist',
    category: 'health',
    title: 'Посетить стоматолога',
    hourCost: 2,
    price: 4000,
    statChanges: { health: 6, mood: -3 },
    actionType: 'health',
    effect: 'Здоровье +6, Настроение -3',
  },
  {
    id: 'health_psychologist',
    category: 'health',
    title: 'Пойти к психологу',
    hourCost: 2,
    price: 3500,
    statChanges: { stress: -15 },
    skillChanges: { emotionalIntelligence: 2 },
    actionType: 'health',
    effect: 'Стресс -15, Эмоциональный интеллект +2',
  },
  {
    id: 'health_vitamins',
    category: 'health',
    title: 'Принять витамины',
    hourCost: 0.5,
    price: 500,
    statChanges: { health: 4, energy: 3 },
    actionType: 'health',
    effect: 'Здоровье +4, Энергия +3',
  },
  {
    id: 'health_massage_course',
    category: 'health',
    title: 'Пройти курс лечебного массажа',
    hourCost: 2,
    price: 4000,
    statChanges: { health: 8, stress: -18 },
    actionType: 'health',
    effect: 'Здоровье +8, Стресс -18',
  },
  {
    id: 'health_vaccination',
    category: 'health',
    title: 'Вакцинация',
    hourCost: 1,
    price: 1200,
    statChanges: { health: 5 },
    actionType: 'health',
    effect: 'Здоровье +5, защита от болезней',
  },
  {
    id: 'health_sick_leave',
    category: 'health',
    title: 'Лечение простуды — постельный режим',
    hourCost: 8,
    price: 800,
    statChanges: { health: 12, energy: 15 },
    actionType: 'health',
    effect: 'Здоровье +12, Энергия +15, пропускает работу',
  },
]

