import type { BalanceAction } from './types'

export const HOBBY_ACTIONS: BalanceAction[] = [
  {
    id: 'hob_drawing',
    category: 'hobby',
    title: 'Рисование / живопись',
    hourCost: 3,
    price: 800,
    statChanges: { mood: 12 },
    skillChanges: { artisticMastery: 3, basicCreativity: 3 },
    actionType: 'hobby',
    effect: 'Креативность +3, Настроение +12',
  },
  {
    id: 'hob_instrument',
    category: 'hobby',
    title: 'Игра на музыкальном инструменте',
    hourCost: 2.5,
    price: 0,
    statChanges: { mood: 15 },
    skillChanges: { musicalAbility: 2 },
    actionType: 'hobby',
    effect: 'Настроение +15, Музыкальные способности +2',
  },
  {
    id: 'hob_writing',
    category: 'hobby',
    title: 'Написание текста / блога',
    hourCost: 3,
    price: 0,
    statChanges: {},
    skillChanges: { writing: 2, basicCreativity: 3 },
    actionType: 'hobby',
    effect: 'Креативность +3, Писательское мастерство +2',
  },
  {
    id: 'hob_photography',
    category: 'hobby',
    title: 'Фотография',
    hourCost: 3,
    price: 400,
    statChanges: {},
    skillChanges: { photography: 2, basicCreativity: 3 },
    actionType: 'hobby',
    effect: 'Креативность +3, Фотография +2',
  },
  {
    id: 'hob_gardening_act',
    category: 'hobby',
    title: 'Садоводство / уход за растениями',
    hourCost: 2,
    price: 300,
    statChanges: { housingComfortDelta: 8 },
    skillChanges: { gardening: 3 },
    actionType: 'hobby',
    effect: 'Садоводство +3, Комфорт дома +8',
  },
  {
    id: 'hob_craft',
    category: 'hobby',
    title: 'Ремесло (вязание, лепка и т.д.)',
    hourCost: 4,
    price: 1200,
    statChanges: { mood: 10 },
    skillChanges: { handiness: 2, basicCreativity: 3 },
    actionType: 'hobby',
    effect: 'Креативность +3, Ремесло +2',
  },
  {
    id: 'hob_dance',
    category: 'hobby',
    title: 'Танцы дома',
    hourCost: 2,
    price: 0,
    statChanges: { physical: 5, mood: 14 },
    skillChanges: { dance: 2 },
    actionType: 'hobby',
    effect: 'Физическая форма +5, Настроение +14',
  },
  {
    id: 'hob_cooking',
    category: 'hobby',
    title: 'Кулинарные эксперименты',
    hourCost: 2.5,
    price: 900,
    statChanges: { mood: 10 },
    skillChanges: { cooking: 3 },
    actionType: 'hobby',
    effect: 'Кулинария +3, Настроение +10',
  },
  {
    id: 'hob_content',
    category: 'hobby',
    title: 'Создание контента (видео)',
    hourCost: 5,
    price: 0,
    statChanges: {},
    skillChanges: { marketing: 2, basicCreativity: 3 },
    actionType: 'hobby',
    effect: 'Маркетинг +2, Креативность +3',
  },
  {
    id: 'hob_collecting',
    category: 'hobby',
    title: 'Коллекционирование',
    hourCost: 2,
    price: 2000,
    statChanges: { mood: 8 },
    skillChanges: { basicCreativity: 1 },
    actionType: 'hobby',
    effect: 'Настроение +8, Креативность +1',
  },
  {
    id: 'hob_woodwork',
    category: 'hobby',
    title: 'Столярное дело / работа с деревом',
    hourCost: 3,
    price: 1200,
    statChanges: { mood: 10 },
    skillChanges: { handiness: 3 },
    actionType: 'hobby',
    effect: 'Ремесло +3, Настроение +10',
  },
  {
    id: 'hob_origami',
    category: 'hobby',
    title: 'Оригами / бумажное искусство',
    hourCost: 1.5,
    price: 300,
    statChanges: {},
    skillChanges: { basicCreativity: 2, patience: 1 },
    actionType: 'hobby',
    effect: 'Креативность +2, Терпение +1',
  },
  {
    id: 'hob_wine',
    category: 'hobby',
    title: 'Виноделие / домашнее пивоварение',
    hourCost: 4,
    price: 2000,
    statChanges: { mood: 8 },
    skillChanges: { culinaryArt: 2 },
    actionType: 'hobby',
    effect: 'Кулинарное искусство +2, Настроение +8',
  },
  {
    id: 'hob_astronomy',
    category: 'hobby',
    title: 'Астрономия — наблюдение за звёздами',
    hourCost: 3,
    price: 500,
    statChanges: { mood: 12 },
    skillChanges: { curiosity: 2 },
    actionType: 'hobby',
    effect: 'Любознательность +2, Настроение +12',
  },
  {
    id: 'hob_blogging',
    category: 'hobby',
    title: 'Блогерство / подкаст',
    hourCost: 4,
    price: 0,
    statChanges: {},
    skillChanges: { writing: 2, marketing: 1 },
    actionType: 'hobby',
    effect: 'Писательское мастерство +2, Маркетинг +1',
  },
  {
    id: 'hob_calligraphy',
    category: 'hobby',
    title: 'Каллиграфия',
    hourCost: 2,
    price: 800,
    statChanges: {},
    skillChanges: { basicCreativity: 2, discipline: 1 },
    actionType: 'hobby',
    effect: 'Креативность +2, Дисциплина +1',
  },
  {
    id: 'hob_street_art',
    category: 'hobby',
    title: 'Стрит-арт / граффити',
    hourCost: 3,
    price: 1500,
    statChanges: { mood: 10 },
    skillChanges: { artisticMastery: 2 },
    actionType: 'hobby',
    effect: 'Художественное мастерство +2, Настроение +10',
  },
  {
    id: 'hob_digital_music',
    category: 'hobby',
    title: 'Создание музыки на компьютере',
    hourCost: 3,
    price: 0,
    statChanges: {},
    skillChanges: { musicalAbility: 2, basicCreativity: 2 },
    actionType: 'hobby',
    effect: 'Музыкальные способности +2, Креативность +2',
  },
]
