import type { BalanceAction } from './types'
import { AgeGroup } from './types'

export const HOBBY_ACTIONS: BalanceAction[] = [
  {
    id: 'hob_drawing',
    category: 'hobby',
    ageGroup: AgeGroup.TODDLER,
    title: 'Рисование / живопись',
    hourCost: 3,
    price: 800,
    statChanges: { hunger: 4.2, energy: -5.5, stress: -4.5, mood: 18.5, health: -0.3, physical: -0.7 },
    skillChanges: { artisticMastery: 3.5, basicCreativity: 3 },
    actionType: 'hobby',
    effect: 'Голод +4.2, Энергия -5.5, Стресс -4.5, Настроение +18.5, Здоровье -0.3, Физическая форма -0.7, Художественное мастерство +3.5, Креативность +3',
    mood: '🎨 Когда кисть в руках — время летит незаметно',
    requirements: { requiresItem: 'art_supplies' },
  },
  {
    id: 'hob_instrument',
    category: 'hobby',
    ageGroup: AgeGroup.TODDLER,
    title: 'Игра на музыкальном инструменте',
    hourCost: 2.5,
    price: 0,
    statChanges: { hunger: 3.5, energy: -4.8, stress: -6.5, mood: 19.5, health: -0.2, physical: -0.5 },
    skillChanges: { musicalAbility: 2.5 },
    actionType: 'hobby',
    effect: 'Голод +3.5, Энергия -4.8, Стресс -6.5, Настроение +19.5, Здоровье -0.2, Физическая форма -0.5, Музыкальные способности +2.5',
    mood: '🎸 Музыка — это язык, на котором говорит душа',
  },
  {
    id: 'hob_writing',
    category: 'hobby',
    ageGroup: AgeGroup.TEEN,
    title: 'Написание текста / блога / книги',
    hourCost: 3,
    price: 0,
    statChanges: { hunger: 4.1, energy: -5.2, stress: -3.5, mood: 16.5, health: -0.3, physical: -0.6 },
    skillChanges: { writing: 3, basicCreativity: 3.5 },
    actionType: 'hobby',
    effect: 'Голод +4.1, Энергия -5.2, Стресс -3.5, Настроение +16.5, Здоровье -0.3, Физическая форма -0.6, Писательское мастерство +3, Креативность +3.5',
    mood: '✍️ Слова рождаются в тишине и сосредоточенности',
  },
  {
    id: 'hob_photography',
    category: 'hobby',
    ageGroup: AgeGroup.CHILD,
    title: 'Фотография (прогулка с камерой)',
    hourCost: 3,
    price: 400,
    statChanges: { hunger: 4.3, energy: -4.5, stress: -5, mood: 17, health: 0.5, physical: 1.2 },
    skillChanges: { photography: 3, basicCreativity: 2.5 },
    actionType: 'hobby',
    effect: 'Голод +4.3, Энергия -4.5, Стресс -5, Настроение +17, Здоровье +0.5, Физическая форма +1.2, Фотография +3, Креативность +2.5',
    mood: '📸 Ловишь момент — и мир становится красивее',
    requirements: { requiresItem: 'camera' },
  },
  {
    id: 'hob_gardening_act',
    category: 'hobby',
    ageGroup: AgeGroup.TODDLER,
    title: 'Садоводство и уход за растениями',
    hourCost: 2,
    price: 300,
    statChanges: { hunger: 3.2, energy: -3.8, stress: -7.5, mood: 14.5, health: 2.8, physical: 3.5 },
    skillChanges: { gardening: 3.5 },
    housingComfortDelta: 10,
    actionType: 'hobby',
    effect: 'Голод +3.2, Энергия -3.8, Стресс -7.5, Настроение +14.5, Здоровье +2.8, Физическая форма +3.5, Садоводство +3.5, Комфорт жилья +10',
    mood: '🌱 Растения учат терпению и дают ощущение жизни',
    requirements: { requiresItem: 'garden_tools' },
  },
  {
    id: 'hob_craft',
    category: 'hobby',
    ageGroup: AgeGroup.CHILD,
    title: 'Ремесло (вязание, лепка, скрапбукинг)',
    hourCost: 4,
    price: 1200,
    statChanges: { hunger: 5.5, energy: -6.8, stress: -5, mood: 17, health: -0.4, physical: -0.8 },
    skillChanges: { handiness: 3, basicCreativity: 3 },
    actionType: 'hobby',
    effect: 'Голод +5.5, Энергия -6.8, Стресс -5, Настроение +17, Здоровье -0.4, Физическая форма -0.8, Рукоделие +3, Креативность +3',
    mood: '🧶 Руками создаёшь — и внутри становится теплее',
  },
  {
    id: 'hob_dance',
    category: 'hobby',
    ageGroup: AgeGroup.TODDLER,
    title: 'Танцы дома',
    hourCost: 2,
    price: 0,
    statChanges: { hunger: 3.8, energy: -4.5, stress: -8, mood: 18.5, health: 0.8, physical: 6.5 },
    skillChanges: { dance: 2.5 },
    actionType: 'hobby',
    effect: 'Голод +3.8, Энергия -4.5, Стресс -8, Настроение +18.5, Здоровье +0.8, Физическая форма +6.5, Танцевальное мастерство +2.5',
    mood: '💃 Танцуешь дома — и стресс уходит сам собой',
  },
  {
    id: 'hob_cooking',
    category: 'hobby',
    ageGroup: AgeGroup.CHILD,
    title: 'Кулинарные эксперименты',
    hourCost: 2.5,
    price: 900,
    statChanges: { hunger: -10.5, energy: -3.5, stress: -6, mood: 19, health: 3.5, physical: -0.5 },
    skillChanges: { cooking: 3.5 },
    actionType: 'hobby',
    effect: 'Голод -10.5, Энергия -3.5, Стресс -6, Настроение +19, Здоровье +3.5, Физическая форма -0.5, Кулинарное мастерство +3.5',
    mood: '🍳 Когда эксперимент удался — это настоящая победа',
    requirements: { requiresItem: 'cooking_set' },
  },
  {
    id: 'hob_content',
    category: 'hobby',
    ageGroup: AgeGroup.TEEN,
    title: 'Создание контента (видео, reels)',
    hourCost: 5,
    price: 0,
    statChanges: { hunger: 6.5, energy: -9.5, stress: -2.5, mood: 15.5, health: -0.6, physical: -1.2 },
    skillChanges: { marketing: 2.5, basicCreativity: 4 },
    actionType: 'hobby',
    effect: 'Голод +6.5, Энергия -9.5, Стресс -2.5, Настроение +15.5, Здоровье -0.6, Физическая форма -1.2, Маркетинг +2.5, Креативность +4',
    mood: '🎥 Создаёшь контент — и чувствуешь себя творцом',
  },
  {
    id: 'hob_collecting',
    category: 'hobby',
    ageGroup: AgeGroup.TODDLER,
    title: 'Коллекционирование (марки, монеты, фигурки)',
    hourCost: 2,
    price: 2000,
    statChanges: { hunger: 2.8, energy: -3.2, stress: -4, mood: 12.5, health: -0.2, physical: -0.4 },
    skillChanges: { basicCreativity: 1.5, patience: 1 },
    actionType: 'hobby',
    effect: 'Голод +2.8, Энергия -3.2, Стресс -4, Настроение +12.5, Здоровье -0.2, Физическая форма -0.4, Креативность +1.5, Терпение +1',
    mood: '🏷️ Коллекция — это история, которую ты собираешь сам',
  },
  {
    id: 'hob_woodwork',
    category: 'hobby',
    ageGroup: AgeGroup.TEEN,
    title: 'Столярное дело / работа с деревом',
    hourCost: 3,
    price: 1200,
    statChanges: { hunger: 4.5, energy: -6, stress: -5.5, mood: 16, health: 1.2, physical: 4.5 },
    skillChanges: { handiness: 4 },
    actionType: 'hobby',
    effect: 'Голод +4.5, Энергия -6, Стресс -5.5, Настроение +16, Здоровье +1.2, Физическая форма +4.5, Рукоделие +4',
    mood: '🔨 Дерево в руках — это настоящее мужское (или женское) творчество',
  },
  {
    id: 'hob_origami',
    category: 'hobby',
    ageGroup: AgeGroup.TODDLER,
    title: 'Оригами и бумажное искусство',
    hourCost: 1.5,
    price: 300,
    statChanges: { hunger: 2.2, energy: -2.8, stress: -5.5, mood: 11.5, health: -0.1, physical: -0.3 },
    skillChanges: { basicCreativity: 2.5, patience: 2 },
    actionType: 'hobby',
    effect: 'Голод +2.2, Энергия -2.8, Стресс -5.5, Настроение +11.5, Здоровье -0.1, Физическая форма -0.3, Креативность +2.5, Терпение +2',
    mood: '🦢 Из бумаги рождается красота и спокойствие',
  },
  {
    id: 'hob_wine',
    category: 'hobby',
    ageGroup: AgeGroup.ADULT,
    title: 'Домашнее виноделие / пивоварение',
    hourCost: 4,
    price: 2000,
    statChanges: { hunger: 5.2, energy: -5.8, stress: -3, mood: 14.5, health: 0.8, physical: -0.9 },
    skillChanges: { culinaryArt: 3 },
    actionType: 'hobby',
    effect: 'Голод +5.2, Энергия -5.8, Стресс -3, Настроение +14.5, Здоровье +0.8, Физическая форма -0.9, Кулинарное искусство +3',
    mood: '🍷 Терпение и наука в одном флаконе',
  },
  {
    id: 'hob_astronomy',
    category: 'hobby',
    ageGroup: AgeGroup.CHILD,
    title: 'Астрономия — наблюдение за звёздами',
    hourCost: 3,
    price: 500,
    statChanges: { hunger: 3.8, energy: -4.2, stress: -9, mood: 18, health: 1.5, physical: -0.6 },
    skillChanges: { curiosity: 3 },
    actionType: 'hobby',
    effect: 'Голод +3.8, Энергия -4.2, Стресс -9, Настроение +18, Здоровье +1.5, Физическая форма -0.6, Любознательность +3',
    mood: '🔭 Вселенная напоминает, насколько мы малы и прекрасны',
  },
  {
    id: 'hob_blogging',
    category: 'hobby',
    ageGroup: AgeGroup.TEEN,
    title: 'Блогерство и подкасты',
    hourCost: 4,
    price: 0,
    statChanges: { hunger: 5.8, energy: -7.5, stress: -4, mood: 15, health: -0.4, physical: -0.9 },
    skillChanges: { writing: 2.5, marketing: 2 },
    actionType: 'hobby',
    effect: 'Голод +5.8, Энергия -7.5, Стресс -4, Настроение +15, Здоровье -0.4, Физическая форма -0.9, Писательское мастерство +2.5, Маркетинг +2',
    mood: '🎙️ Делишься мыслями — и находишь единомышленников',
  },
  {
    id: 'hob_calligraphy',
    category: 'hobby',
    ageGroup: AgeGroup.TEEN,
    title: 'Каллиграфия',
    hourCost: 2,
    price: 800,
    statChanges: { hunger: 2.6, energy: -3.5, stress: -6.5, mood: 13, health: -0.2, physical: -0.4 },
    skillChanges: { basicCreativity: 2.5, discipline: 2 },
    actionType: 'hobby',
    effect: 'Голод +2.6, Энергия -3.5, Стресс -6.5, Настроение +13, Здоровье -0.2, Физическая форма -0.4, Креативность +2.5, Дисциплина +2',
    mood: '🖋️ Красота в каждой букве и в каждом движении',
  },
  {
    id: 'hob_street_art',
    category: 'hobby',
    ageGroup: AgeGroup.TEEN,
    title: 'Стрит-арт / граффити',
    hourCost: 3,
    price: 1500,
    statChanges: { hunger: 4.5, energy: -5.5, stress: -3.5, mood: 16.5, health: -0.3, physical: 1.5 },
    skillChanges: { artisticMastery: 3 },
    actionType: 'hobby',
    effect: 'Голод +4.5, Энергия -5.5, Стресс -3.5, Настроение +16.5, Здоровье -0.3, Физическая форма +1.5, Художественное мастерство +3',
    mood: '🎨 Искусство на улицах — это свобода и смелость',
  },
  {
    id: 'hob_digital_music',
    category: 'hobby',
    ageGroup: AgeGroup.TEEN,
    title: 'Создание электронной музыки',
    hourCost: 3,
    price: 0,
    statChanges: { hunger: 4.2, energy: -6, stress: -4.5, mood: 17, health: -0.3, physical: -0.7 },
    skillChanges: { musicalAbility: 3, basicCreativity: 3 },
    actionType: 'hobby',
    effect: 'Голод +4.2, Энергия -6, Стресс -4.5, Настроение +17, Здоровье -0.3, Физическая форма -0.7, Музыкальные способности +3, Креативность +3',
    mood: '🎹 Биты и мелодии рождаются из вдохновения',
  },

  // ───── ДОПОЛНИТЕЛЬНЫЕ ЖИЗНЕННЫЕ ХОББИ ─────
  {
    id: 'hob_modeling',
    category: 'hobby',
    ageGroup: AgeGroup.CHILD,
    title: 'Сборка моделей (самолёты, корабли, танки)',
    hourCost: 3.5,
    price: 950,
    statChanges: { hunger: 4.8, energy: -5.5, stress: -7, mood: 15.5, health: -0.2, physical: -0.6 },
    skillChanges: { patience: 3, handiness: 2.5 },
    actionType: 'hobby',
    effect: 'Голод +4.8, Энергия -5.5, Стресс -7, Настроение +15.5, Здоровье -0.2, Физическая форма -0.6, Терпение +3, Рукоделие +2.5',
    mood: '🛠️ Маленький мир, который ты собираешь своими руками',
  },
  {
    id: 'hob_fishing_hobby',
    category: 'hobby',
    ageGroup: AgeGroup.CHILD,
    title: 'Рыбалка как хобби',
    hourCost: 5,
    price: 600,
    statChanges: { hunger: 6.5, energy: -7.5, stress: -12, mood: 16.5, health: -0.4, physical: -1 },
    skillChanges: { patience: 2.5 },
    actionType: 'hobby',
    effect: 'Голод +6.5, Энергия -7.5, Стресс -12, Настроение +16.5, Здоровье -0.4, Физическая форма -1, Терпение +2.5',
    mood: '🎣 Тишина у воды — лучшее лекарство от городской суеты',
  },
  {
    id: 'hob_chess_hobby',
    category: 'hobby',
    ageGroup: AgeGroup.CHILD,
    title: 'Шахматы и стратегические игры',
    hourCost: 2,
    price: 0,
    statChanges: { hunger: 2.8, energy: -3.5, stress: 1.5, mood: 12.5, health: -0.2, physical: -0.4 },
    skillChanges: { analyticalThinking: 3, discipline: 1.5 },
    actionType: 'hobby',
    effect: 'Голод +2.8, Энергия -3.5, Стресс +1.5, Настроение +12.5, Здоровье -0.2, Физическая форма -0.4, Аналитическое мышление +3, Дисциплина +1.5',
    mood: '♟️ Шахматы — это гимнастика для мозга',
  },
  // ───── ПЕРЕНЕСЕНО ИЗ EDUCATION ─────
  {
    id: 'edu_cooking_masterclass',
    category: 'hobby',
    title: 'Мастер-класс по кулинарии',
    hourCost: 3,
    price: 2500,
    statChanges: { hunger: -13.5, energy: -5.5, stress: -7.5, mood: 15.5, health: 2.8, physical: -0.7 },
    skillChanges: { cooking: 4 },
    actionType: 'hobby',
    effect: 'Голод -13.5, Энергия -5.5, Стресс -7.5, Настроение +15.5, Здоровье +2.8, Физическая форма -0.7, Кулинарное мастерство +4',
    mood: '🍳 Мастер-класс по готовке — вкусно и полезно одновременно',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'edu_photo_practice',
    category: 'hobby',
    title: 'Практика фотографии',
    hourCost: 3,
    price: 300,
    statChanges: { hunger: 4.2, energy: -5.5, stress: -6.5, mood: 12.5, health: -0.3, physical: -0.7 },
    skillChanges: { photography: 4, basicCreativity: 2.5 },
    actionType: 'hobby',
    effect: 'Голод +4.2, Энергия -5.5, Стресс -6.5, Настроение +12.5, Здоровье -0.3, Физическая форма -0.7, Фотография +4, Креативность +2.5',
    mood: '📸 Практика фотографии развивает взгляд и креативность',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'edu_gardening',
    category: 'hobby',
    title: 'Изучение садоводства и ухода за растениями',
    hourCost: 2,
    price: 600,
    statChanges: { hunger: 3.2, energy: -4, stress: -7.5, mood: 10.5, health: 2.5, physical: 3.5 },
    housingComfortDelta: 8,
    skillChanges: { gardening: 4 },
    actionType: 'hobby',
    effect: 'Голод +3.2, Энергия -4, Стресс -7.5, Настроение +10.5, Здоровье +2.5, Физическая форма +3.5, Садоводство +4, Комфорт жилья +8',
    mood: '🌱 Садоводство учит терпению и дарит ощущение жизни',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'edu_acting',
    category: 'hobby',
    title: 'Курс актёрского мастерства',
    hourCost: 4,
    price: 3500,
    statChanges: { hunger: 5.2, energy: -7, stress: -8.5, mood: 14.5, health: -0.5, physical: -1 },
    skillChanges: { acting: 4, charisma: 3 },
    actionType: 'hobby',
    effect: 'Голод +5.2, Энергия -7, Стресс -8.5, Настроение +14.5, Здоровье -0.5, Физическая форма -1, Актёрское мастерство +4, Харизма +3',
    mood: '🎭 Актёрское мастерство раскрывает эмоции и уверенность',
    ageGroup: AgeGroup.TEEN,
  },
]