import type { BalanceAction } from './types'

export const HOME_ACTIONS: BalanceAction[] = [
  {
    id: 'home_good_bed',
    category: 'home',
    title: 'Хорошая кровать',
    hourCost: 1,
    price: 18000,
    statChanges: { energy: 18, health: 8 },
    housingComfortDelta: 10,
    oneTime: true,
    furnitureId: 'good_bed',
    actionType: 'recovery',
    effect: 'Энергия +18, Здоровье +8, Комфорт дома +10',
    mood: '🛏️ Удобная кровать — лучший друг',
  },
  {
    id: 'home_fridge',
    category: 'home',
    title: 'Холодильник',
    hourCost: 1,
    price: 24000,
    statChanges: { hunger: 12 },
    housingComfortDelta: 12,
    oneTime: true,
    furnitureId: 'fridge',
    actionType: 'recovery',
    effect: 'Голод +12, Комфорт дома +12',
    mood: '🧊 Свежие продукты всегда под рукой',
  },
  {
    id: 'home_decor',
    category: 'home',
    title: 'Декор и свет',
    hourCost: 1,
    price: 9500,
    statChanges: { mood: 5 },
    housingComfortDelta: 8,
    oneTime: true,
    furnitureId: 'decor_light',
    actionType: 'recovery',
    effect: 'Настроение +5, Комфорт дома +8',
    mood: '💡 Уютный свет и приятные мелочи',
  },
  {
    id: 'home_move_studio',
    category: 'home',
    title: 'Переезд в студию',
    hourCost: 4,
    price: 80000,
    housingUpgradeLevel: 1,
    actionType: 'recovery',
    effect: 'Переезд в студию',
    mood: '🏠 Своя студия — первый шаг к независимости',
  },
  {
    id: 'home_move_1k',
    category: 'home',
    title: 'Переезд в 1-комнатную',
    hourCost: 6,
    price: 250000,
    housingUpgradeLevel: 2,
    actionType: 'recovery',
    effect: 'Переезд в однокомнатную квартиру',
    mood: '🏢 Просторная однушка — уже настоящий дом',
  },
  {
    id: 'home_move_2k',
    category: 'home',
    title: 'Переезд в 2-комнатную',
    hourCost: 8,
    price: 650000,
    housingUpgradeLevel: 3,
    actionType: 'recovery',
    effect: 'Переезд в двухкомнатную квартиру',
    mood: '🏡 Двушка — место для жизни и гостей',
  },
  {
    id: 'home_move_house',
    category: 'home',
    title: 'Переезд в дом',
    hourCost: 10,
    price: 2500000,
    housingUpgradeLevel: 4,
    actionType: 'recovery',
    effect: 'Переезд в собственный дом',
    mood: '🏘️ Собственный дом — мечта сбылась',
  },
  {
    id: 'home_minor_repair',
    category: 'home',
    title: 'Мелкий ремонт',
    hourCost: 3,
    price: 2000,
    housingComfortDelta: 10,
    skillChanges: { handiness: 1 },
    actionType: 'recovery',
    effect: 'Комфорт дома +10, Ремонт +1',
    mood: '🔧 Починил — стало лучше',
  },
  {
    id: 'home_workspace',
    category: 'home',
    title: 'Обустроить рабочее место',
    hourCost: 2,
    price: 5000,
    housingComfortDelta: 8,
    skillChanges: { professionalism: 1 },
    oneTime: true,
    actionType: 'recovery',
    effect: 'Комфорт дома +8, Профессионализм +1',
    mood: '💻 Рабочее место — залог продуктивности',
  },
  {
    id: 'home_cook_dinner',
    category: 'home',
    title: 'Приготовить ужин дома',
    hourCost: 2,
    price: 600,
    statChanges: { hunger: 30, mood: 6 },
    skillChanges: { cooking: 2 },
    actionType: 'recovery',
    effect: 'Голод +30, Настроение +6, Кулинария +2',
    mood: '🍳 Вкусный ужин своими руками',
  },
  {
    id: 'home_cleaning',
    category: 'home',
    title: 'Заказать клининг',
    hourCost: 1,
    price: 3000,
    statChanges: { stress: -5 },
    housingComfortDelta: 15,
    actionType: 'recovery',
    effect: 'Стресс -5, Комфорт дома +15',
    mood: '✨ Чистота — залог уюта',
  },
  {
    id: 'home_balcony',
    category: 'home',
    title: 'Обустроить балкон / террасу',
    hourCost: 4,
    price: 8000,
    statChanges: { mood: 8 },
    housingComfortDelta: 12,
    skillChanges: { gardening: 1 },
    oneTime: true,
    actionType: 'recovery',
    effect: 'Настроение +8, Комфорт дома +12, Садоводство +1',
    mood: '🌿 Балкон превратился в оазис',
  },
  {
    id: 'home_smart_home',
    category: 'home',
    title: 'Установить систему умного дома',
    hourCost: 3,
    price: 15000,
    housingComfortDelta: 18,
    skillChanges: { technicalLiteracy: 1 },
    oneTime: true,
    requirements: { housingLevel: 2 },
    actionType: 'recovery',
    effect: 'Комфорт дома +18, Техническая грамотность +1',
    mood: '🤖 Умный дом — будущее уже здесь',
  },
  {
    id: 'home_laundry',
    category: 'home',
    title: 'Постирать и убрать вещи',
    hourCost: 2,
    price: 300,
    housingComfortDelta: 8,
    skillChanges: { organization: 1 },
    actionType: 'recovery',
    effect: 'Комфорт дома +8, Организация +1',
    mood: '👕 Чистые вещи — порядок в голове',
  },
  {
    id: 'home_plant',
    category: 'home',
    title: 'Завести комнатное растение',
    hourCost: 1,
    price: 500,
    statChanges: { mood: 3 },
    housingComfortDelta: 5,
    skillChanges: { gardening: 1 },
    actionType: 'recovery',
    effect: 'Настроение +3, Комфорт дома +5, Садоводство +1',
    mood: '🌱 Растение добавило жизни в комнату',
  },
]

