import type { BalanceAction } from './types'

export const HOME_ACTIONS: BalanceAction[] = [
  {
    id: 'home_good_bed',
    category: 'home',
    title: 'Купить хорошую кровать',
    hourCost: 1,
    price: 18000,
    statChanges: { hunger: 1.8, energy: 22, stress: -8, mood: 9, health: 8.5, physical: 1.2 },
    housingComfortDelta: 12,
    oneTime: true,
    furnitureId: 'good_bed',
    actionType: 'recovery',
    effect: 'Голод +1.8, Энергия +22, Стресс -8, Настроение +9, Здоровье +8.5, Физическая форма +1.2, Комфорт жилья +12',
    mood: '🛏️ Качественный сон начинается с хорошей кровати',
  },
  {
    id: 'home_fridge',
    category: 'home',
    title: 'Купить холодильник',
    hourCost: 1,
    price: 24000,
    statChanges: { hunger: -14, energy: 3.5, stress: -2.5, mood: 4.5, health: 1.5, physical: -0.3 },
    housingComfortDelta: 14,
    oneTime: true,
    furnitureId: 'fridge',
    actionType: 'recovery',
    effect: 'Голод -14, Энергия +3.5, Стресс -2.5, Настроение +4.5, Здоровье +1.5, Физическая форма -0.3, Комфорт жилья +14',
    mood: '🧊 Свежие продукты всегда под рукой — это меняет жизнь',
  },
  {
    id: 'home_decor',
    category: 'home',
    title: 'Декор и уютное освещение',
    hourCost: 1,
    price: 9500,
    statChanges: { hunger: 1.2, energy: -1.5, stress: -6.5, mood: 12.5, health: 0.5, physical: -0.2 },
    housingComfortDelta: 10,
    oneTime: true,
    furnitureId: 'decor_light',
    actionType: 'recovery',
    effect: 'Голод +1.2, Энергия -1.5, Стресс -6.5, Настроение +12.5, Здоровье +0.5, Физическая форма -0.2, Комфорт жилья +10',
    mood: '💡 Правильный свет и детали создают настоящий уют',
  },
  {
    id: 'home_move_studio',
    category: 'home',
    title: 'Переезд в студию',
    hourCost: 4,
    price: 80000,
    housingUpgradeLevel: 1,
    actionType: 'recovery',
    effect: 'Переезд в студию — начало самостоятельной жизни',
    mood: '🏠 Своя студия — первый шаг к независимости',
  },
  {
    id: 'home_move_1k',
    category: 'home',
    title: 'Переезд в 1-комнатную квартиру',
    hourCost: 6,
    price: 250000,
    housingUpgradeLevel: 2,
    actionType: 'recovery',
    effect: 'Переезд в однокомнатную квартиру',
    mood: '🏢 Просторная однушка — уже настоящий дом',
  },
  {
    id: 'home_move_2k',
    category: 'home',
    title: 'Переезд в 2-комнатную квартиру',
    hourCost: 8,
    price: 650000,
    housingUpgradeLevel: 3,
    actionType: 'recovery',
    effect: 'Переезд в двухкомнатную квартиру',
    mood: '🏡 Двушка — место для жизни и гостей',
  },
  {
    id: 'home_move_house',
    category: 'home',
    title: 'Переезд в собственный дом',
    hourCost: 10,
    price: 2500000,
    housingUpgradeLevel: 4,
    actionType: 'recovery',
    effect: 'Переезд в собственный дом',
    mood: '🏘️ Собственный дом — мечта многих стала реальностью',
  },
  {
    id: 'home_minor_repair',
    category: 'home',
    title: 'Мелкий ремонт своими руками',
    hourCost: 3,
    price: 2000,
    housingComfortDelta: 12,
    skillChanges: { handiness: 2 },
    actionType: 'recovery',
    effect: 'Голод +4.2, Энергия -5, Стресс -4, Настроение +6, Здоровье +0.8, Физическая форма +2.5, Комфорт жилья +12, Рукоделие +2',
    mood: '🔧 Починил сам — и сразу чувствуешь гордость',
  },
  {
    id: 'home_workspace',
    category: 'home',
    title: 'Обустроить удобное рабочее место',
    hourCost: 2,
    price: 5000,
    housingComfortDelta: 10,
    skillChanges: { professionalism: 2 },
    oneTime: true,
    actionType: 'recovery',
    effect: 'Голод +2.5, Энергия -3, Стресс -5, Настроение +8, Комфорт жилья +10, Профессионализм +2',
    mood: '💻 Хорошее рабочее место сильно повышает продуктивность',
  },
  {
    id: 'home_cook_dinner',
    category: 'home',
    title: 'Приготовить ужин дома',
    hourCost: 2,
    price: 600,
    statChanges: { hunger: -13.5, energy: -4.5, stress: -7, mood: 14.5, health: 2.8, physical: -0.6 },
    skillChanges: { cooking: 2.5 },
    actionType: 'recovery',
    effect: 'Голод -13.5, Энергия -4.5, Стресс -7, Настроение +14.5, Здоровье +2.8, Физическая форма -0.6, Кулинарное мастерство +2.5',
    mood: '🍳 Вкусный домашний ужин — это забота о себе',
  },
  {
    id: 'home_cleaning',
    category: 'home',
    title: 'Заказать профессиональный клининг',
    hourCost: 1,
    price: 3000,
    statChanges: { hunger: 1.5, energy: -2, stress: -12, mood: 7.5, health: 0.5, physical: -0.3 },
    housingComfortDelta: 18,
    actionType: 'recovery',
    effect: 'Голод +1.5, Энергия -2, Стресс -12, Настроение +7.5, Здоровье +0.5, Физическая форма -0.3, Комфорт жилья +18',
    mood: '✨ Когда приходит клининг — в доме сразу становится легче дышать',
  },
  {
    id: 'home_balcony',
    category: 'home',
    title: 'Обустроить балкон или террасу',
    hourCost: 4,
    price: 8000,
    statChanges: { hunger: 4.5, energy: -5.5, stress: -8.5, mood: 16.5, health: 1.5, physical: 2.8 },
    housingComfortDelta: 15,
    skillChanges: { gardening: 2 },
    oneTime: true,
    actionType: 'recovery',
    effect: 'Голод +4.5, Энергия -5.5, Стресс -8.5, Настроение +16.5, Здоровье +1.5, Физическая форма +2.8, Комфорт жилья +15, Садоводство +2',
    mood: '🌿 Балкон превратился в маленький личный оазис',
  },
  {
    id: 'home_smart_home',
    category: 'home',
    title: 'Установить систему умного дома',
    hourCost: 3,
    price: 15000,
    housingComfortDelta: 20,
    skillChanges: { technicalLiteracy: 2 },
    oneTime: true,
    requirements: { housingLevel: 2 },
    actionType: 'recovery',
    effect: 'Голод +3.2, Энергия -3.5, Стресс -6, Настроение +10, Комфорт жилья +20, Техническая грамотность +2',
    mood: '🤖 Умный дом — это когда технологии работают на твой комфорт',
  },
  {
    id: 'home_laundry',
    category: 'home',
    title: 'Постирать, погладить и разобрать вещи',
    hourCost: 2,
    price: 300,
    housingComfortDelta: 9,
    skillChanges: { organization: 2 },
    actionType: 'recovery',
    effect: 'Голод +2.8, Энергия -3.5, Стресс -5.5, Настроение +5, Комфорт жилья +9, Организация +2',
    mood: '👕 Чистое бельё и порядок в шкафу — приятное чувство',
  },
  {
    id: 'home_plant',
    category: 'home',
    title: 'Завести комнатное растение',
    hourCost: 1,
    price: 500,
    statChanges: { hunger: 1.3, energy: -1.8, stress: -5.5, mood: 8.5, health: 1.2, physical: 0.5 },
    housingComfortDelta: 6,
    skillChanges: { gardening: 1.5 },
    actionType: 'recovery',
    effect: 'Голод +1.3, Энергия -1.8, Стресс -5.5, Настроение +8.5, Здоровье +1.2, Физическая форма +0.5, Комфорт жилья +6, Садоводство +1.5',
    mood: '🌱 Одно растение способно оживить всю комнату',
  },

  // ───── ДОПОЛНИТЕЛЬНЫЕ ЖИЗНЕННЫЕ ДЕЙСТВИЯ ДЛЯ ДОМА ─────
  {
    id: 'home_cosy_evening',
    category: 'home',
    title: 'Уютный вечер дома (свечи, плед, чай)',
    hourCost: 2.5,
    price: 250,
    statChanges: { hunger: 2.8, energy: -3, stress: -14, mood: 17.5, health: 1.8, physical: -0.4 },
    housingComfortDelta: 8,
    actionType: 'recovery',
    effect: 'Голод +2.8, Энергия -3, Стресс -14, Настроение +17.5, Здоровье +1.8, Физическая форма -0.4, Комфорт жилья +8',
    mood: '🕯️ Когда дома тепло и уютно — мир снаружи отступает',
  },
  {
    id: 'home_furniture_assembly',
    category: 'home',
    title: 'Сборка новой мебели',
    hourCost: 4,
    price: 0,
    statChanges: { hunger: 5.5, energy: -7.5, stress: -6, mood: 12.5, health: 0.5, physical: 3.5 },
    housingComfortDelta: 14,
    skillChanges: { handiness: 3 },
    actionType: 'recovery',
    effect: 'Голод +5.5, Энергия -7.5, Стресс -6, Настроение +12.5, Здоровье +0.5, Физическая форма +3.5, Комфорт жилья +14, Рукоделие +3',
    mood: '🛠️ Собрал своими руками — теперь это по-настоящему твоё',
  },
  {
    id: 'home_home_cinema',
    category: 'home',
    title: 'Домашний кинотеатр вечером',
    hourCost: 3,
    price: 1200,
    statChanges: { hunger: 4.2, energy: -4.8, stress: -9.5, mood: 18, health: -0.3, physical: -0.8 },
    housingComfortDelta: 7,
    actionType: 'recovery',
    effect: 'Голод +4.2, Энергия -4.8, Стресс -9.5, Настроение +18, Здоровье -0.3, Физическая форма -0.8, Комфорт жилья +7',
    mood: '📺 Большой экран дома — совсем другой уровень просмотра',
  },
]