import { AgeGroup } from './types'
import type { BalanceAction } from './types'
export const SELFDEV_ACTIONS: BalanceAction[] = [
  {
    id: 'self_morning_routine',
    category: 'selfdev',
    title: 'Утренняя рутина (зарядка + планирование дня)',
    hourCost: 1,
    price: 0,
    statChanges: { hunger: 2.2, energy: 9.5, stress: -6.5, mood: 8.5, health: 1.8, physical: 2.5 },
    skillChanges: { discipline: 1.5, organization: 1.5 },
    actionType: 'selfdev',
    effect: 'Голод +2.2, Энергия +9.5, Стресс -6.5, Настроение +8.5, Здоровье +1.8, Физическая форма +2.5, Дисциплина +1.5, Организация +1.5',
    mood: '🌅 Правильное утро задаёт тон всему дню',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'self_evening_routine',
    category: 'selfdev',
    title: 'Вечерняя рутина (рефлексия + подготовка ко сну)',
    hourCost: 1,
    price: 0,
    statChanges: { hunger: 1.8, energy: -2.5, stress: -13.5, mood: 9.5, health: 1.2, physical: -0.3 },
    skillChanges: { wisdom: 1, emotionalIntelligence: 1.5 },
    actionType: 'selfdev',
    effect: 'Голод +1.8, Энергия -2.5, Стресс -13.5, Настроение +9.5, Здоровье +1.2, Физическая форма -0.3, Мудрость +1, Эмоциональный интеллект +1.5',
    mood: '🌙 Вечерний ритуал помогает подвести итоги и успокоиться',
    requirements: { minSkills: { wisdom: 2 } },
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'self_digital_detox',
    category: 'selfdev',
    title: 'Цифровой детокс (день без гаджетов)',
    hourCost: 8,
    price: 0,
    statChanges: { hunger: 9.5, energy: -11, stress: -22, mood: 16.5, health: -0.5, physical: -2.5 },
    skillChanges: { patience: 1.5, emotionalIntelligence: 0.5 },
    actionType: 'selfdev',
    effect: 'Голод +9.5, Энергия -11, Стресс -22, Настроение +16.5, Здоровье -0.5, Физическая форма -2.5, Терпение +1.5, Эмоциональный интеллект +0.5',
    mood: '📵 Отключение от экранов возвращает связь с собой и миром',
    ageGroup: AgeGroup.TEEN,
    requirements: { minSkills: { emotionalIntelligence: 2 } },
  },
  {
    id: 'self_gratitude',
    category: 'selfdev',
    title: 'Практика благодарности (журнал или размышления)',
    hourCost: 0.5,
    price: 0,
    statChanges: { hunger: 0.9, energy: -1.2, stress: -7.5, mood: 12.5, health: 0.8, physical: -0.1 },
    skillChanges: { optimism: 1.5 },
    actionType: 'selfdev',
    effect: 'Голод +0.9, Энергия -1.2, Стресс -7.5, Настроение +12.5, Здоровье +0.8, Физическая форма -0.1, Оптимизм +1.5',
    mood: '🙏 Благодарность — простой способ видеть хорошее в жизни',
    ageGroup: AgeGroup.TODDLER,
  },
  {
    id: 'self_personality_test',
    category: 'selfdev',
    title: 'Пройти глубокий личностный тест',
    hourCost: 1.5,
    price: 500,
    statChanges: { hunger: 2.1, energy: -2.8, stress: -3.5, mood: 7.5, health: 0.5, physical: -0.3 },
    skillChanges: { intuition: 1.5, wisdom: 0.5 },
    actionType: 'selfdev',
    effect: 'Голод +2.1, Энергия -2.8, Стресс -3.5, Настроение +7.5, Здоровье +0.5, Физическая форма -0.3, Интуиция +1.5, Мудрость +0.5',
    mood: '🧠 Лучше понимать себя — первый шаг к росту',
    oneTime: true,
    ageGroup: AgeGroup.TEEN,
    requirements: { requiresItem: 'study_laptop' },
  },
  {
    id: 'self_coaching',
    category: 'selfdev',
    title: 'Сеанс с личным коучем',
    hourCost: 2,
    price: 4000,
    statChanges: { hunger: 2.5, energy: -3.5, stress: -14.5, mood: 13.5, health: 1.2, physical: -0.4 },
    skillChanges: { discipline: 2, optimism: 1 },
    actionType: 'selfdev',
    effect: 'Голод +2.5, Энергия -3.5, Стресс -14.5, Настроение +13.5, Здоровье +1.2, Физическая форма -0.4, Дисциплина +2, Оптимизм +1',
    mood: '🎯 Коуч помогает увидеть путь и двигаться по нему увереннее',
    ageGroup: AgeGroup.ADULT,
    requirements: { minSkills: { discipline: 3 } },
  },

  // ───── ДОПОЛНИТЕЛЬНЫЕ ЖИЗНЕННЫЕ ДЕЙСТВИЯ САМОРАЗВИТИЯ ─────
  {
    id: 'self_journaling',
    category: 'selfdev',
    title: 'Ведение дневника (рефлексия)',
    hourCost: 1,
    price: 0,
    statChanges: { hunger: 1.6, energy: -2.2, stress: -10.5, mood: 11.5, health: 0.8, physical: -0.2 },
    skillChanges: { wisdom: 2, emotionalIntelligence: 1.5 },
    actionType: 'selfdev',
    effect: 'Голод +1.6, Энергия -2.2, Стресс -10.5, Настроение +11.5, Здоровье +0.8, Физическая форма -0.2, Мудрость +2, Эмоциональный интеллект +1.5',
    mood: '📖 Дневник помогает разобраться в мыслях и эмоциях',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'self_reading_nonfiction',
    category: 'selfdev',
    title: 'Чтение развивающей литературы',
    hourCost: 2.5,
    price: 450,
    statChanges: { hunger: 3.5, energy: -4.5, stress: -6.5, mood: 14, health: 0.5, physical: -0.6 },
    skillChanges: { wisdom: 3, discipline: 1 },
    actionType: 'selfdev',
    effect: 'Голод +3.5, Энергия -4.5, Стресс -6.5, Настроение +14, Здоровье +0.5, Физическая форма -0.6, Мудрость +3, Дисциплина +1',
    mood: '📚 Книги, которые действительно меняют мышление',
    ageGroup: AgeGroup.CHILD,
    requirements: { requiresItem: 'book_general' },
  },
  {
    id: 'self_meditation_practice',
    category: 'selfdev',
    title: 'Ежедневная медитация',
    hourCost: 0.8,
    price: 0,
    statChanges: { hunger: 1.1, energy: -1.8, stress: -16.5, mood: 10.5, health: 1.5, physical: -0.2 },
    skillChanges: { meditation: 1.5, emotionalIntelligence: 0.5, patience: 0.5 },
    actionType: 'selfdev',
    effect: 'Голод +1.1, Энергия -1.8, Стресс -16.5, Настроение +10.5, Здоровье +1.5, Физическая форма -0.2, Медитация +1.5, Эмоциональный интеллект +0.5, Терпение +0.5',
    mood: '🧘‍♂️ 10–15 минут тишины творят чудеса с разумом',
    ageGroup: AgeGroup.CHILD,
    requirements: { requiresItem: 'book_meditation_foundations' },
  },
  {
    id: 'self_goal_setting',
    category: 'selfdev',
    title: 'Постановка и разбор целей на квартал',
    hourCost: 2,
    price: 0,
    statChanges: { hunger: 2.8, energy: -3.8, stress: -5.5, mood: 12, health: 0.6, physical: -0.4 },
    skillChanges: { organization: 3, discipline: 2 },
    actionType: 'selfdev',
    effect: 'Голод +2.8, Энергия -3.8, Стресс -5.5, Настроение +12, Здоровье +0.6, Физическая форма -0.4, Организация +3, Дисциплина +2',
    mood: '🎯 Чёткие цели — это карта твоего будущего',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'self_public_speaking',
    category: 'selfdev',
    title: 'Практика публичных выступлений (онлайн)',
    hourCost: 1.5,
    price: 800,
    statChanges: { hunger: 2.4, energy: -4, stress: -7.5, mood: 9.5, health: -0.2, physical: -0.5 },
    skillChanges: { charisma: 2, discipline: 1.5 },
    actionType: 'selfdev',
    effect: 'Голод +2.4, Энергия -4, Стресс -7.5, Настроение +9.5, Здоровье -0.2, Физическая форма -0.5, Харизма +2, Дисциплина +1.5',
    mood: '🗣️ Умение говорить публично открывает множество дверей',
    ageGroup: AgeGroup.TEEN,
    requirements: { requiresItem: 'study_laptop' },
  },
]