import type { BalanceAction } from './types'

export type { BalanceAction }

export const SHOP_ACTIONS: BalanceAction[] = [
  {
    id: 'shop_quick_snack',
    category: 'shop',
    title: 'Быстрый перекус',
    hourCost: 0.5,
    price: 150,
    statChanges: { hunger: 22, energy: 4, stress: -2 },
    actionType: 'shopping',
    effect: 'Голод +22, Энергия +4, Стресс -2',
    mood: '🥪 Быстрый перекус на бегу',
  },
  {
    id: 'shop_full_lunch',
    category: 'shop',
    title: 'Полноценный обед',
    hourCost: 1,
    price: 450,
    statChanges: { hunger: 40, energy: 10, mood: 4 },
    actionType: 'shopping',
    effect: 'Голод +40, Энергия +10, Настроение +4',
    mood: '🍽️ Полноценный обед',
  },
  {
    id: 'shop_groceries_3days',
    category: 'shop',
    title: 'Запас продуктов на 3 дня',
    hourCost: 1.5,
    price: 1200,
    statChanges: { hunger: 18, mood: 4 },
    actionType: 'shopping',
    effect: 'Голод +18, Настроение +4',
    mood: '🛒 Запас продуктов на 3 дня',
  },
  {
    id: 'shop_healthy_food',
    category: 'shop',
    title: 'Здоровое питание (овощи, фрукты)',
    hourCost: 1,
    price: 650,
    statChanges: { hunger: 28, health: 4, physical: 3 },
    actionType: 'shopping',
    effect: 'Голод +28, Здоровье +4, Физическая форма +3',
    mood: '🥗 Здоровое питание',
  },
  {
    id: 'shop_junk_food',
    category: 'shop',
    title: 'Вредная еда (фастфуд, сладости)',
    hourCost: 0.5,
    price: 350,
    statChanges: { hunger: 30, mood: 12, health: -6 },
    actionType: 'shopping',
    effect: 'Голод +30, Настроение +12, Здоровье -6',
    mood: '🍔 Вредная еда',
  },
  {
    id: 'shop_alcohol',
    category: 'shop',
    title: 'Алкоголь и закуски',
    hourCost: 1,
    price: 850,
    statChanges: { mood: 15, stress: -12, health: -5 },
    actionType: 'shopping',
    effect: 'Настроение +15, Стресс -12, Здоровье -5',
    mood: '🍺 Алкоголь и закуски',
  },
  {
    id: 'shop_household_chemicals',
    category: 'shop',
    title: 'Бытовая химия и товары для дома',
    hourCost: 1,
    price: 950,
    housingComfortDelta: 6,
    actionType: 'shopping',
    effect: 'Комфорт жилья +6',
    mood: '🧹 Бытовая химия и товары для дома',
  },
  {
    id: 'shop_clothes',
    category: 'shop',
    title: 'Одежда и обувь',
    hourCost: 2,
    price: 3200,
    statChanges: { mood: 9 },
    housingComfortDelta: 3,
    actionType: 'shopping',
    effect: 'Настроение +9, Комфорт жилья +3',
    mood: '👕 Одежда и обувь',
  },
  {
    id: 'shop_sports_nutrition',
    category: 'shop',
    title: 'Спортивное питание и добавки',
    hourCost: 0.5,
    price: 1450,
    statChanges: { physical: 7, energy: 8 },
    actionType: 'shopping',
    effect: 'Физическая форма +7, Энергия +8',
    mood: '💪 Спортивное питание и добавки',
  },
  {
    id: 'shop_books',
    category: 'shop',
    title: 'Книги и учебные материалы',
    hourCost: 1,
    price: 1100,
    statChanges: { mood: 4 },
    skillChanges: { basicCreativity: 1 },
    actionType: 'shopping',
    effect: 'Настроение +4, Базовая креативность +1',
    mood: '📚 Книги и учебные материалы',
  },
  {
    id: 'shop_medicine',
    category: 'shop',
    title: 'Лекарства и витамины',
    hourCost: 0.5,
    price: 680,
    statChanges: { health: 12, energy: 5 },
    actionType: 'shopping',
    effect: 'Здоровье +12, Энергия +5',
    mood: '💊 Лекарства и витамины',
  },
  {
    id: 'shop_gift_friend',
    category: 'shop',
    title: 'Подарок для друга',
    hourCost: 1,
    price: 2200,
    statChanges: { mood: 7 },
    relationshipDelta: 10,
    actionType: 'shopping',
    effect: 'Отношения +10, Настроение +7',
    mood: '🎁 Подарок для друга',
  },
  {
    id: 'shop_gift_partner',
    category: 'shop',
    title: 'Подарок для партнёра',
    hourCost: 1,
    price: 4500,
    statChanges: { mood: 10 },
    relationshipDelta: 15,
    requirements: { requiresRelationship: true },
    actionType: 'shopping',
    effect: 'Отношения +15, Настроение +10',
    mood: '💝 Подарок для партнёра',
  },
  {
    id: 'shop_big_grocery',
    category: 'shop',
    title: 'Большой продуктовый шопинг',
    hourCost: 2.5,
    price: 4800,
    statChanges: { hunger: 40 },
    housingComfortDelta: 8,
    actionType: 'shopping',
    effect: 'Голод +40, Комфорт жилья +8',
    mood: '🛒 Большой продуктовый шопинг',
  },
  {
    id: 'shop_seeds_plants',
    category: 'shop',
    title: 'Семена и комнатные растения',
    hourCost: 1,
    price: 1650,
    statChanges: { health: 3 },
    housingComfortDelta: 10,
    actionType: 'shopping',
    effect: 'Комфорт жилья +10, Здоровье +3',
    mood: '🌱 Семена и комнатные растения',
  },
  {
    id: 'shop_appliance',
    category: 'shop',
    title: 'Бытовая техника (чайник, микроволновка)',
    hourCost: 1.5,
    price: 6500,
    statChanges: { energy: 5 },
    housingComfortDelta: 15,
    oneTime: true,
    actionType: 'shopping',
    effect: 'Комфорт жилья +15, Энергия +5',
    mood: '🔌 Бытовая техника',
  },
  {
    id: 'shop_cosmetics',
    category: 'shop',
    title: 'Косметика и уход за собой',
    hourCost: 1,
    price: 1800,
    statChanges: { mood: 12, health: 2 },
    actionType: 'shopping',
    effect: 'Настроение +12, Здоровье +2',
    mood: '💄 Косметика и уход за собой',
  },
  {
    id: 'shop_stationery',
    category: 'shop',
    title: 'Канцелярия и органайзеры',
    hourCost: 1,
    price: 950,
    skillChanges: { organization: 2 },
    housingComfortDelta: 4,
    actionType: 'shopping',
    effect: 'Организация +2, Комфорт жилья +4',
    mood: '📝 Канцелярия и органайзеры',
  },
  {
    id: 'shop_games_entertainment',
    category: 'shop',
    title: 'Игры и развлечения (консоль, диски)',
    hourCost: 1.5,
    price: 4200,
    statChanges: { mood: 14 },
    actionType: 'shopping',
    effect: 'Настроение +14',
    mood: '🎮 Игры и развлечения',
  },
  {
    id: 'shop_energy_drinks',
    category: 'shop',
    title: 'Энергетики и кофе',
    hourCost: 0.5,
    price: 280,
    statChanges: { energy: 15, stress: 5, health: -3 },
    actionType: 'shopping',
    effect: 'Энергия +15, Стресс +5, Здоровье -3',
    mood: '☕ Энергетики и кофе',
  },
  {
    id: 'shop_meat_fish',
    category: 'shop',
    title: 'Мясо и рыба (качественные)',
    hourCost: 1,
    price: 1350,
    statChanges: { hunger: 35, health: 5 },
    actionType: 'shopping',
    effect: 'Голод +35, Здоровье +5',
    mood: '🥩 Мясо и рыба',
  },
  {
    id: 'shop_veg_set',
    category: 'shop',
    title: 'Вегетарианский набор',
    hourCost: 1,
    price: 980,
    statChanges: { hunger: 30, health: 6, physical: 2 },
    actionType: 'shopping',
    effect: 'Голод +30, Здоровье +6, Физическая форма +2',
    mood: '🥬 Вегетарианский набор',
  },
  {
    id: 'shop_hygiene',
    category: 'shop',
    title: 'Средства гигиены',
    hourCost: 0.5,
    price: 750,
    statChanges: { health: 3 },
    housingComfortDelta: 5,
    actionType: 'shopping',
    effect: 'Комфорт жилья +5, Здоровье +3',
    mood: '🧼 Средства гигиены',
  },
  {
    id: 'shop_kids_goods',
    category: 'shop',
    title: 'Детские товары',
    hourCost: 1.5,
    price: 3200,
    statChanges: { mood: 6 },
    relationshipDelta: 8,
    requirements: { requiresRelationship: true },
    actionType: 'shopping',
    effect: 'Отношения +8, Настроение +6',
    mood: '🧸 Детские товары',
  },
  {
    id: 'shop_hobby_goods',
    category: 'shop',
    title: 'Товары для хобби (краски, гитара и т.д.)',
    hourCost: 1.5,
    price: 3800,
    statChanges: { mood: 10 },
    skillChanges: { basicCreativity: 2 },
    actionType: 'shopping',
    effect: 'Настроение +10, Базовая креативность +2',
    mood: '🎨 Товары для хобби',
  },
  {
    id: 'shop_seasonal_clothes',
    category: 'shop',
    title: 'Сезонная одежда',
    hourCost: 2,
    price: 5200,
    statChanges: { mood: 11 },
    housingComfortDelta: 4,
    actionType: 'shopping',
    effect: 'Настроение +11, Комфорт жилья +4',
    mood: '🧥 Сезонная одежда',
  },
  {
    id: 'shop_small_furniture',
    category: 'shop',
    title: 'Мебель мелкая (стул, полка)',
    hourCost: 2,
    price: 8500,
    housingComfortDelta: 18,
    actionType: 'shopping',
    effect: 'Комфорт жилья +18',
    mood: '🪑 Мебель мелкая',
  },
  {
    id: 'shop_auto_goods',
    category: 'shop',
    title: 'Автотовары',
    hourCost: 1.5,
    price: 4200,
    statChanges: { stress: -8 },
    actionType: 'shopping',
    effect: 'Стресс -8',
    mood: '🚗 Автотовары',
  },
  {
    id: 'shop_online_subscription',
    category: 'shop',
    title: 'Подписка на онлайн-сервисы',
    hourCost: 0.5,
    price: 799,
    statChanges: { mood: 6 },
    skillChanges: { memory: 1 },
    subscription: { monthlyCost: 799 },
    actionType: 'shopping',
    effect: 'Настроение +6, Память +1',
    mood: '📱 Подписка на онлайн-сервисы',
  },
  {
    id: 'shop_luxury_dinner',
    category: 'shop',
    title: 'Роскошный ужин (доставка)',
    hourCost: 1,
    price: 2500,
    statChanges: { hunger: 45, mood: 18, stress: -8 },
    actionType: 'shopping',
    effect: 'Голод +45, Настроение +18, Стресс -8',
    mood: '🍽️ Роскошный ужин',
  },
  {
    id: 'shop_fitness_membership',
    category: 'shop',
    title: 'Купить абонемент в фитнес-клуб',
    hourCost: 1,
    price: 8000,
    subscription: {
      monthlyCost: 8000,
      effectPerWeek: { statChanges: { physical: 1, health: 2 } },
    },
    grantsItem: 'fitness_membership',
    actionType: 'shopping',
    effect: 'Физическая форма +1/нед, Здоровье +2/нед',
    mood: '🏋️ Абонемент в фитнес-клуб',
  },
  {
    id: 'shop_pet',
    category: 'shop',
    title: 'Купить домашнее животное',
    hourCost: 2,
    price: 15000,
    statChanges: { mood: 10 },
    housingComfortDelta: 8,
    oneTime: true,
    subscription: { monthlyCost: 2000 },
    actionType: 'shopping',
    effect: 'Настроение +10, Комфорт жилья +8',
    mood: '🐾 Купить домашнее животное',
  },
  {
    id: 'shop_healthy_delivery',
    category: 'shop',
    title: 'Заказать здоровую доставку еды на неделю',
    hourCost: 1,
    price: 5500,
    statChanges: { hunger: 35, health: 3 },
    actionType: 'shopping',
    effect: 'Голод +35, Здоровье +3',
    mood: '🥗 Здоровая доставка еды',
  },
  {
    id: 'shop_weekend_trip',
    category: 'shop',
    title: 'Купить путёвку на выходные',
    hourCost: 1.5,
    price: 12000,
    statChanges: { mood: 5 },
    actionType: 'shopping',
    effect: 'Настроение +5, Открывает поездку на выходные',
    mood: '✈️ Путёвка на выходные',
  },
  {
    id: 'shop_music_instrument',
    category: 'shop',
    title: 'Купить музыкальный инструмент',
    hourCost: 1,
    price: 8500,
    statChanges: { mood: 8 },
    skillChanges: { musicalAbility: 1 },
    oneTime: true,
    actionType: 'shopping',
    effect: 'Настроение +8, Музыкальные способности +1',
    mood: '🎸 Музыкальный инструмент',
  },
  {
    id: 'shop_coworking',
    category: 'shop',
    title: 'Арендовать рабочее место в коворкинге',
    hourCost: 1,
    price: 6000,
    subscription: {
      monthlyCost: 6000,
      effectPerWeek: { skillChanges: { professionalism: 1 } },
    },
    actionType: 'shopping',
    effect: 'Профессионализм +1/нед',
    mood: '💻 Аренда рабочего места в коворкинге',
  },
]

