import type { BalanceAction } from './types'
import { AgeGroup } from './types'

export type { BalanceAction }

export const SHOP_ACTIONS: BalanceAction[] = [
  {
    id: 'shop_quick_snack',
    category: 'shop',
    title: 'Быстрый перекус (бутерброд, батончик)',
    hourCost: 0.5,
    price: 150,
    statChanges: { hunger: -22, energy: 4.5, stress: -2.5, mood: 3.5, health: -1.2, physical: -0.3 },
    actionType: 'shopping',
    effect: 'Голод -22, Энергия +4.5, Стресс -2.5, Настроение +3.5, Здоровье -1.2, Физическая форма -0.3',
    mood: '🥪 Быстрый перекус на бегу — спасает, но ненадолго',
    ageGroup: AgeGroup.INFANT,
  },
  {
    id: 'shop_full_lunch',
    category: 'shop',
    title: 'Полноценный обед в кафе',
    hourCost: 1,
    price: 450,
    statChanges: { hunger: -28, energy: 7.5, stress: -4, mood: 8.5, health: 1.2, physical: -0.4 },
    actionType: 'shopping',
    effect: 'Голод -28, Энергия +7.5, Стресс -4, Настроение +8.5, Здоровье +1.2, Физическая форма -0.4',
    mood: '🍽️ Нормальный обед — возвращает силы',
    ageGroup: AgeGroup.INFANT,
  },
  {
    id: 'shop_groceries_3days',
    category: 'shop',
    title: 'Запас продуктов на 3 дня',
    hourCost: 1.5,
    price: 1200,
    statChanges: { hunger: -18, energy: -3, stress: -3.5, mood: 6, health: 0.8, physical: -0.5 },
    actionType: 'shopping',
    effect: 'Голод -18, Энергия -3, Стресс -3.5, Настроение +6, Здоровье +0.8, Физическая форма -0.5, Комфорт жилья +8',
    mood: '🛒 Запас еды на несколько дней — спокойствие в холодильнике',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'shop_healthy_food',
    category: 'shop',
    title: 'Здоровые продукты (овощи, фрукты, крупы)',
    hourCost: 1,
    price: 650,
    statChanges: { hunger: -19, energy: 2.5, stress: -5, mood: 7, health: 5.5, physical: 3.2 },
    actionType: 'shopping',
    effect: 'Голод -19, Энергия +2.5, Стресс -5, Настроение +7, Здоровье +5.5, Физическая форма +3.2',
    mood: '🥗 Овощи и фрукты — инвестиция в самочувствие',
    ageGroup: AgeGroup.CHILD,
  },
  {
    id: 'shop_junk_food',
    category: 'shop',
    title: 'Вредная еда (фастфуд, сладости, чипсы)',
    hourCost: 0.5,
    price: 350,
    statChanges: { hunger: -24, energy: 6, stress: 3.5, mood: 13.5, health: -7.5, physical: -1.5 },
    actionType: 'shopping',
    effect: 'Голод -24, Энергия +6, Стресс +3.5, Настроение +13.5, Здоровье -7.5, Физическая форма -1.5',
    mood: '🍔 Вредная еда — быстрый кайф и последующая расплата',
    ageGroup: AgeGroup.TODDLER,
  },
  {
    id: 'shop_alcohol',
    category: 'shop',
    title: 'Алкоголь и закуски',
    hourCost: 1,
    price: 850,
    statChanges: { hunger: -4, energy: -6.5, stress: -14, mood: 16.5, health: -6.8, physical: -1.2 },
    actionType: 'shopping',
    effect: 'Голод -4, Энергия -6.5, Стресс -14, Настроение +16.5, Здоровье -6.8, Физическая форма -1.2',
    mood: '🍺 Алкоголь расслабляет, но организм платит цену',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'shop_household_chemicals',
    category: 'shop',
    title: 'Бытовая химия и товары для дома',
    hourCost: 1,
    price: 950,
    housingComfortDelta: 8,
    actionType: 'shopping',
    effect: 'Голод +1.5, Энергия -2, Стресс -4, Настроение +3, Комфорт жилья +8',
    mood: '🧹 Чистящие средства — порядок в доме начинается с них',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'shop_clothes',
    category: 'shop',
    title: 'Одежда и обувь',
    hourCost: 2,
    price: 3200,
    statChanges: { hunger: 3.2, energy: -4, stress: -5.5, mood: 13.5, health: -0.3, physical: -0.6 },
    housingComfortDelta: 4,
    actionType: 'shopping',
    effect: 'Голод +3.2, Энергия -4, Стресс -5.5, Настроение +13.5, Здоровье -0.3, Физическая форма -0.6, Комфорт жилья +4',
    mood: '👕 Новая одежда — мгновенный подъём настроения',
    ageGroup: AgeGroup.TODDLER,
  },
  {
    id: 'shop_sports_nutrition',
    category: 'shop',
    title: 'Спортивное питание и добавки',
    hourCost: 0.5,
    price: 1450,
    statChanges: { hunger: 2.8, energy: 8.5, stress: -2, mood: 4.5, health: 3.5, physical: 7.5 },
    actionType: 'shopping',
    effect: 'Голод +2.8, Энергия +8.5, Стресс -2, Настроение +4.5, Здоровье +3.5, Физическая форма +7.5',
    mood: '💪 Протеин и добавки — поддержка для тренировок',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'shop_books',
    category: 'shop',
    title: 'Книги и учебные материалы',
    hourCost: 1,
    price: 1100,
    statChanges: { hunger: 1.8, energy: -2.5, stress: -6, mood: 9.5, health: 0.5, physical: -0.3 },
    skillChanges: { basicCreativity: 2 },
    actionType: 'shopping',
    effect: 'Голод +1.8, Энергия -2.5, Стресс -6, Настроение +9.5, Здоровье +0.5, Физическая форма -0.3, Креативность +2',
    mood: '📚 Новые книги — пища для ума и души',
    ageGroup: AgeGroup.TODDLER,
    grantsItem: 'book_general',
  },
  {
    id: 'shop_time_management_book',
    category: 'shop',
    title: 'Книга «Как управлять временем»',
    hourCost: 0.5,
    price: 950,
    oneTime: true,
    grantsItem: 'book_time_management',
    actionType: 'shopping',
    effect: 'Открывает программу чтения «Как управлять временем» в разделе обучения.',
    mood: '📘 Книга куплена. Можно начинать обучение в библиотеке.',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'shop_meditation_foundations_book',
    category: 'shop',
    title: 'Книга «Основы медитации»',
    hourCost: 0.5,
    price: 690,
    oneTime: true,
    grantsItem: 'book_meditation_foundations',
    actionType: 'shopping',
    effect: 'Открывает пошаговую программу чтения «Основы медитации» в разделе обучения.',
    mood: '📗 Книга куплена. Можно запускать программу из библиотеки.',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'shop_study_laptop',
    category: 'shop',
    title: 'Ноутбук для учёбы',
    hourCost: 1,
    price: 42000,
    oneTime: true,
    grantsItem: 'study_laptop',
    actionType: 'shopping',
    effect: 'Открывает доступ к онлайн-курсам и дистанционным программам обучения.',
    mood: '💻 Ноутбук куплен. Теперь доступны онлайн-курсы.',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'shop_medicine',
    category: 'shop',
    title: 'Лекарства и витамины',
    hourCost: 0.5,
    price: 680,
    statChanges: { hunger: 1.2, energy: 5.5, stress: -3, mood: 3.5, health: 10.5, physical: 0.8 },
    actionType: 'shopping',
    effect: 'Голод +1.2, Энергия +5.5, Стресс -3, Настроение +3.5, Здоровье +10.5, Физическая форма +0.8',
    mood: '💊 Когда нужно — лекарства и витамины выручают',
    ageGroup: AgeGroup.TODDLER,
  },
  {
    id: 'shop_gift_friend',
    category: 'shop',
    title: 'Подарок для друга',
    hourCost: 1,
    price: 2200,
    statChanges: { hunger: 1.5, energy: -2, stress: -4.5, mood: 10.5, health: -0.2, physical: -0.3 },
    relationshipDelta: 12,
    actionType: 'shopping',
    effect: 'Голод +1.5, Энергия -2, Стресс -4.5, Настроение +10.5, Здоровье -0.2, Физическая форма -0.3, Отношения +12',
    mood: '🎁 Приятный подарок укрепляет дружбу',
    ageGroup: AgeGroup.TODDLER,
  },
  {
    id: 'shop_gift_partner',
    category: 'shop',
    title: 'Подарок для партнёра',
    hourCost: 1,
    price: 4500,
    statChanges: { hunger: 1.6, energy: -2.2, stress: -5, mood: 13.5, health: -0.2, physical: -0.3 },
    relationshipDelta: 18,
    requirements: { requiresRelationship: true },
    actionType: 'shopping',
    effect: 'Голод +1.6, Энергия -2.2, Стресс -5, Настроение +13.5, Здоровье -0.2, Физическая форма -0.3, Отношения +18',
    mood: '💝 Внимание к близкому человеку бесценно',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'shop_big_grocery',
    category: 'shop',
    title: 'Большой продуктовый шопинг',
    hourCost: 2.5,
    price: 4800,
    statChanges: { hunger: -25, energy: -5.5, stress: -6, mood: 8.5, health: 1.5, physical: -0.8 },
    housingComfortDelta: 10,
    actionType: 'shopping',
    effect: 'Голод -25, Энергия -5.5, Стресс -6, Настроение +8.5, Здоровье +1.5, Физическая форма -0.8, Комфорт жилья +10',
    mood: '🛒 Полный холодильник — ощущение стабильности',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'shop_seeds_plants',
    category: 'shop',
    title: 'Семена и комнатные растения',
    hourCost: 1,
    price: 1650,
    statChanges: { hunger: 1.4, energy: -2, stress: -7, mood: 9.5, health: 2.8, physical: 1.5 },
    housingComfortDelta: 12,
    actionType: 'shopping',
    effect: 'Голод +1.4, Энергия -2, Стресс -7, Настроение +9.5, Здоровье +2.8, Физическая форма +1.5, Комфорт жилья +12',
    mood: '🌱 Новые растения оживляют пространство',
    ageGroup: AgeGroup.TODDLER,
  },
  {
    id: 'shop_appliance',
    category: 'shop',
    title: 'Бытовая техника (чайник, микроволновка и т.д.)',
    hourCost: 1.5,
    price: 6500,
    statChanges: { hunger: 2.1, energy: 4.5, stress: -5.5, mood: 7.5, health: 0.8, physical: -0.4 },
    housingComfortDelta: 18,
    oneTime: true,
    actionType: 'shopping',
    effect: 'Голод +2.1, Энергия +4.5, Стресс -5.5, Настроение +7.5, Здоровье +0.8, Физическая форма -0.4, Комфорт жилья +18',
    mood: '🔌 Новая техника сильно упрощает быт',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'shop_cosmetics',
    category: 'shop',
    title: 'Косметика и средства ухода за собой',
    hourCost: 1,
    price: 1800,
    statChanges: { hunger: 1.5, energy: -2, stress: -6.5, mood: 14.5, health: 3.2, physical: -0.3 },
    actionType: 'shopping',
    effect: 'Голод +1.5, Энергия -2, Стресс -6.5, Настроение +14.5, Здоровье +3.2, Физическая форма -0.3',
    mood: '💄 Уход за собой — это забота о своём настроении',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'shop_stationery',
    category: 'shop',
    title: 'Канцелярия и органайзеры',
    hourCost: 1,
    price: 950,
    statChanges: { hunger: 1.6, energy: -2.2, stress: -4.5, mood: 6.5, health: 0.4, physical: -0.3 },
    skillChanges: { organization: 2.5 },
    housingComfortDelta: 5,
    actionType: 'shopping',
    effect: 'Голод +1.6, Энергия -2.2, Стресс -4.5, Настроение +6.5, Здоровье +0.4, Физическая форма -0.3, Организация +2.5, Комфорт жилья +5',
    mood: '📝 Красивые органайзеры помогают держать жизнь в порядке',
    ageGroup: AgeGroup.TODDLER,
  },
  {
    id: 'shop_games_entertainment',
    category: 'shop',
    title: 'Игры и развлечения (консоль, диски, настолки)',
    hourCost: 1.5,
    price: 4200,
    statChanges: { hunger: 2.4, energy: -3.5, stress: -8.5, mood: 16.5, health: -0.4, physical: -0.7 },
    actionType: 'shopping',
    effect: 'Голод +2.4, Энергия -3.5, Стресс -8.5, Настроение +16.5, Здоровье -0.4, Физическая форма -0.7',
    mood: '🎮 Новые игры — отличный способ отдохнуть',
    ageGroup: AgeGroup.TODDLER,
  },
  {
    id: 'shop_energy_drinks',
    category: 'shop',
    title: 'Энергетики и кофе',
    hourCost: 0.5,
    price: 280,
    statChanges: { hunger: 1.1, energy: 13.5, stress: 6.5, mood: 4.5, health: -4.5, physical: -0.8 },
    actionType: 'shopping',
    effect: 'Голод +1.1, Энергия +13.5, Стресс +6.5, Настроение +4.5, Здоровье -4.5, Физическая форма -0.8',
    mood: '☕ Энергетик даёт быстрый подъём, но потом откат',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'shop_meat_fish',
    category: 'shop',
    title: 'Качественное мясо и рыба',
    hourCost: 1,
    price: 1350,
    statChanges: { hunger: -26, energy: 3.5, stress: -3, mood: 5.5, health: 6.5, physical: 1.8 },
    actionType: 'shopping',
    effect: 'Голод -26, Энергия +3.5, Стресс -3, Настроение +5.5, Здоровье +6.5, Физическая форма +1.8',
    mood: '🥩 Хорошее мясо и рыба — основа сбалансированного питания',
    ageGroup: AgeGroup.TODDLER,
  },
  {
    id: 'shop_veg_set',
    category: 'shop',
    title: 'Вегетарианский / веганский набор',
    hourCost: 1,
    price: 980,
    statChanges: { hunger: -21, energy: 2.8, stress: -5.5, mood: 6.5, health: 5.8, physical: 2.5 },
    actionType: 'shopping',
    effect: 'Голод -21, Энергия +2.8, Стресс -5.5, Настроение +6.5, Здоровье +5.8, Физическая форма +2.5',
    mood: '🥬 Лёгкие и полезные продукты для хорошего самочувствия',
    ageGroup: AgeGroup.TODDLER,
  },
  {
    id: 'shop_hygiene',
    category: 'shop',
    title: 'Средства личной гигиены',
    hourCost: 0.5,
    price: 750,
    statChanges: { hunger: 0.9, energy: -1.2, stress: -3.5, mood: 5.5, health: 3.5, physical: 0.5 },
    housingComfortDelta: 6,
    actionType: 'shopping',
    effect: 'Голод +0.9, Энергия -1.2, Стресс -3.5, Настроение +5.5, Здоровье +3.5, Физическая форма +0.5, Комфорт жилья +6',
    mood: '🧼 Свежий душ и чистота — базовый комфорт',
    ageGroup: AgeGroup.TODDLER,
  },
  {
    id: 'shop_kids_goods',
    category: 'shop',
    title: 'Детские товары',
    hourCost: 1.5,
    price: 3200,
    statChanges: { hunger: 2.1, energy: -2.8, stress: -4.5, mood: 9.5, health: -0.2, physical: -0.4 },
    relationshipDelta: 10,
    requirements: { requiresRelationship: true },
    actionType: 'shopping',
    effect: 'Голод +2.1, Энергия -2.8, Стресс -4.5, Настроение +9.5, Здоровье -0.2, Физическая форма -0.4, Отношения +10',
    mood: '🧸 Забота о детях всегда возвращается теплом',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'shop_hobby_goods',
    category: 'shop',
    title: 'Товары для хобби (краски, гитара, пряжа и т.д.)',
    hourCost: 1.5,
    price: 3800,
    statChanges: { hunger: 2.4, energy: -3.5, stress: -7, mood: 13.5, health: -0.3, physical: -0.6 },
    skillChanges: { basicCreativity: 2.5 },
    actionType: 'shopping',
    effect: 'Голод +2.4, Энергия -3.5, Стресс -7, Настроение +13.5, Здоровье -0.3, Физическая форма -0.6, Креативность +2.5',
    mood: '🎨 Новые материалы для хобби — вдохновение гарантировано',
    ageGroup: AgeGroup.TODDLER,
  },
  {
    id: 'shop_seasonal_clothes',
    category: 'shop',
    title: 'Сезонная одежда',
    hourCost: 2,
    price: 5200,
    statChanges: { hunger: 3, energy: -4, stress: -6, mood: 14, health: -0.3, physical: -0.5 },
    housingComfortDelta: 5,
    actionType: 'shopping',
    effect: 'Голод +3, Энергия -4, Стресс -6, Настроение +14, Здоровье -0.3, Физическая форма -0.5, Комфорт жилья +5',
    mood: '🧥 Одежда по сезону — комфорт и уверенность',
    ageGroup: AgeGroup.TODDLER,
  },
  {
    id: 'shop_small_furniture',
    category: 'shop',
    title: 'Мелкая мебель (стул, полка, тумба)',
    hourCost: 2,
    price: 8500,
    housingComfortDelta: 20,
    actionType: 'shopping',
    effect: 'Голод +3.5, Энергия -5, Стресс -5.5, Настроение +8, Комфорт жилья +20',
    mood: '🪑 Новая полка или стул — и комната преображается',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'shop_auto_goods',
    category: 'shop',
    title: 'Автотовары и аксессуары',
    hourCost: 1.5,
    price: 4200,
    statChanges: { hunger: 2.2, energy: -3, stress: -9.5, mood: 5.5, health: -0.3, physical: -0.5 },
    actionType: 'shopping',
    effect: 'Голод +2.2, Энергия -3, Стресс -9.5, Настроение +5.5, Здоровье -0.3, Физическая форма -0.5',
    mood: '🚗 Уход за машиной приносит спокойствие',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'shop_online_subscription',
    category: 'shop',
    title: 'Подписка на онлайн-сервисы (кино, музыка, книги)',
    hourCost: 0.5,
    price: 799,
    statChanges: { hunger: 1, energy: -1.5, stress: -5, mood: 8.5, health: -0.1, physical: -0.2 },
    skillChanges: { basicCreativity: 1 },
    subscription: { monthlyCost: 799 },
    actionType: 'shopping',
    effect: 'Голод +1, Энергия -1.5, Стресс -5, Настроение +8.5, Здоровье -0.1, Физическая форма -0.2, Креативность +1',
    mood: '📱 Подписка — бесконечный доступ к контенту',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'shop_luxury_dinner',
    category: 'shop',
    title: 'Роскошный ужин с доставкой',
    hourCost: 1,
    price: 2500,
    statChanges: { hunger: -32, energy: -2.5, stress: -9.5, mood: 19.5, health: 1.5, physical: -0.5 },
    actionType: 'shopping',
    effect: 'Голод -32, Энергия -2.5, Стресс -9.5, Настроение +19.5, Здоровье +1.5, Физическая форма -0.5',
    mood: '🍽️ Роскошный ужин дома — маленькая радость жизни',
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'shop_fitness_membership',
    category: 'shop',
    title: 'Абонемент в фитнес-клуб',
    hourCost: 1,
    price: 8000,
    subscription: {
      monthlyCost: 8000,
      effectPerWeek: { statChanges: { hunger: 2.5, energy: -2, stress: -8, mood: 5, health: 3, physical: 6 } },
    },
    grantsItem: 'fitness_membership',
    actionType: 'shopping',
    effect: 'Абонемент открывает регулярные тренировки (Физическая форма и Здоровье растут еженедельно)',
    mood: '🏋️ Абонемент — обязательство заботиться о себе',
    ageGroup: AgeGroup.TEEN,
  },
  {
    id: 'shop_pet',
    category: 'shop',
    title: 'Купить домашнее животное',
    hourCost: 2,
    price: 15000,
    statChanges: { hunger: 3.5, energy: -4, stress: -12, mood: 18, health: 2.5, physical: 1.5 },
    housingComfortDelta: 10,
    oneTime: true,
    subscription: { monthlyCost: 2000 },
    actionType: 'shopping',
    effect: 'Голод +3.5, Энергия -4, Стресс -12, Настроение +18, Здоровье +2.5, Физическая форма +1.5, Комфорт жилья +10',
    mood: '🐾 Питомец приносит любовь и ответственность',
    requirements: { housingLevel: 1 }, // рекомендуется добавить требование к жилью
    ageGroup: AgeGroup.ADULT,
  },
  {
    id: 'shop_healthy_delivery',
    category: 'shop',
    title: 'Здоровая доставка еды на неделю',
    hourCost: 1,
    price: 5500,
    statChanges: { hunger: -35, energy: 4.5, stress: -7, mood: 8.5, health: 6.5, physical: 2.5 },
    actionType: 'shopping',
    effect: 'Голод -35, Энергия +4.5, Стресс -7, Настроение +8.5, Здоровье +6.5, Физическая форма +2.5',
    mood: '🥗 Готовая здоровая еда на неделю — экономия времени и сил',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'shop_weekend_trip',
    category: 'shop',
    title: 'Путёвка на выходные',
    hourCost: 1.5,
    price: 12000,
    statChanges: { hunger: 3.2, energy: -3.5, stress: -14, mood: 17.5, health: 2.8, physical: 3.5 },
    actionType: 'shopping',
    effect: 'Голод +3.2, Энергия -3.5, Стресс -14, Настроение +17.5, Здоровье +2.8, Физическая форма +3.5',
    mood: '✈️ Короткая поездка на выходные — отличная перезагрузка',
    ageGroup: AgeGroup.YOUNG,
  },
  {
    id: 'shop_music_instrument',
    category: 'shop',
    title: 'Музыкальный инструмент',
    hourCost: 1,
    price: 8500,
    statChanges: { hunger: 2.1, energy: -3, stress: -7.5, mood: 12.5, health: -0.2, physical: -0.4 },
    skillChanges: { musicalAbility: 2 },
    oneTime: true,
    actionType: 'shopping',
    effect: 'Голод +2.1, Энергия -3, Стресс -7.5, Настроение +12.5, Здоровье -0.2, Физическая форма -0.4, Музыкальные способности +2',
    mood: '🎸 Новый инструмент — начало нового хобби',
    ageGroup: AgeGroup.TODDLER,
  },
  {
    id: 'shop_coworking',
    category: 'shop',
    title: 'Аренда места в коворкинге',
    hourCost: 1,
    price: 6000,
    subscription: {
      monthlyCost: 6000,
      effectPerWeek: { skillChanges: { professionalism: 2 } },
    },
    actionType: 'shopping',
    effect: 'Профессионализм +2 в неделю при регулярном посещении',
    mood: '💻 Коворкинг — атмосфера и дисциплина для работы',
    ageGroup: AgeGroup.YOUNG,
  },
]