import type { BalanceAction } from './types'

export const SOCIAL_ACTIONS: BalanceAction[] = [
  {
    id: 'social_call_parents',
    category: 'social',
    title: 'Позвонить родителям',
    hourCost: 0.5,
    price: 0,
    statChanges: { mood: 7, stress: -5 },
    relationshipDelta: 5,
    actionType: 'social',
    effect: 'Настроение +7, Стресс -5, Отношения +5',
    mood: '📞 Тёплый разговор с мамой и папой',
  },
  {
    id: 'social_meet_friend',
    category: 'social',
    title: 'Встретиться с другом',
    hourCost: 3,
    price: 600,
    statChanges: { mood: 16, stress: -10 },
    relationshipDelta: 9,
    actionType: 'social',
    effect: 'Настроение +16, Стресс -10, Отношения +9',
    mood: '🤝 Отличная встреча с близким другом',
  },
  {
    id: 'social_date',
    category: 'social',
    title: 'Свидание',
    hourCost: 4,
    price: 2200,
    statChanges: { mood: 20, stress: -8 },
    relationshipDelta: 15,
    actionType: 'social',
    effect: 'Настроение +20, Стресс -8, Отношения +15',
    mood: '❤️ Прекрасное свидание',
    requirements: { requiresRelationship: true },
  },
  {
    id: 'social_family_dinner',
    category: 'social',
    title: 'Семейный ужин',
    hourCost: 3,
    price: 1200,
    statChanges: { mood: 15 },
    relationshipDelta: 12,
    actionType: 'social',
    effect: 'Настроение +15, Отношения +12',
    mood: '🍽️ Тёплый семейный ужин',
    requirements: { requiresRelationship: true },
  },
  {
    id: 'social_party',
    category: 'social',
    title: 'Вечеринка с друзьями',
    hourCost: 5,
    price: 2500,
    statChanges: { mood: 18, stress: -12 },
    relationshipDelta: 10,
    actionType: 'social',
    effect: 'Настроение +18, Стресс -12, Отношения +10',
    mood: '🎉 Весёлая вечеринка в отличной компании',
  },
  {
    id: 'social_help_friend',
    category: 'social',
    title: 'Помочь другу',
    hourCost: 2,
    price: 0,
    statChanges: { mood: 8 },
    relationshipDelta: 14,
    actionType: 'social',
    effect: 'Настроение +8, Отношения +14',
    mood: '🤝 Радость от помощи близкому другу',
  },
  {
    id: 'social_online_chat',
    category: 'social',
    title: 'Онлайн-общение',
    hourCost: 1,
    price: 0,
    statChanges: { mood: 5 },
    relationshipDelta: 6,
    actionType: 'social',
    effect: 'Настроение +5, Отношения +6',
    mood: '💬 Приятная переписка с друзьями',
  },
  {
    id: 'social_joint_sport',
    category: 'social',
    title: 'Совместный спорт',
    hourCost: 2.5,
    price: 800,
    statChanges: { physical: 5, mood: 12 },
    relationshipDelta: 10,
    actionType: 'social',
    effect: 'Физическая форма +5, Настроение +12, Отношения +10',
    mood: '🏋️ Совместная тренировка — в два раза веселее',
  },
  {
    id: 'social_bar_colleagues',
    category: 'social',
    title: 'Поход в бар с коллегами',
    hourCost: 4,
    price: 1800,
    statChanges: { stress: -10, mood: 10 },
    relationshipDelta: 8,
    actionType: 'social',
    effect: 'Стресс -10, Настроение +10, Отношения +8',
    mood: '🍺 Посиделки в баре после работы',
  },
  {
    id: 'social_visit_relatives',
    category: 'social',
    title: 'Посетить родственников',
    hourCost: 5,
    price: 500,
    statChanges: { mood: 9 },
    relationshipDelta: 13,
    actionType: 'social',
    effect: 'Настроение +9, Отношения +13',
    mood: '🏠 Визит к родственникам — тепло и уют',
  },
  {
    id: 'social_romantic_dinner',
    category: 'social',
    title: 'Романтический ужин дома',
    hourCost: 3,
    price: 1800,
    statChanges: { mood: 16 },
    relationshipDelta: 18,
    actionType: 'social',
    effect: 'Настроение +16, Отношения +18',
    mood: '🕯️ Романтический ужин при свечах',
    requirements: { requiresRelationship: true },
  },
  {
    id: 'social_joint_hobby',
    category: 'social',
    title: 'Совместное хобби',
    hourCost: 4,
    price: 1200,
    relationshipDelta: 12,
    actionType: 'social',
    effect: 'Отношения +12, Базовая креативность +2',
    mood: '🎨 Совместное творчество сближает',
    skillChanges: { basicCreativity: 2 },
  },
  {
    id: 'social_argument',
    category: 'social',
    title: 'Ссора и примирение',
    hourCost: 2,
    price: 0,
    statChanges: { mood: 5 },
    relationshipDelta: -10,
    actionType: 'social',
    effect: 'Настроение +5, Отношения -10 (или +15 при успешном примирении)',
    mood: '😤 Ссора… но возможно примирение',
  },
  {
    id: 'social_birthday_gift',
    category: 'social',
    title: 'Подарок на день рождения',
    hourCost: 1,
    price: 3000,
    relationshipDelta: 16,
    actionType: 'social',
    effect: 'Отношения +16',
    mood: '🎁 Родной человек обрадовался подарку',
  },
  {
    id: 'social_help_elderly',
    category: 'social',
    title: 'Помощь пожилым родственникам',
    hourCost: 3,
    price: 0,
    relationshipDelta: 14,
    actionType: 'social',
    effect: 'Отношения +14, Мудрость +1',
    mood: '👴 Помощь старшим — дело важное',
    skillChanges: { wisdom: 1 },
  },
  {
    id: 'social_networking',
    category: 'social',
    title: 'Нетворкинг (деловая встреча)',
    hourCost: 3,
    price: 1500,
    relationshipDelta: 10,
    actionType: 'social',
    effect: 'Отношения +10, Харизма +1',
    mood: '💼 Полезные деловые знакомства',
    skillChanges: { charisma: 1 },
  },
  {
    id: 'social_weekend_trip',
    category: 'social',
    title: 'Совместная поездка на выходные',
    hourCost: 12,
    price: 8500,
    statChanges: { mood: 20 },
    relationshipDelta: 25,
    actionType: 'social',
    effect: 'Настроение +20, Отношения +25',
    mood: '🚗 Незабываемая поездка на выходные',
    requirements: { requiresRelationship: true },
  },
  {
    id: 'social_online_game',
    category: 'social',
    title: 'Онлайн-игра с друзьями',
    hourCost: 3,
    price: 0,
    statChanges: { mood: 10 },
    relationshipDelta: 8,
    actionType: 'social',
    effect: 'Настроение +10, Отношения +8',
    mood: '🎮 Весёлая онлайн-игра в компании друзей',
  },
  {
    id: 'social_volunteer',
    category: 'social',
    title: 'Волонтёрство',
    hourCost: 4,
    price: 0,
    statChanges: { mood: 12 },
    relationshipDelta: 0,
    actionType: 'social',
    effect: 'Настроение +12, Эмпатия +2',
    mood: '🤲 Помощь другим приносит радость',
    skillChanges: { empathy: 2 },
  },
  {
    id: 'social_family_holiday',
    category: 'social',
    title: 'Семейный праздник',
    hourCost: 6,
    price: 4000,
    statChanges: { mood: 15 },
    relationshipDelta: 18,
    actionType: 'social',
    effect: 'Настроение +15, Отношения +18',
    mood: '🎄 Семейный праздник — тепло и радость',
    requirements: { requiresRelationship: true },
  },
  {
    id: 'social_invite_friends_dinner',
    category: 'social',
    title: 'Пригласить друзей на ужин домой',
    hourCost: 4,
    price: 2500,
    statChanges: { mood: 16 },
    relationshipDelta: 14,
    actionType: 'social',
    effect: 'Настроение +16, Отношения +14, Кулинария +1',
    mood: '🍽️ Уютный ужин с друзьями у себя дома',
    skillChanges: { cooking: 1 },
  },
  {
    id: 'social_meet_new',
    category: 'social',
    title: 'Познакомиться с новым человеком',
    hourCost: 2,
    price: 500,
    statChanges: { mood: 5 },
    relationshipDelta: 6,
    actionType: 'social',
    effect: 'Настроение +5, Отношения +6, Харизма +1',
    mood: '👋 Интересное новое знакомство',
    skillChanges: { charisma: 1 },
  },
  {
    id: 'social_write_old_friend',
    category: 'social',
    title: 'Написать старому другу',
    hourCost: 0.5,
    price: 0,
    statChanges: { mood: 4 },
    relationshipDelta: 4,
    actionType: 'social',
    effect: 'Настроение +4, Отношения +4',
    mood: '✉️ Ностальгическая переписка со старым другом',
  },
  {
    id: 'social_blind_date',
    category: 'social',
    title: 'Свидание вслепую',
    hourCost: 3,
    price: 1500,
    statChanges: { mood: 10 },
    relationshipDelta: 8,
    actionType: 'social',
    effect: 'Настроение +10, Отношения +8 (возможен случайный исход)',
    mood: '🎲 Свидание вслепую — сюрприз',
  },
  {
    id: 'social_quest_team',
    category: 'social',
    title: 'Поучаствовать в квесте / тимбилдинге',
    hourCost: 4,
    price: 2000,
    statChanges: { mood: 14 },
    relationshipDelta: 12,
    actionType: 'social',
    effect: 'Настроение +14, Отношения +12, Лидерство +1',
    mood: '🧩 Командный квест — азарт и сплочение',
    skillChanges: { leadership: 1 },
  },
  {
    id: 'social_open_event',
    category: 'social',
    title: 'Посетить открытое мероприятие',
    hourCost: 3,
    price: 1000,
    statChanges: { mood: 10 },
    relationshipDelta: 8,
    actionType: 'social',
    effect: 'Настроение +10, Отношения +8',
    mood: '🎤 Интересное открытое мероприятие',
  },
  {
    id: 'social_nature_trip',
    category: 'social',
    title: 'Совместный выезд на природу',
    hourCost: 8,
    price: 3500,
    statChanges: { mood: 18, stress: -14 },
    relationshipDelta: 20,
    actionType: 'social',
    effect: 'Настроение +18, Стресс -14, Отношения +20',
    mood: '🌲 Выезд на природу в отличной компании',
  },
  {
    id: 'social_marathon',
    category: 'social',
    title: 'Поучаствовать в марафоне / забеге',
    hourCost: 6,
    price: 1500,
    statChanges: { physical: 6, health: 3 },
    relationshipDelta: 8,
    actionType: 'social',
    effect: 'Физическая форма +6, Здоровье +3, Отношения +8',
    mood: '🏃 Марафон — испытание и триумф',
  },
]

