import { AgeGroup } from './types'
import type { BalanceAction } from './types'
export const SOCIAL_ACTIONS: BalanceAction[] = [
  {
    id: 'social_call_parents',
    category: 'social',
    title: 'Позвонить родителям',
    hourCost: 0.5,
    price: 0,
    statChanges: { hunger: 0.9, energy: -1.2, stress: -8.5, mood: 10.5, health: 0.5, physical: -0.2 },
    relationshipDelta: 7,
    actionType: 'social',
    ageGroup: AgeGroup.INFANT,
    effect: 'Голод +0.9, Энергия -1.2, Стресс -8.5, Настроение +10.5, Здоровье +0.5, Физическая форма -0.2, Отношения +7',
    mood: '📞 Тёплый разговор с родителями всегда согревает душу',
  },
  {
    id: 'social_meet_friend',
    category: 'social',
    title: 'Встретиться с другом',
    hourCost: 3,
    price: 600,
    statChanges: { hunger: 4.2, energy: -5.5, stress: -11.5, mood: 18.5, health: -0.4, physical: -0.7 },
    relationshipDelta: 11,
    actionType: 'social',
    ageGroup: AgeGroup.TODDLER,
    effect: 'Голод +4.2, Энергия -5.5, Стресс -11.5, Настроение +18.5, Здоровье -0.4, Физическая форма -0.7, Отношения +11',
    mood: '🤝 Встреча с близким другом — лучшее лекарство от одиночества',
  },
  {
    id: 'social_date',
    category: 'social',
    title: 'Свидание',
    hourCost: 4,
    price: 2200,
    statChanges: { hunger: 5.5, energy: -7, stress: -9.5, mood: 22.5, health: -0.5, physical: -1 },
    relationshipDelta: 17,
    actionType: 'social',
    ageGroup: AgeGroup.TEEN,
    effect: 'Голод +5.5, Энергия -7, Стресс -9.5, Настроение +22.5, Здоровье -0.5, Физическая форма -1, Отношения +17',
    mood: '❤️ Свидание — волнение и приятные эмоции',
    requirements: { requiresRelationship: true },
  },
  {
    id: 'social_family_dinner',
    category: 'social',
    title: 'Семейный ужин',
    hourCost: 3,
    price: 1200,
    statChanges: { hunger: -12.5, energy: -4.5, stress: -6.5, mood: 16.5, health: 1.5, physical: -0.6 },
    relationshipDelta: 14,
    actionType: 'social',
    ageGroup: AgeGroup.TODDLER,
    effect: 'Голод -12.5, Энергия -4.5, Стресс -6.5, Настроение +16.5, Здоровье +1.5, Физическая форма -0.6, Отношения +14',
    mood: '🍽️ Тёплый семейный ужин — ощущение дома',
  },
  {
    id: 'social_party',
    category: 'social',
    title: 'Вечеринка с друзьями',
    hourCost: 5,
    price: 2500,
    statChanges: { hunger: 6.5, energy: -9.5, stress: -12.5, mood: 21.5, health: -0.8, physical: -1.5 },
    relationshipDelta: 13,
    actionType: 'social',
    ageGroup: AgeGroup.YOUNG,
    effect: 'Голод +6.5, Энергия -9.5, Стресс -12.5, Настроение +21.5, Здоровье -0.8, Физическая форма -1.5, Отношения +13',
    mood: '🎉 Весёлая вечеринка — заряд положительных эмоций',
  },
  {
    id: 'social_help_friend',
    category: 'social',
    title: 'Помочь другу в деле',
    hourCost: 2,
    price: 0,
    statChanges: { hunger: 3.2, energy: -4.5, stress: -7.5, mood: 11.5, health: 0.8, physical: 1.5 },
    relationshipDelta: 16,
    actionType: 'social',
    ageGroup: AgeGroup.TODDLER,
    effect: 'Голод +3.2, Энергия -4.5, Стресс -7.5, Настроение +11.5, Здоровье +0.8, Физическая форма +1.5, Отношения +16',
    mood: '🤝 Помочь другу — это всегда ценно и приятно',
  },
  {
    id: 'social_online_chat',
    category: 'social',
    title: 'Онлайн-общение с друзьями',
    hourCost: 1,
    price: 0,
    statChanges: { hunger: 1.4, energy: -2, stress: -5.5, mood: 8.5, health: -0.1, physical: -0.3 },
    relationshipDelta: 7,
    actionType: 'social',
    ageGroup: AgeGroup.CHILD,
    effect: 'Голод +1.4, Энергия -2, Стресс -5.5, Настроение +8.5, Здоровье -0.1, Физическая форма -0.3, Отношения +7',
    mood: '💬 Приятная переписка или звонок — быстро поднимает настроение',
  },
  {
    id: 'social_joint_sport',
    category: 'social',
    title: 'Совместная тренировка или спорт',
    hourCost: 2.5,
    price: 800,
    statChanges: { hunger: 4.8, energy: -5.5, stress: -9.5, mood: 14.5, health: 1.5, physical: 6.5 },
    relationshipDelta: 11,
    actionType: 'social',
    ageGroup: AgeGroup.CHILD,
    effect: 'Голод +4.8, Энергия -5.5, Стресс -9.5, Настроение +14.5, Здоровье +1.5, Физическая форма +6.5, Отношения +11',
    mood: '🏋️ Тренироваться вместе гораздо веселее и эффективнее',
  },
  {
    id: 'social_bar_colleagues',
    category: 'social',
    title: 'Поход в бар с коллегами',
    hourCost: 4,
    price: 1800,
    statChanges: { hunger: 5.2, energy: -7.5, stress: -10.5, mood: 13.5, health: -1.2, physical: -1.1 },
    relationshipDelta: 9,
    actionType: 'social',
    ageGroup: AgeGroup.ADULT,
    effect: 'Голод +5.2, Энергия -7.5, Стресс -10.5, Настроение +13.5, Здоровье -1.2, Физическая форма -1.1, Отношения +9',
    mood: '🍺 Расслабленные посиделки после работы с коллегами',
  },
  {
    id: 'social_visit_relatives',
    category: 'social',
    title: 'Посетить родственников',
    hourCost: 5,
    price: 500,
    statChanges: { hunger: 6.5, energy: -8, stress: -7.5, mood: 13.5, health: -0.6, physical: -1.2 },
    relationshipDelta: 15,
    actionType: 'social',
    ageGroup: AgeGroup.TODDLER,
    effect: 'Голод +6.5, Энергия -8, Стресс -7.5, Настроение +13.5, Здоровье -0.6, Физическая форма -1.2, Отношения +15',
    mood: '🏠 Визит к родным — тепло, еда и семейные истории',
  },
  {
    id: 'social_romantic_dinner',
    category: 'social',
    title: 'Романтический ужин дома',
    hourCost: 3,
    price: 1800,
    statChanges: { hunger: -11.5, energy: -4.5, stress: -8.5, mood: 19.5, health: 1.2, physical: -0.6 },
    relationshipDelta: 20,
    actionType: 'social',
    ageGroup: AgeGroup.YOUNG,
    effect: 'Голод -11.5, Энергия -4.5, Стресс -8.5, Настроение +19.5, Здоровье +1.2, Физическая форма -0.6, Отношения +20',
    mood: '🕯️ Романтический ужин при свечах сближает как ничто другое',
    requirements: { requiresRelationship: true },
  },
  {
    id: 'social_joint_hobby',
    category: 'social',
    title: 'Совместное хобби или творчество',
    hourCost: 4,
    price: 1200,
    statChanges: { hunger: 5.2, energy: -6.5, stress: -9, mood: 16.5, health: -0.4, physical: -0.9 },
    relationshipDelta: 14,
    skillChanges: { basicCreativity: 2.5 },
    actionType: 'social',
    ageGroup: AgeGroup.CHILD,
    effect: 'Голод +5.2, Энергия -6.5, Стресс -9, Настроение +16.5, Здоровье -0.4, Физическая форма -0.9, Отношения +14, Креативность +2.5',
    mood: '🎨 Делать что-то вместе — один из лучших способов сблизиться',
  },
  {
    id: 'social_argument',
    category: 'social',
    title: 'Ссора и последующее примирение',
    hourCost: 2,
    price: 0,
    statChanges: { hunger: 2.8, energy: -4, stress: 12.5, mood: -8.5, health: -0.8, physical: -0.6 },
    relationshipDelta: -12,
    actionType: 'social',
    ageGroup: AgeGroup.TODDLER,
    effect: 'Голод +2.8, Энергия -4, Стресс +12.5, Настроение -8.5, Здоровье -0.8, Физическая форма -0.6, Отношения -12',
    mood: '😤 Ссора — неприятно, но примирение может всё исправить',
  },
  {
    id: 'social_birthday_gift',
    category: 'social',
    title: 'Подарок на день рождения',
    hourCost: 1,
    price: 3000,
    statChanges: { hunger: 1.5, energy: -2, stress: -5.5, mood: 11.5, health: -0.1, physical: -0.3 },
    relationshipDelta: 18,
    actionType: 'social',
    ageGroup: AgeGroup.TODDLER,
    effect: 'Голод +1.5, Энергия -2, Стресс -5.5, Настроение +11.5, Здоровье -0.1, Физическая форма -0.3, Отношения +18',
    mood: '🎁 Когда человек искренне радуется твоему подарку — это бесценно',
  },
  {
    id: 'social_help_elderly',
    category: 'social',
    title: 'Помочь пожилым родственникам',
    hourCost: 3,
    price: 0,
    statChanges: { hunger: 4.2, energy: -5.5, stress: -6.5, mood: 12.5, health: 1.8, physical: 2.2 },
    relationshipDelta: 16,
    skillChanges: { wisdom: 2 },
    actionType: 'social',
    ageGroup: AgeGroup.CHILD,
    effect: 'Голод +4.2, Энергия -5.5, Стресс -6.5, Настроение +12.5, Здоровье +1.8, Физическая форма +2.2, Отношения +16, Мудрость +2',
    mood: '👴 Забота о старших наполняет жизнь смыслом',
  },
  {
    id: 'social_networking',
    category: 'social',
    title: 'Нетворкинг и деловые знакомства',
    hourCost: 3,
    price: 1500,
    statChanges: { hunger: 3.5, energy: -4.5, stress: -5.5, mood: 10.5, health: -0.3, physical: -0.6 },
    relationshipDelta: 11,
    skillChanges: { charisma: 2 },
    actionType: 'social',
    ageGroup: AgeGroup.YOUNG,
    effect: 'Голод +3.5, Энергия -4.5, Стресс -5.5, Настроение +10.5, Здоровье -0.3, Физическая форма -0.6, Отношения +11, Харизма +2',
    mood: '💼 Полезные знакомства могут открыть новые возможности',
  },
  {
    id: 'social_weekend_trip',
    category: 'social',
    title: 'Совместная поездка на выходные',
    hourCost: 12,
    price: 8500,
    statChanges: { hunger: 11.5, energy: -14.5, stress: -16.5, mood: 24.5, health: 1.5, physical: 4.5 },
    relationshipDelta: 28,
    actionType: 'social',
    ageGroup: AgeGroup.YOUNG,
    effect: 'Голод +11.5, Энергия -14.5, Стресс -16.5, Настроение +24.5, Здоровье +1.5, Физическая форма +4.5, Отношения +28',
    mood: '🚗 Совместная поездка — один из лучших способов укрепить отношения',
    requirements: { requiresRelationship: true },
  },
  {
    id: 'social_online_game',
    category: 'social',
    title: 'Онлайн-игра с друзьями',
    hourCost: 3,
    price: 0,
    statChanges: { hunger: 4.2, energy: -5, stress: -6.5, mood: 13.5, health: -0.4, physical: -0.8 },
    relationshipDelta: 9,
    actionType: 'social',
    ageGroup: AgeGroup.CHILD,
    effect: 'Голод +4.2, Энергия -5, Стресс -6.5, Настроение +13.5, Здоровье -0.4, Физическая форма -0.8, Отношения +9',
    mood: '🎮 Играть вместе онлайн — смех и азарт гарантированы',
  },
  {
    id: 'social_volunteer',
    category: 'social',
    title: 'Волонтёрская помощь',
    hourCost: 4,
    price: 0,
    statChanges: { hunger: 5.5, energy: -7, stress: -10.5, mood: 14.5, health: 2.5, physical: 2.8 },
    relationshipDelta: 6,
    skillChanges: { empathy: 3, wisdom: 1 },
    actionType: 'social',
    ageGroup: AgeGroup.CHILD,
    effect: 'Голод +5.5, Энергия -7, Стресс -10.5, Настроение +14.5, Здоровье +2.5, Физическая форма +2.8, Отношения +6, Эмпатия +3, Мудрость +1',
    mood: '🤲 Помогать другим — один из самых приятных видов саморазвития',
  },
  {
    id: 'social_family_holiday',
    category: 'social',
    title: 'Семейный праздник',
    hourCost: 6,
    price: 4000,
    statChanges: { hunger: -13.5, energy: -8.5, stress: -8.5, mood: 19.5, health: 1.2, physical: -1.4 },
    relationshipDelta: 20,
    actionType: 'social',
    ageGroup: AgeGroup.TODDLER,
    effect: 'Голод -13.5, Энергия -8.5, Стресс -8.5, Настроение +19.5, Здоровье +1.2, Физическая форма -1.4, Отношения +20',
    mood: '🎄 Семейный праздник — ощущение единства и тепла',
  },
  {
    id: 'social_invite_friends_dinner',
    category: 'social',
    title: 'Пригласить друзей на ужин домой',
    hourCost: 4,
    price: 2500,
    statChanges: { hunger: -14.5, energy: -6.5, stress: -7.5, mood: 18.5, health: 1.5, physical: -0.9 },
    relationshipDelta: 16,
    skillChanges: { cooking: 2 },
    actionType: 'social',
    ageGroup: AgeGroup.CHILD,
    effect: 'Голод -14.5, Энергия -6.5, Стресс -7.5, Настроение +18.5, Здоровье +1.5, Физическая форма -0.9, Отношения +16, Кулинарное мастерство +2',
    mood: '🍽️ Когда друзья приходят к тебе домой — это особенная атмосфера',
  },
  {
    id: 'social_meet_new',
    category: 'social',
    title: 'Познакомиться с новым человеком',
    hourCost: 2,
    price: 500,
    statChanges: { hunger: 2.8, energy: -3.5, stress: -4.5, mood: 9.5, health: -0.2, physical: -0.5 },
    relationshipDelta: 8,
    skillChanges: { charisma: 2 },
    actionType: 'social',
    ageGroup: AgeGroup.CHILD,
    effect: 'Голод +2.8, Энергия -3.5, Стресс -4.5, Настроение +9.5, Здоровье -0.2, Физическая форма -0.5, Отношения +8, Харизма +2',
    mood: '👋 Новое знакомство — всегда небольшой риск и интерес',
  },
  {
    id: 'social_write_old_friend',
    category: 'social',
    title: 'Написать старому другу',
    hourCost: 0.5,
    price: 0,
    statChanges: { hunger: 0.8, energy: -1.2, stress: -4.5, mood: 7.5, health: 0.3, physical: -0.2 },
    relationshipDelta: 6,
    actionType: 'social',
    ageGroup: AgeGroup.TODDLER,
    effect: 'Голод +0.8, Энергия -1.2, Стресс -4.5, Настроение +7.5, Здоровье +0.3, Физическая форма -0.2, Отношения +6',
    mood: '✉️ Ностальгия и тёплые воспоминания от общения со старым другом',
  },
  {
    id: 'social_blind_date',
    category: 'social',
    title: 'Свидание вслепую',
    hourCost: 3,
    price: 1500,
    statChanges: { hunger: 4.2, energy: -5.5, stress: -6.5, mood: 12.5, health: -0.4, physical: -0.8 },
    relationshipDelta: 9,
    actionType: 'social',
    ageGroup: AgeGroup.ADULT,
    effect: 'Голод +4.2, Энергия -5.5, Стресс -6.5, Настроение +12.5, Здоровье -0.4, Физическая форма -0.8, Отношения +9',
    mood: '🎲 Свидание вслепую — всегда лотерея эмоций',
  },
  {
    id: 'social_quest_team',
    category: 'social',
    title: 'Квест или тимбилдинг в команде',
    hourCost: 4,
    price: 2000,
    statChanges: { hunger: 5.5, energy: -7, stress: -10.5, mood: 17.5, health: -0.5, physical: -1 },
    relationshipDelta: 14,
    skillChanges: { leadership: 2 },
    actionType: 'social',
    ageGroup: AgeGroup.CHILD,
    effect: 'Голод +5.5, Энергия -7, Стресс -10.5, Настроение +17.5, Здоровье -0.5, Физическая форма -1, Отношения +14, Лидерство +2',
    mood: '🧩 Командный квест — азарт, смех и сплочение',
  },
  {
    id: 'social_open_event',
    category: 'social',
    title: 'Посетить открытое мероприятие',
    hourCost: 3,
    price: 1000,
    statChanges: { hunger: 4.2, energy: -5.5, stress: -7, mood: 13.5, health: -0.4, physical: -0.8 },
    relationshipDelta: 9,
    actionType: 'social',
    ageGroup: AgeGroup.CHILD,
    effect: 'Голод +4.2, Энергия -5.5, Стресс -7, Настроение +13.5, Здоровье -0.4, Физическая форма -0.8, Отношения +9',
    mood: '🎤 Открытые мероприятия — отличный способ провести время и познакомиться',
  },
  {
    id: 'social_nature_trip',
    category: 'social',
    title: 'Совместный выезд на природу',
    hourCost: 8,
    price: 3500,
    statChanges: { hunger: 10.5, energy: -12.5, stress: -15.5, mood: 23.5, health: 2.5, physical: 5.5 },
    relationshipDelta: 24,
    actionType: 'social',
    ageGroup: AgeGroup.CHILD,
    effect: 'Голод +10.5, Энергия -12.5, Стресс -15.5, Настроение +23.5, Здоровье +2.5, Физическая форма +5.5, Отношения +24',
    mood: '🌲 Выезд на природу в хорошей компании — незабываемо',
  },
  {
    id: 'social_marathon',
    category: 'social',
    title: 'Участвовать в марафоне или забеге',
    hourCost: 6,
    price: 1500,
    statChanges: { hunger: 9.5, energy: -11.5, stress: -8.5, mood: 12.5, health: 4.5, physical: 8.5 },
    relationshipDelta: 10,
    actionType: 'social',
    ageGroup: AgeGroup.CHILD,
    effect: 'Голод +9.5, Энергия -11.5, Стресс -8.5, Настроение +12.5, Здоровье +4.5, Физическая форма +8.5, Отношения +10',
    mood: '🏃 Совместный забег — испытание, которое объединяет',
  },
]