export const STAT_LABELS_RU: Record<string, string> = {
  hunger: 'Голод',
  energy: 'Энергия',
  stress: 'Стресс',
  mood: 'Настроение',
  health: 'Здоровье',
  physical: 'Форма',
}

export const STAT_KEY_ORDER = ['hunger', 'energy', 'stress', 'mood', 'health', 'physical']

export const METRIC_LABELS: Record<string, string> = {
  hunger: 'Голод',
  energy: 'Энергия',
  stress: 'Стресс',
  mood: 'Настроение',
  health: 'Здоровье',
  physical: 'Физическая форма',
  memory: 'Память',
  concentration: 'Концентрация',
  creativity: 'Креативность',
  organization: 'Организация',
  professionalism: 'Профессионализм',
}

export const EFFECT_LABELS: Record<string, string> = {
  energyDrainMultiplier: 'Расход энергии',
  stressGainMultiplier: 'Рост стресса',
  workEfficiencyMultiplier: 'Эффективность работы',
  learningSpeedMultiplier: 'Скорость обучения',
  positiveEventChance: 'Шанс позитивных событий',
  positiveEventChanceBonus: 'Шанс позитивных событий',
  relationshipGainMultiplier: 'Рост отношений',
  salaryMultiplier: 'Зарплата',
  shopPriceMultiplier: 'Цены в магазине',
  investmentReturnMultiplier: 'Доходность инвестиций',
  passiveIncomeBonus: 'Пассивный доход',
  hungerDrainMultiplier: 'Расход сытости',
  healthDecayMultiplier: 'Ухудшение здоровья',
  recoveryEfficiency: 'Эффективность восстановления',
  negativeEventPenaltyReduction: 'Снижение штрафов от негатива',
  jobChangeCostReduction: 'Стоимость смены работы',
  workPeriodBonusChance: 'Шанс бонуса на работе',
  maxEnergyBonus: 'Максимум энергии',
  stressResistanceFromWork: 'Стресс от работы',
  moodRecoveryMultiplier: 'Восстановление настроения',
  negativeEventMitigation: 'Сила негативных событий',
  homeComfortMultiplier: 'Комфорт дома',
  dailyExpenseMultiplier: 'Повседневные расходы',
  hobbyIncomeMultiplier: 'Доход от хобби',
  stressEventImmunity: 'Иммунитет к стрессовым событиям',
  lowMoodPenaltyReduction: 'Штрафы от низкого настроения',
  autoRecoveryWeekly: 'Автовосстановление в неделю',
  randomSkillGainChance: 'Шанс случайного роста навыка',
  relationshipQualityMultiplier: 'Качество отношений',
  friendHelpChance: 'Помощь друзей',
  educationDecayReduction: 'Потеря прогресса обучения',
  relearningBonus: 'Бонус повторного обучения',
  promotionChance: 'Шанс повышения',
  teamEventBonus: 'Бонус командных событий',
  jobSalaryOnHire: 'Стартовая зарплата',
  investmentRiskReduction: 'Риск инвестиций',
  jobSpecificSalaryBonus: 'Зарплата по специализации',
  stressGainFromWork: 'Стресс от работы',
  overtimeImmunity: 'Иммунитет к переработкам',
  learningTechSpeed: 'Скорость техобучения',
  homeTechBonus: 'Бонус от техники дома',
  foodRecoveryMultiplier: 'Восстановление от еды',
  taxReduction: 'Снижение налогов',
  subordinateEfficiency: 'Эффективность сотрудников',
  salesSuccess: 'Успешность продаж',
  overallEfficiency: 'Общая эффективность',
  legalPenaltyReduction: 'Юридические штрафы',
  healthRecoveryMultiplier: 'Восстановление здоровья',
  agingSpeedMultiplier: 'Скорость старения',
  routinePenaltyReduction: 'Штрафы от рутины',
  allRecoveryMultiplier: 'Общее восстановление',
  negativeEventChance: 'Частота негативных событий',
  missedActionPenalty: 'Штрафы за пропуски',
  agingPenaltyReduction: 'Возрастные штрафы',
  giftQualityBonus: 'Качество подарков',
  eventChoiceHint: 'Подсказки в событиях',
  agePenaltyAfter50: 'Штрафы после 50 лет',
  lifeExpectancyBonus: 'Ожидаемая продолжительность жизни',
  socialEventBonus: 'Социальные события',
  healthBonus: 'Бонус к здоровью',
  repairCostReduction: 'Стоимость ремонта',
  energyRecoveryFromActivity: 'Восстановление энергии',
  publicEventSuccess: 'Успех публичных выступлений',
  furnitureComfortBonus: 'Комфорт от мебели',
  homeFoodRecovery: 'Домашняя еда',
}

export const EXPENSE_LABELS_RU: Record<string, string> = {
  housing: 'Жильё',
  food: 'Еда',
  transport: 'Транспорт',
  leisure: 'Досуг',
  education: 'Образование',
}
