export const CAREER_JOBS = [
  {
    id: 'office_employee',
    name: 'Офисный сотрудник',
    schedule: '5/2',
    level: 1,
    salaryPerHour: 1050,
    salaryPerDay: 8400,
    salaryPerWeek: 42000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 0,
    minEducationRank: -1,
    minAge: 16,
  },
  {
    id: 'project_coordinator',
    name: 'Координатор проектов',
    schedule: '5/2',
    level: 2,
    salaryPerHour: 1225,
    salaryPerDay: 9800,
    salaryPerWeek: 49000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 3,
    minEducationRank: -1,
    minAge: 18,
  },
  {
    id: 'business_analyst',
    name: 'Бизнес-аналитик',
    schedule: '5/2',
    level: 3,
    salaryPerHour: 1600,
    salaryPerDay: 12800,
    salaryPerWeek: 64000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 4,
    minEducationRank: 0,
    minAge: 21,
  },
  {
    id: 'team_lead',
    name: 'Тимлид',
    schedule: '5/2',
    level: 4,
    salaryPerHour: 1950,
    salaryPerDay: 15600,
    salaryPerWeek: 78000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 6,
    minEducationRank: 1,
    minAge: 25,
  },
  {
    id: 'shift_worker',
    name: 'Сменный рабочий',
    schedule: '2/2',
    level: 1,
    salaryPerHour: 1200,
    salaryPerDay: 14400,
    salaryPerWeek: 28800,
    requiredHoursPerWeek: 24,
    minProfessionalism: 0,
    minEducationRank: -1,
    minAge: 18,
  },
  {
    id: 'senior_manager',
    name: 'Старший менеджер',
    schedule: '6/1',
    level: 5,
    salaryPerHour: 2200,
    salaryPerDay: 15400,
    salaryPerWeek: 92400,
    requiredHoursPerWeek: 42,
    minProfessionalism: 8,
    minEducationRank: 1,
    minAge: 28,
  },
];
