import type { CareerJob } from '@/domain/balance/types'

/**
 * Реалистичные карьеры для РФ (2024)
 *
 * level: 1-10 (карьерный уровень)
 * minEducationRank: -1 = любое, 0 = Среднее, 1 = Высшее, 2 = Бакалавриат, 3 = Магистратура, 4 = MBA
 * salaryPerHour: почасовая ставка (руб)
 * salaryPerDay = salaryPerHour * 8 (или другое количество часов)
 * salaryPerWeek = salaryPerDay * 5 (или нужное количество дней)
 */
export const CAREER_JOBS: CareerJob[] = [
  // === IT / Технологии ===
  {
    id: 'it_junior',
    name: 'Junior-разработчик',
    schedule: '5/2',
    level: 1,
    salaryPerHour: 625,      // ~50к/мес
    salaryPerDay: 5000,
    salaryPerWeek: 25000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 0,
    minEducationRank: -1,
    minAge: 18,
    description: 'Начинающий программист. Изучение технологий и помощь в простых задачах.',
  },
  {
    id: 'it_middle',
    name: 'Middle-разработчик',
    schedule: '5/2',
    level: 3,
    salaryPerHour: 1250,     // ~100к/мес
    salaryPerDay: 10000,
    salaryPerWeek: 50000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 4,
    minEducationRank: 0,
    minAge: 22,
    description: 'Самостоятельная разработка, код-ревью, помощь младшим.',
  },
  {
    id: 'it_senior',
    name: 'Senior-разработчик',
    schedule: '5/2',
    level: 5,
    salaryPerHour: 2250,     // ~180к/мес
    salaryPerDay: 18000,
    salaryPerWeek: 90000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 7,
    minEducationRank: 1,
    minAge: 26,
    description: 'Архитектурные решения, сложные задачи, наставничество.',
  },
  {
    id: 'it_techlead',
    name: 'Технический лидер',
    schedule: '5/2',
    level: 7,
    salaryPerHour: 3125,     // ~250к/мес
    salaryPerDay: 25000,
    salaryPerWeek: 125000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 9,
    minEducationRank: 1,
    minAge: 30,
    description: 'Техническое руководство, архитектура, стратегия развития.',
  },
  {
    id: 'qa_engineer',
    name: 'QA-инженер (тестировщик)',
    schedule: '5/2',
    level: 2,
    salaryPerHour: 750,      // ~60к/мес
    salaryPerDay: 6000,
    salaryPerWeek: 30000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 2,
    minEducationRank: -1,
    minAge: 19,
    description: 'Функциональное и автоматическое тестирование ПО.',
  },
  {
    id: 'devops',
    name: 'DevOps-инженер',
    schedule: '5/2',
    level: 4,
    salaryPerHour: 1750,     // ~140к/мес
    salaryPerDay: 14000,
    salaryPerWeek: 70000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 6,
    minEducationRank: 0,
    minAge: 24,
    description: 'Инфраструктура, CI/CD, мониторинг, безопасность.',
  },
  {
    id: 'system_admin',
    name: 'Системный администратор',
    schedule: '5/2',
    level: 3,
    salaryPerHour: 1000,     // ~80к/мес
    salaryPerDay: 8000,
    salaryPerWeek: 40000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 4,
    minEducationRank: 0,
    minAge: 21,
    description: 'Поддержка серверов, сетей, рабочих станций.',
  },
  {
    id: 'data_analyst',
    name: 'Аналитик данных',
    schedule: '5/2',
    level: 4,
    salaryPerHour: 1500,     // ~120к/мес
    salaryPerDay: 12000,
    salaryPerWeek: 60000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 5,
    minEducationRank: 1,
    minAge: 23,
    description: 'SQL, Python, аналитика, дашборды, прогнозы.',
  },

  // === Медицина ===
  {
    id: 'med_nurse',
    name: 'Медсестра / Медбрат',
    schedule: '2/2',
    level: 1,
    salaryPerHour: 625,      // ~50к/мес
    salaryPerDay: 5000,
    salaryPerWeek: 25000,
    requiredHoursPerWeek: 36,
    minProfessionalism: 0,
    minEducationRank: 0,    // Среднее медицинское
    minAge: 19,
    description: 'Уход за пациентами, процедуры, назначения врача.',
  },
  {
    id: 'med_doctor_poly',
    name: 'Врач-терапевт (поликлиника)',
    schedule: '5/2',
    level: 3,
    salaryPerHour: 1250,     // ~100к/мес
    salaryPerDay: 10000,
    salaryPerWeek: 50000,
    requiredHoursPerWeek: 39,
    minProfessionalism: 4,
    minEducationRank: 1,
    minAge: 25,
    description: 'Приём пациентов, диагностика, назначение лечения.',
  },
  {
    id: 'med_doctor_spec',
    name: 'Врач-специалист',
    schedule: '5/2',
    level: 5,
    salaryPerHour: 2000,     // ~160к/мес
    salaryPerDay: 16000,
    salaryPerWeek: 80000,
    requiredHoursPerWeek: 39,
    minProfessionalism: 7,
    minEducationRank: 1,
    minAge: 28,
    description: 'Узкая специализация: хирург, кардиолог, невролог и др.',
  },
  {
    id: 'med_head',
    name: 'Заведующий отделением',
    schedule: '5/2',
    level: 7,
    salaryPerHour: 2750,     // ~220к/мес
    salaryPerDay: 22000,
    salaryPerWeek: 110000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 9,
    minEducationRank: 2,
    minAge: 35,
    description: 'Руководство отделением, администрация, коммерция.',
  },

  // === Образование ===
  {
    id: 'edu_school',
    name: 'Учитель школы',
    schedule: '5/2',
    level: 2,
    salaryPerHour: 500,      // ~40к/мес
    salaryPerDay: 4000,
    salaryPerWeek: 20000,
    requiredHoursPerWeek: 36,
    minProfessionalism: 2,
    minEducationRank: 1,
    minAge: 22,
    description: 'Преподавание, проверка работ, воспитательная работа.',
  },
  {
    id: 'edu_school_senior',
    name: 'Старший учитель',
    schedule: '5/2',
    level: 4,
    salaryPerHour: 688,      // ~55к/мес
    salaryPerDay: 5500,
    salaryPerWeek: 27500,
    requiredHoursPerWeek: 36,
    minProfessionalism: 5,
    minEducationRank: 1,
    minAge: 28,
    description: 'Опытный педагог, методическая работа.',
  },
  {
    id: 'edu_university',
    name: 'Преподаватель вуза',
    schedule: '5/2',
    level: 4,
    salaryPerHour: 875,      // ~70к/мес
    salaryPerDay: 7000,
    salaryPerWeek: 35000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 5,
    minEducationRank: 2,
    minAge: 27,
    description: 'Лекции, научная работа, руководство студентами.',
  },
  {
    id: 'edu_professor',
    name: 'Профессор',
    schedule: '5/2',
    level: 8,
    salaryPerHour: 1875,     // ~150к/мес
    salaryPerDay: 15000,
    salaryPerWeek: 75000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 10,
    minEducationRank: 3,
    minAge: 40,
    description: 'Научная деятельность, руководство кафедрой.',
  },

  // === Производство ===
  {
    id: 'prod_worker',
    name: 'Рабочий на производстве',
    schedule: '2/2',
    level: 1,
    salaryPerHour: 563,      // ~45к/мес (по 12ч)
    salaryPerDay: 6750,
    salaryPerWeek: 27000,
    requiredHoursPerWeek: 36,
    minProfessionalism: 0,
    minEducationRank: -1,
    minAge: 18,
    description: 'Конвейер, станки, упаковка. Физический труд.',
  },
  {
    id: 'prod_operator',
    name: 'Оператор станков с ЧПУ',
    schedule: '2/2',
    level: 3,
    salaryPerHour: 938,      // ~75к/мес
    salaryPerDay: 11250,
    salaryPerWeek: 45000,
    requiredHoursPerWeek: 36,
    minProfessionalism: 3,
    minEducationRank: 0,
    minAge: 21,
    description: 'Настройка и обслуживание станков с программным управлением.',
  },
  {
    id: 'prod_master',
    name: 'Мастер цеха',
    schedule: '5/2',
    level: 4,
    salaryPerHour: 1250,     // ~100к/мес
    salaryPerDay: 10000,
    salaryPerWeek: 50000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 5,
    minEducationRank: 1,
    minAge: 25,
    description: 'Руководство бригадой, контроль качества.',
  },
  {
    id: 'prod_engineer',
    name: 'Инженер-технолог',
    schedule: '5/2',
    level: 4,
    salaryPerHour: 1125,     // ~90к/мес
    salaryPerDay: 9000,
    salaryPerWeek: 45000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 5,
    minEducationRank: 1,
    minAge: 24,
    description: 'Разработка технологических процессов, документация.',
  },
  {
    id: 'prod_director',
    name: 'Директор завода',
    schedule: '5/2',
    level: 9,
    salaryPerHour: 3750,     // ~300к/мес
    salaryPerDay: 30000,
    salaryPerWeek: 150000,
    requiredHoursPerWeek: 45,
    minProfessionalism: 10,
    minEducationRank: 3,
    minAge: 40,
    description: 'Полное управление производством, стратегия.',
  },

  // === Торговля / Retail ===
  {
    id: 'retail_seller',
    name: 'Продавец-консультант',
    schedule: '2/2',
    level: 1,
    salaryPerHour: 500,      // ~40к/мес + премии
    salaryPerDay: 4000,
    salaryPerWeek: 16000,
    requiredHoursPerWeek: 30,
    minProfessionalism: 0,
    minEducationRank: -1,
    minAge: 18,
    description: 'Консультации, выкладка, касса.',
  },
  {
    id: 'retail_shift',
    name: 'Старший продавец',
    schedule: '2/2',
    level: 2,
    salaryPerHour: 625,      // ~50к/мес
    salaryPerDay: 5000,
    salaryPerWeek: 20000,
    requiredHoursPerWeek: 30,
    minProfessionalism: 2,
    minEducationRank: -1,
    minAge: 21,
    description: 'Заказ товара, инкассация, управление сменой.',
  },
  {
    id: 'retail_manager',
    name: 'Менеджер магазина',
    schedule: '5/2',
    level: 4,
    salaryPerHour: 1000,     // ~80к/мес
    salaryPerDay: 8000,
    salaryPerWeek: 40000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 5,
    minEducationRank: 0,
    minAge: 25,
    description: 'Управление магазином, персонал, финансы.',
  },
  {
    id: 'retail_director',
    name: 'Директор торговой сети',
    schedule: '5/2',
    level: 8,
    salaryPerHour: 3125,     // ~250к/мес
    salaryPerDay: 25000,
    salaryPerWeek: 125000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 9,
    minEducationRank: 2,
    minAge: 35,
    description: 'Управление сетью магазинов, стратегия.',
  },

  // === Офисная работа ===
  {
    id: 'office_specialist',
    name: 'Офис-менеджер',
    schedule: '5/2',
    level: 1,
    salaryPerHour: 563,      // ~45к/мес
    salaryPerDay: 4500,
    salaryPerWeek: 22500,
    requiredHoursPerWeek: 40,
    minProfessionalism: 0,
    minEducationRank: -1,
    minAge: 18,
    description: 'Документооборот, приём звонков, встреча гостей.',
  },
  {
    id: 'hr_specialist',
    name: 'HR-специалист',
    schedule: '5/2',
    level: 3,
    salaryPerHour: 875,      // ~70к/мес
    salaryPerDay: 7000,
    salaryPerWeek: 35000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 4,
    minEducationRank: 1,
    minAge: 23,
    description: 'Подбор персонала, адаптация, кадры.',
  },
  {
    id: 'accountant',
    name: 'Бухгалтер',
    schedule: '5/2',
    level: 3,
    salaryPerHour: 1000,     // ~80к/мес
    salaryPerDay: 8000,
    salaryPerWeek: 40000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 4,
    minEducationRank: 1,
    minAge: 23,
    description: 'Учёт, отчётность, налоги.',
  },
  {
    id: 'finance_manager',
    name: 'Финансовый менеджер',
    schedule: '5/2',
    level: 5,
    salaryPerHour: 1500,     // ~120к/мес
    salaryPerDay: 12000,
    salaryPerWeek: 60000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 6,
    minEducationRank: 1,
    minAge: 27,
    description: 'Бюджетирование, финансовый анализ.',
  },

  // === Строительство ===
  {
    id: 'build_worker',
    name: 'Строительный рабочий',
    schedule: '6/1',
    level: 1,
    salaryPerHour: 625,      // ~50к/мес
    salaryPerDay: 5000,
    salaryPerWeek: 30000,
    requiredHoursPerWeek: 48,
    minProfessionalism: 0,
    minEducationRank: -1,
    minAge: 18,
    description: 'О��ще��троительные работы, физический труд.',
  },
  {
    id: 'build_brigadir',
    name: 'Бригадир',
    schedule: '6/1',
    level: 3,
    salaryPerHour: 875,      // ~70к/мес
    salaryPerDay: 7000,
    salaryPerWeek: 42000,
    requiredHoursPerWeek: 48,
    minProfessionalism: 3,
    minEducationRank: 0,
    minAge: 25,
    description: 'Руководство бригадой рабочих.',
  },
  {
    id: 'build_pro',
    name: 'Прораб',
    schedule: '5/2',
    level: 4,
    salaryPerHour: 1250,     // ~100к/мес
    salaryPerDay: 10000,
    salaryPerWeek: 50000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 5,
    minEducationRank: 1,
    minAge: 28,
    description: 'Контроль стройки, сроков, качества.',
  },
  {
    id: 'build_engineer',
    name: 'Инженер-строитель',
    schedule: '5/2',
    level: 5,
    salaryPerHour: 1500,     // ~120к/мес
    salaryPerDay: 12000,
    salaryPerWeek: 60000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 6,
    minEducationRank: 1,
    minAge: 27,
    description: 'Проектирование, надзор, документация.',
  },

  // === Транспорт / Логистика ===
  {
    id: 'driver_cargo',
    name: 'Водитель-экспедитор',
    schedule: '6/1',
    level: 1,
    salaryPerHour: 688,      // ~55к/мес
    salaryPerDay: 5500,
    salaryPerWeek: 33000,
    requiredHoursPerWeek: 48,
    minProfessionalism: 1,
    minEducationRank: -1,
    minAge: 21,
    description: 'Доставка грузов по городу/региону.',
  },
  {
    id: 'driver_ap',
    name: 'Водитель автобуса / маршрутки',
    schedule: '2/2',
    level: 2,
    salaryPerHour: 750,      // ~60к/мес
    salaryPerDay: 6000,
    salaryPerWeek: 30000,
    requiredHoursPerWeek: 36,
    minProfessionalism: 3,
    minEducationRank: -1,
    minAge: 25,
    description: 'Перевозка пассажиров, ответственность за людей.',
  },
  {
    id: 'logistics_manager',
    name: 'Менеджер по логистике',
    schedule: '5/2',
    level: 4,
    salaryPerHour: 1125,     // ~90к/мес
    salaryPerDay: 9000,
    salaryPerWeek: 45000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 5,
    minEducationRank: 1,
    minAge: 26,
    description: 'Организация перевозок, оптимизация маршрутов.',
  },

  // === Общепит / HoReCa ===
  {
    id: 'cook_line',
    name: 'Повар на линии',
    schedule: '2/2',
    level: 1,
    salaryPerHour: 563,      // ~45к/мес
    salaryPerDay: 4500,
    salaryPerWeek: 22500,
    requiredHoursPerWeek: 36,
    minProfessionalism: 1,
    minEducationRank: -1,
    minAge: 18,
    description: 'Приготовление блюд по меню.',
  },
  {
    id: 'cook_senior',
    name: 'Старший повар',
    schedule: '2/2',
    level: 3,
    salaryPerHour: 875,      // ~70к/мес
    salaryPerDay: 7000,
    salaryPerWeek: 35000,
    requiredHoursPerWeek: 36,
    minProfessionalism: 4,
    minEducationRank: 0,
    minAge: 25,
    description: 'Контроль кухни, обучение персонала.',
  },
  {
    id: 'chef',
    name: 'Шеф-повар',
    schedule: '5/2',
    level: 6,
    salaryPerHour: 1875,     // ~150к/мес
    salaryPerDay: 15000,
    salaryPerWeek: 75000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 8,
    minEducationRank: 1,
    minAge: 30,
    description: 'Меню, управление кухней, концепция заведения.',
  },

  // === Госслужба ===
  {
    id: 'gov_specialist',
    name: 'Специалист госс��уж��ы',
    schedule: '5/2',
    level: 2,
    salaryPerHour: 500,      // ~40к/мес
    salaryPerDay: 4000,
    salaryPerWeek: 20000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 1,
    minEducationRank: 1,
    minAge: 22,
    description: 'Работа в государственном учреждении.',
  },
  {
    id: 'gov_inspector',
    name: 'Государственный инспектор',
    schedule: '5/2',
    level: 4,
    salaryPerHour: 750,      // ~60к/мес
    salaryPerDay: 6000,
    salaryPerWeek: 30000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 4,
    minEducationRank: 1,
    minAge: 25,
    description: 'Проверки, надзор, документы.',
  },
  {
    id: 'gov_official',
    name: 'Государственный служащий',
    schedule: '5/2',
    level: 6,
    salaryPerHour: 1500,     // ~120к/мес
    salaryPerDay: 12000,
    salaryPerWeek: 60000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 7,
    minEducationRank: 2,
    minAge: 30,
    description: 'Руководство отделом, принятие решений.',
  },

  // === Творческие / Медиа ===
  {
    id: 'media_copywriter',
    name: 'Копирайтер',
    schedule: 'Свободный',
    level: 1,
    salaryPerHour: 500,      // ~30-50к/мес
    salaryPerDay: 3000,
    salaryPerWeek: 15000,
    requiredHoursPerWeek: 30,
    minProfessionalism: 1,
    minEducationRank: -1,
    minAge: 18,
    description: 'Написание текстов, постов, статей.',
  },
  {
    id: 'media_designer',
    name: 'Графический дизайнер',
    schedule: 'Свободный',
    level: 2,
    salaryPerHour: 750,      // ~45-60к/мес
    salaryPerDay: 4500,
    salaryPerWeek: 22500,
    requiredHoursPerWeek: 30,
    minProfessionalism: 3,
    minEducationRank: 0,
    minAge: 20,
    description: 'Дизайн рекламы, упаковка, брендинг.',
  },
  {
    id: 'media_photographer',
    name: 'Профессиональный фотограф',
    schedule: 'Свободный',
    level: 3,
    salaryPerHour: 1250,     // ~75-100к/мес
    salaryPerDay: 7500,
    salaryPerWeek: 37500,
    requiredHoursPerWeek: 30,
    minProfessionalism: 4,
    minEducationRank: -1,
    minAge: 22,
    description: 'Съёмка, обработка, продажа услуг.',
  },
  {
    id: 'media_content',
    name: 'Контент-мейкер / Блогер',
    schedule: 'Свободный',
    level: 3,
    salaryPerHour: 1500,     // переменный доход
    salaryPerDay: 9000,
    salaryPerWeek: 45000,
    requiredHoursPerWeek: 30,
    minProfessionalism: 5,
    minEducationRank: 0,
    minAge: 20,
    description: 'Создание контента, соцсети, монетизация.',
  },

  // === Банки / Финансы ===
  {
    id: 'bank_manager',
    name: 'Менеджер банка',
    schedule: '5/2',
    level: 2,
    salaryPerHour: 750,      // ~60к/мес + бонусы
    salaryPerDay: 6000,
    salaryPerWeek: 30000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 2,
    minEducationRank: 1,
    minAge: 22,
    description: 'Привлечение клиентов, продажа продуктов.',
  },
  {
    id: 'bank_analyst',
    name: 'Банковский аналитик',
    schedule: '5/2',
    level: 4,
    salaryPerHour: 1375,     // ~110к/мес
    salaryPerDay: 11000,
    salaryPerWeek: 55000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 5,
    minEducationRank: 1,
    minAge: 26,
    description: 'Анализ рисков, кредитов, инвестиций.',
  },
  {
    id: 'bank_director',
    name: 'Директор филиала банка',
    schedule: '5/2',
    level: 8,
    salaryPerHour: 3125,     // ~250к/мес
    salaryPerDay: 25000,
    salaryPerWeek: 125000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 9,
    minEducationRank: 2,
    minAge: 35,
    description: 'Управление филиалом, команда, план.',
  },

  // === Сфера услуг ===
  {
    id: 'service_cosmetologist',
    name: 'Косметолог',
    schedule: 'Свободный',
    level: 2,
    salaryPerHour: 1125,     // ~90к/мес
    salaryPerDay: 6750,
    salaryPerWeek: 33750,
    requiredHoursPerWeek: 30,
    minProfessionalism: 3,
    minEducationRank: 1,
    minAge: 22,
    description: 'Уход за кожей, косметические процедуры.',
  },
  {
    id: 'service_fit',
    name: 'Фитнес-тренер',
    schedule: 'Свободный',
    level: 2,
    salaryPerHour: 750,      // ~60к/мес
    salaryPerDay: 4500,
    salaryPerWeek: 22500,
    requiredHoursPerWeek: 30,
    minProfessionalism: 2,
    minEducationRank: -1,
    minAge: 20,
    description: 'Тренировки, составление программ.',
  },
  {
    id: 'service_realtor',
    name: 'Риелтор',
    schedule: 'Свободный',
    level: 2,
    salaryPerHour: 1250,     // комиссия ~3-5%
    salaryPerDay: 7500,
    salaryPerWeek: 37500,
    requiredHoursPerWeek: 32,
    minProfessionalism: 3,
    minEducationRank: -1,
    minAge: 21,
    description: 'Сделки с недвижимостью, аренда, продажа.',
  },
]