import type { CareerJob } from '@/domain/balance/types'

export const CAREER_JOBS: CareerJob[] = [
  {
    id: 'office_employee',
    name: 'Офисный сотрудник',
    schedule: '5/2',
    level: 1,
    salaryPerHour: 1050,
    salaryPerDay: 8400,
    salaryPerWeek: 42000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 0,
    minEducationRank: -1,
    minAge: 16,
    description: 'Классическая офисная работа: документы, отчёты, совещания. Стабильный старт карьеры.',
  },
  {
    id: 'shift_worker',
    name: 'Сменный рабочий (производство / склад)',
    schedule: '2/2',
    level: 1,
    salaryPerHour: 1250,
    salaryPerDay: 15000,
    salaryPerWeek: 30000,
    requiredHoursPerWeek: 24,
    minProfessionalism: 0,
    minEducationRank: -1,
    minAge: 18,
    description: 'Сменная работа на производстве или складе. Физический труд, но хорошая почасовая оплата.',
  },
  {
    id: 'project_coordinator',
    name: 'Координатор проектов',
    schedule: '5/2',
    level: 2,
    salaryPerHour: 1350,
    salaryPerDay: 10800,
    salaryPerWeek: 54000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 3,
    minEducationRank: 0,
    minAge: 20,
    description: 'Организация задач, контроль сроков и коммуникация между командами.',
  },
  {
    id: 'business_analyst',
    name: 'Бизнес-аналитик',
    schedule: '5/2',
    level: 3,
    salaryPerHour: 1720,
    salaryPerDay: 13760,
    salaryPerWeek: 68800,
    requiredHoursPerWeek: 40,
    minProfessionalism: 5,
    minEducationRank: 1,
    minAge: 22,
    description: 'Анализ бизнес-процессов, сбор требований и подготовка решений.',
  },
  {
    id: 'team_lead',
    name: 'Тимлид / Руководитель группы',
    schedule: '5/2',
    level: 4,
    salaryPerHour: 2050,
    salaryPerDay: 16400,
    salaryPerWeek: 82000,
    requiredHoursPerWeek: 40,
    minProfessionalism: 7,
    minEducationRank: 2,
    minAge: 26,
    description: 'Руководство небольшой командой, распределение задач и развитие сотрудников.',
  },
  {
    id: 'senior_manager',
    name: 'Старший менеджер / Руководитель отдела',
    schedule: '5/2',
    level: 5,
    salaryPerHour: 2450,
    salaryPerDay: 19600,
    salaryPerWeek: 98000,
    requiredHoursPerWeek: 42,
    minProfessionalism: 9,
    minEducationRank: 3,
    minAge: 29,
    description: 'Управление большим отделом, стратегические решения и ответственность за результат.',
  },
  {
    id: 'freelance_specialist',
    name: 'Фрилансер / Специалист на удалёнке',
    schedule: 'Свободный',
    level: 2,
    salaryPerHour: 1650,
    salaryPerDay: 9900,     // при 6 часах
    salaryPerWeek: 49500,
    requiredHoursPerWeek: 30,
    minProfessionalism: 4,
    minEducationRank: 0,
    minAge: 19,
    description: 'Удалённая работа на себя. Гибкий график, но нет стабильной зарплаты.',
  },
  {
    id: 'department_head',
    name: 'Руководитель департамента',
    schedule: '5/2',
    level: 6,
    salaryPerHour: 3100,
    salaryPerDay: 24800,
    salaryPerWeek: 124000,
    requiredHoursPerWeek: 44,
    minProfessionalism: 12,
    minEducationRank: 4,
    minAge: 32,
    description: 'Высокая управленческая позиция с серьёзной ответственностью и доходом.',
  },
]