import type { EducationProgram } from '@/domain/balance/types'

export const EDUCATION_PROGRAMS: EducationProgram[] = [
  {
    id: 'time_management_book',
    title: 'Книга «Как управлять временем»',
    subtitle: 'Простой и недорогой способ навести порядок в голове и делах.',
    typeLabel: 'Книга',
    cost: 950,
    daysRequired: 2,
    hoursRequired: 9,
    accentKey: 'accent',
    rewardText: 'Тайм-менеджмент +2 • Стресс -6 • Дисциплина +1',
    completionStatChanges: { stress: -6, mood: 4 },
    completionSkillChanges: { timeManagement: 2, discipline: 1 },
    description: 'Короткая, но очень практичная книга, которая помогает перестать тратить время впустую.',
  },
  {
    id: 'online_productivity_course',
    title: 'Онлайн-курс «Личная эффективность»',
    subtitle: 'Системный подход к продуктивности с заданиями и обратной связью.',
    typeLabel: 'Онлайн-курс',
    cost: 6900,
    daysRequired: 6,
    hoursRequired: 28,
    accentKey: 'blue',
    rewardText: 'Профессионализм +2 • Тайм-менеджмент +2 • Настроение +10',
    completionStatChanges: { mood: 10, stress: -7, energy: 5 },
    completionSkillChanges: { professionalism: 2, timeManagement: 2, discipline: 1 },
    description: 'Практический курс с видео, заданиями и чек-листами. Даёт ощутимый прирост организованности.',
  },
  {
    id: 'institute_retraining',
    title: 'Профессиональная переподготовка в институте',
    subtitle: 'Серьёзное долгосрочное обучение для перехода на новый карьерный уровень.',
    typeLabel: 'Институт',
    cost: 135000,
    daysRequired: 10,
    hoursRequired: 180,
    accentKey: 'sage',
    rewardText: 'Профессионализм +4 • Зарплата +8% • Образование: Высшее',
    completionStatChanges: { mood: 8, stress: -5 },
    completionSkillChanges: { professionalism: 4, analyticalThinking: 2 },
    salaryMultiplierDelta: 0.08,
    educationLevel: 'Высшее',
    description: 'Полноценная переподготовка с дипломом. Долгий, но надёжный путь к более высокой должности и зарплате.',
  },

  // ───── Новые осознанные образовательные программы ─────
  {
    id: 'foreign_language_intensive',
    title: 'Интенсив по иностранному языку',
    subtitle: 'Погружение в язык с ежедневными занятиями и разговорной практикой.',
    typeLabel: 'Интенсив',
    cost: 18500,
    daysRequired: 7,
    hoursRequired: 45,
    accentKey: 'blue',
    rewardText: 'Коммуникация +3 • Харизма +1 • Настроение +9',
    completionStatChanges: { mood: 9, stress: -6 },
    completionSkillChanges: { communication: 3, charisma: 1 },
    description: 'Интенсивный курс с носителем языка. Значительно улучшает навык общения.',
  },
  {
    id: 'public_speaking_course',
    title: 'Курс ораторского мастерства',
    subtitle: 'Учимся уверенно выступать перед аудиторией.',
    typeLabel: 'Курс',
    cost: 12400,
    daysRequired: 5,
    hoursRequired: 22,
    accentKey: 'accent',
    rewardText: 'Харизма +3 • Коммуникация +2 • Стресс от публичных выступлений -30%',
    completionStatChanges: { stress: -8, mood: 11 },
    completionSkillChanges: { charisma: 3, communication: 2 },
    description: 'Практический курс с выступлениями, разбором и обратной связью.',
  },
  {
    id: 'financial_literacy_intensive',
    title: 'Интенсив «Финансовая свобода»',
    subtitle: 'Глубокое погружение в личные финансы и инвестиции.',
    typeLabel: 'Интенсив',
    cost: 9800,
    daysRequired: 4,
    hoursRequired: 18,
    accentKey: 'sage',
    rewardText: 'Финансовая грамотность +4 • Аналитическое мышление +2',
    completionStatChanges: { stress: -10, mood: 7 },
    completionSkillChanges: { financialLiteracy: 4, analyticalThinking: 2 },
    description: 'Практический курс, после которого вы перестаёте бояться денег и начинаете ими управлять.',
  },
]