import type { EducationProgram } from '@domain/balance/types'
import { AgeGroup } from '@domain/balance/actions/types'

export const EDUCATION_PROGRAMS: EducationProgram[] = [
  {
    id: 'time_management_book',
    title: 'Книга «Как управлять временем»',
    subtitle: 'Простой и недорогой способ навести порядок в голове и делах.',
    track: 'book',
    acquisition: 'shop_only',
    requiresItemId: 'book_time_management',
    purchaseActionId: 'shop_time_management_book',
    typeLabel: 'Книга',
    cost: 0,
    daysRequired: 2,
    hoursRequired: 9,
    accentKey: 'accent',
    rewardText: 'Тайм-менеджмент +2 • Стресс -6 • Дисциплина +1',
    completionStatChanges: { stress: -6, mood: 4 },
    completionSkillChanges: { timeManagement: 2, discipline: 1 },
    description: 'Короткая, но очень практичная книга, которая помогает перестать тратить время впустую.',
    minAgeGroup: AgeGroup.TEEN,
    ageReason: 'Осознанный навык самоорганизации, книга про self-management',
    preventRepeat: true,
  },
  {
    id: 'meditation_foundations_book',
    title: 'Книга «Основы медитации»',
    subtitle: 'Пять этапов освоения — от введения до устойчивой практики в жизни.',
    track: 'book',
    acquisition: 'shop_only',
    requiresItemId: 'book_meditation_foundations',
    purchaseActionId: 'shop_meditation_foundations_book',
    typeLabel: 'Книга',
    cost: 0,
    daysRequired: 2,
    hoursRequired: 14,
    accentKey: 'sage',
    rewardText: 'Медитация +1 • Эмоциональный интеллект +0.5',
    completionStatChanges: { hunger: 6.5, energy: -9, stress: -20, mood: 16, health: 1.2, physical: -1 },
    completionSkillChanges: { meditation: 1, emotionalIntelligence: 0.5 },
    description:
      'Книга делится на пять этапов: введение, тело и дыхание, работа с мыслями, эмоции и внимание, встраивание практики в день. Каждый этап — отдельные главы и упражнения. После полного прохождения открывается действие «Медитация» в развлечениях.',
    minAgeGroup: AgeGroup.TEEN,
    ageReason: 'Самостоятельная практика осознанности, книга для подростков и старше',
    preventRepeat: true,
    steps: [
      {
        id: 'meditation_foundations_book_stage_1',
        title: 'Этап 1. Введение и намерение',
        hoursRequired: 3,
        progressPercent: 0,
      },
      {
        id: 'meditation_foundations_book_stage_2',
        title: 'Этап 2. Тело, осанка и дыхание',
        hoursRequired: 3,
        progressPercent: 0,
      },
      {
        id: 'meditation_foundations_book_stage_3',
        title: 'Этап 3. Наблюдение за мыслями',
        hoursRequired: 3,
        progressPercent: 0,
      },
      {
        id: 'meditation_foundations_book_stage_4',
        title: 'Этап 4. Эмоции и возвращение внимания',
        hoursRequired: 3,
        progressPercent: 0,
      },
      {
        id: 'meditation_foundations_book_stage_5',
        title: 'Этап 5. Практика в повседневности',
        hoursRequired: 2,
        progressPercent: 0,
        milestoneReward: {
          message: '📘 Финальный этап книги пройден — осталось закрепить награду за полное освоение.',
        },
      },
    ],
  },
  {
    id: 'online_productivity_course',
    title: 'Онлайн-курс «Личная эффективность»',
    subtitle: 'Системный подход к продуктивности с заданиями и обратной связью.',
    track: 'online',
    acquisition: 'purchase_on_education_page',
    requiresComputer: true,
    requiresItemId: 'study_laptop',
    typeLabel: 'Онлайн-курс',
    cost: 6900,
    daysRequired: 6,
    hoursRequired: 28,
    accentKey: 'blue',
    rewardText: 'Профессионализм +2 • Тайм-менеджмент +2 • Настроение +10',
    completionStatChanges: { mood: 10, stress: -7, energy: 5 },
    completionSkillChanges: { professionalism: 2, timeManagement: 2, discipline: 1 },
    description: 'Практический курс с видео, заданиями и чек-листами. Даёт ощутимый прирост организованности.',
    minAgeGroup: AgeGroup.YOUNG,
    ageReason: 'Уже заметно adult-coded продукт, системный подход к продуктивности',
  },
  {
    id: 'institute_retraining',
    title: 'Профессиональная переподготовка в институте',
    subtitle: 'Серьёзное долгосрочное обучение для перехода на новый карьерный уровень.',
    track: 'institute',
    acquisition: 'purchase_on_education_page',
    typeLabel: 'Институт',
    cost: 135000,
    daysRequired: 10,
    hoursRequired: 180,
    accentKey: 'sage',
    rewardText: 'Профессионализм +4 • Зарплата +8% • Образование: Высшее',
    completionStatChanges: { mood: 8, stress: -5 },
    completionSkillChanges: { professionalism: 4, analyticalThinking: 2 },
    salaryMultiplierDelta: 0.08,
    educationLevel: 'Высшее',
    description: 'Полноценная переподготовка с дипломом. Долгий, но надёжный путь к более высокой должности и зарплате.',
    minAgeGroup: AgeGroup.ADULT,
    ageReason: 'Формальное карьерное обучение, даёт образование: Высшее, повышает зарплату',
  },

  // ───── Новые осознанные образовательные программы ─────
  {
    id: 'foreign_language_intensive',
    title: 'Интенсив по иностранному языку',
    subtitle: 'Погружение в язык с ежедневными занятиями и разговорной практикой.',
    track: 'intensive',
    acquisition: 'purchase_on_education_page',
    typeLabel: 'Интенсив',
    cost: 18500,
    daysRequired: 7,
    hoursRequired: 45,
    accentKey: 'blue',
    rewardText: 'Коммуникация +3 • Харизма +1 • Настроение +9',
    completionStatChanges: { mood: 9, stress: -6 },
    completionSkillChanges: { communication: 3, charisma: 1 },
    description: 'Интенсивный курс с носителем языка. Значительно улучшает навык общения.',
    minAgeGroup: AgeGroup.TEEN,
    ageReason: 'Реалистично с подросткового возраста, языковые интенсивы распространены',
  },
  {
    id: 'public_speaking_course',
    title: 'Курс ораторского мастерства',
    subtitle: 'Учимся уверенно выступать перед аудиторией.',
    track: 'course',
    acquisition: 'purchase_on_education_page',
    typeLabel: 'Курс',
    cost: 12400,
    daysRequired: 5,
    hoursRequired: 22,
    accentKey: 'accent',
    rewardText: 'Харизма +3 • Коммуникация +2 • Стресс от публичных выступлений -30%',
    completionStatChanges: { stress: -8, mood: 11 },
    completionSkillChanges: { charisma: 3, communication: 2 },
    description: 'Практический курс с выступлениями, разбором и обратной связью.',
    minAgeGroup: AgeGroup.TEEN,
    ageReason: 'Подходит подросткам и взрослым',
  },
  {
    id: 'financial_literacy_intensive',
    title: 'Интенсив «Финансовая свобода»',
    subtitle: 'Глубокое погружение в личные финансы и инвестиции.',
    track: 'intensive',
    acquisition: 'purchase_on_education_page',
    typeLabel: 'Интенсив',
    cost: 9800,
    daysRequired: 4,
    hoursRequired: 18,
    accentKey: 'sage',
    rewardText: 'Финансовая грамотность +4 • Аналитическое мышление +2',
    completionStatChanges: { stress: -10, mood: 7 },
    completionSkillChanges: { financialLiteracy: 4, analyticalThinking: 2 },
    description: 'Практический курс, после которого вы перестаёте бояться денег и начинаете ими управлять.',
    minAgeGroup: AgeGroup.YOUNG,
    ageReason: 'Уже ближе к личным финансам взрослого уровня, инвестиционный фокус',
  },
]