import type { LegacyFinanceAction } from '@/domain/balance/types'

export const LEGACY_FINANCE_SCENE_ACTIONS: LegacyFinanceAction[] = [
  {
    id: 'reserve_transfer',
    title: 'Пополнить финансовую подушку',
    subtitle: 'Перевести часть свободных средств в резерв на непредвиденные случаи.',
    amount: 10000,
    reserveDelta: 10000,
    dayCost: 1,
    hourCost: 1,
    statChanges: { hunger: 1.5, energy: -2, stress: -11.5, mood: 7.5, health: 0.5 },
    skillChanges: { financialLiteracy: 1.5 },
    accentKey: 'sage',
    description: 'Ликвидные деньги -10 000 ₽ • Резерв +10 000 ₽ • Стресс сильно снижается',
  },
  {
    id: 'open_deposit',
    title: 'Открыть банковский вклад',
    subtitle: 'Заморозить деньги на 28 дней, чтобы получить гарантированный процент.',
    amount: 50000,
    expectedReturn: 4200,
    durationDays: 28,
    dayCost: 1,
    hourCost: 2,
    statChanges: { hunger: 2.2, energy: -3.5, stress: -8.5, mood: 6.5, health: 0.4 },
    skillChanges: { financialLiteracy: 2 },
    accentKey: 'blue',
    description: 'Ликвидные деньги -50 000 ₽ • Через 28 дней вернётся 54 200 ₽ • Спокойствие и небольшой доход',
  },
  {
    id: 'budget_review',
    title: 'Пересмотреть и оптимизировать бюджет',
    subtitle: 'Проанализировать расходы и найти возможности для экономии.',
    amount: 0,
    dayCost: 1,
    hourCost: 1.5,
    statChanges: { hunger: 1.8, energy: -3, stress: -12.5, mood: 8.5, health: 0.6 },
    skillChanges: { financialLiteracy: 2.5, organization: 1.5 },
    monthlyExpenseDelta: {
      leisure: -1200,
      education: 300,
      food: -400,
    },
    accentKey: 'accent',
    description: 'Стресс значительно снижается • Финансовая грамотность +2.5 • Организованность +1.5 • Экономия ~1600 ₽/мес',
  },

  // ───── Новые осознанные действия ─────
  {
    id: 'pay_off_small_debt',
    title: 'Погасить небольшой долг',
    subtitle: 'Закрыть микрозайм или кредитную карту, чтобы снять психологическое давление.',
    amount: 8000,
    dayCost: 1,
    hourCost: 1,
    statChanges: { hunger: 1.5, energy: -2.5, stress: -18, mood: 14.5, health: 1.2 },
    skillChanges: { financialLiteracy: 1 },
    accentKey: 'sage',
    description: 'Ликвидные деньги -8 000 ₽ • Стресс сильно падает • Настроение заметно улучшается',
  },
  {
    id: 'create_auto_savings',
    title: 'Настроить автоматические накопления',
    subtitle: 'Автоматически переводить небольшую сумму каждый месяц на сберегательный счёт.',
    amount: 0,
    dayCost: 1,
    hourCost: 1,
    statChanges: { hunger: 1.2, energy: -2, stress: -9.5, mood: 7 },
    skillChanges: { discipline: 2, financialLiteracy: 2 },
    accentKey: 'blue',
    description: 'Финансовая дисциплина +2 • Финансовая грамотность +2 • Автоматические накопления запущены',
  },
  {
    id: 'sell_unnecessary_items',
    title: 'Продать ненужные вещи',
    subtitle: 'Разобрать гардероб, технику и другие вещи, которые не используются.',
    amount: 0,
    dayCost: 2,
    hourCost: 3,
    statChanges: { hunger: 4.5, energy: -6.5, stress: -7.5, mood: 9.5 },
    skillChanges: { organization: 2 },
    accentKey: 'accent',
    description: 'Организованность +2 • Возможный доход от продажи вещей • Освобождение пространства',
  },
]