import type { PersonalityTraitDef } from '../types/personality'
import { PersonalityAxis } from '../types/personality'

/**
 * 41 черта характера, формируемая в детстве.
 * Каждая имеет компромисс: положительные + отрицательные эффекты.
 * Формируется через события и выборы в определённом возрасте.
 */
export const PERSONALITY_TRAITS: PersonalityTraitDef[] = [
  // =============================================================================
  // OPENNESS (Открытость опыту)
  // =============================================================================
  { id: 'curious', name: 'Любопытство', description: 'Интерес ко всему новому', axis: PersonalityAxis.OPENNESS, threshold: 30,
    positiveEffects: 'Быстрее обучаешься', negativeEffects: 'Легко отвлекаешься',
    acquireCondition: 'Исследовал мир в 4-8 лет', formAgeStart: 4, formAgeEnd: 8,
    modifiers: { learningSpeedMultiplier: 0.15 } },
  { id: 'creative', name: 'Творчество', description: 'Нестандартное мышление', axis: PersonalityAxis.OPENNESS, threshold: 60,
    positiveEffects: 'Уникальные решения, доход от хобби', negativeEffects: 'Сложно с рутиной',
    acquireCondition: 'Рисовал, придумывал истории в 5-12 лет', formAgeStart: 5, formAgeEnd: 12,
    modifiers: { learningSpeedMultiplier: 0.2, hobbyIncomeMultiplier: 0.25 } },
  { id: 'closed_minded', name: 'Консервативность', description: 'Предпочитает проверенное', axis: PersonalityAxis.OPENNESS, threshold: -30,
    positiveEffects: 'Меньше стресса от нового', negativeEffects: 'Упускаешь возможности',
    acquireCondition: 'Избегал нового в 6-12 лет', formAgeStart: 6, formAgeEnd: 12,
    modifiers: { stressGainMultiplier: -0.1 } },
  { id: 'riskTaker', name: 'Рисковый', description: 'Любит риск и азарт', axis: PersonalityAxis.OPENNESS, threshold: 50,
    positiveEffects: 'Удвоенная награда за риск', negativeEffects: 'Рано или поздно разобьёшься',
    acquireCondition: '3+ раз рискнул и выиграл в 13-17 лет', formAgeStart: 13, formAgeEnd: 17,
    modifiers: { positiveEventChance: 0.15, negativeEventChance: 0.1 } },
  { id: 'cautious', name: 'Осторожный', description: 'Избегает ненужного риска', axis: PersonalityAxis.OPENNESS, threshold: -50,
    positiveEffects: 'Никогда не попадёшь в большую беду', negativeEffects: 'Никогда не получишь большую награду',
    acquireCondition: '3+ раз рискнул и проиграл в 13-17 лет', formAgeStart: 13, formAgeEnd: 17,
    modifiers: { negativeEventChance: -0.15, positiveEventChance: -0.1 } },
  { id: 'idealist', name: 'Идеалист', description: 'Верит в идеи и мечты', axis: PersonalityAxis.OPENNESS, threshold: 40,
    positiveEffects: 'Осмысленная жизнь', negativeEffects: 'Почти наверняка будешь бедным',
    acquireCondition: 'Хвалили за идеи и мечты в 6-12 лет', formAgeStart: 6, formAgeEnd: 12,
    modifiers: { moodRecoveryMultiplier: 0.15, salaryMultiplier: -0.1 } },
  { id: 'liar', name: 'Лгун', description: 'Мастер обмана', axis: PersonalityAxis.OPENNESS, threshold: -40,
    positiveEffects: 'Лжи всегда верят', negativeEffects: 'Перестаёшь отличать правду от лжи',
    acquireCondition: 'Наказывали когда говорил правду в 6-13 лет', formAgeStart: 6, formAgeEnd: 13,
    modifiers: { relationshipGainMultiplier: 0.1, stressGainMultiplier: 0.1 } },
  { id: 'honestToBone', name: 'Честный до мозга костей', description: 'Никогда не лжёт', axis: PersonalityAxis.OPENNESS, threshold: 50,
    positiveEffects: 'Все абсолютно доверяют', negativeEffects: 'Не можешь солгать даже когда необходимо',
    acquireCondition: 'Никогда не наказывали за правду в 6-13 лет', formAgeStart: 6, formAgeEnd: 13,
    modifiers: { relationshipGainMultiplier: 0.25, shopPriceMultiplier: 0.05 } },

  // =============================================================================
  // CONSCIENTIOUSNESS (Добросовестность)
  // =============================================================================
  { id: 'organized', name: 'Организованность', description: 'Любит порядок', axis: PersonalityAxis.CONSCIENTIOUSNESS, threshold: 30,
    positiveEffects: '+10% эффективность работы', negativeEffects: 'Теряешься в хаосе',
    acquireCondition: 'Убирал и раскладывал в 6-12 лет', formAgeStart: 6, formAgeEnd: 12,
    modifiers: { workEfficiencyMultiplier: 0.1 } },
  { id: 'disciplined', name: 'Дисциплина', description: 'Всегда доводит дела до конца', axis: PersonalityAxis.CONSCIENTIOUSNESS, threshold: 60,
    positiveEffects: '+20% работа, шанс повышения', negativeEffects: 'Сложно расслабиться',
    acquireCondition: 'Делал домашку и ходил в школу в 8-14 лет', formAgeStart: 8, formAgeEnd: 14,
    modifiers: { workEfficiencyMultiplier: 0.2, promotionChanceBonus: 0.15 } },
  { id: 'lazy', name: 'Лень', description: 'Избегает лишних усилий', axis: PersonalityAxis.CONSCIENTIOUSNESS, threshold: -30,
    positiveEffects: 'Никогда не выгораешь', negativeEffects: 'Всегда делаешь минимум',
    acquireCondition: 'Никогда не хвалили за усилия в 8-14 лет', formAgeStart: 8, formAgeEnd: 14,
    modifiers: { energyDrainMultiplier: -0.15, workEfficiencyMultiplier: -0.1 } },
  { id: 'perfectionist', name: 'Перфекционист', description: 'Всё должно быть идеально', axis: PersonalityAxis.CONSCIENTIOUSNESS, threshold: 70,
    positiveEffects: 'Делаешь всё на 10% лучше', negativeEffects: 'Никогда не заканчиваешь вовремя',
    acquireCondition: 'Постоянно ругали за ошибки в 7-12 лет', formAgeStart: 7, formAgeEnd: 12,
    modifiers: { workEfficiencyMultiplier: 0.1, stressGainMultiplier: 0.15 } },
  { id: 'workaholic', name: 'Трудоголик', description: 'Живёт работой', axis: PersonalityAxis.CONSCIENTIOUSNESS, threshold: 80,
    positiveEffects: '×2 работа', negativeEffects: 'Никогда не отдыхаешь, выгораешь быстрее',
    acquireCondition: 'Хвалили только за результаты в 8-14 лет', formAgeStart: 8, formAgeEnd: 14,
    modifiers: { workEfficiencyMultiplier: 0.3, stressGainMultiplier: 0.2 } },
  { id: 'materialist', name: 'Материалист', description: 'Ценит вещи и деньги', axis: PersonalityAxis.CONSCIENTIOUSNESS, threshold: -40,
    positiveEffects: 'Всегда будешь зарабатывать много', negativeEffects: 'Деньги никогда не сделают счастливым',
    acquireCondition: 'Единственное за что хвалили — вещи в 6-12 лет', formAgeStart: 6, formAgeEnd: 12,
    modifiers: { salaryMultiplier: 0.2, moodRecoveryMultiplier: -0.1 } },

  // =============================================================================
  // EXTRAVERSION (Экстраверсия)
  // =============================================================================
  { id: 'friendly', name: 'Дружелюбие', description: 'Легко находит общий язык', axis: PersonalityAxis.EXTRAVERSION, threshold: 30,
    positiveEffects: '+20% качество отношений', negativeEffects: 'Тратишь энергию на общение',
    acquireCondition: 'Играл с другими детьми в 4-10 лет', formAgeStart: 4, formAgeEnd: 10,
    modifiers: { relationshipGainMultiplier: 0.2 } },
  { id: 'sociable', name: 'Общительность', description: 'Душа компании', axis: PersonalityAxis.EXTRAVERSION, threshold: 60,
    positiveEffects: '+35% отношения, +10% позитивные события', negativeEffects: 'Зависишь от чужого внимания',
    acquireCondition: 'Был лидером в компании в 8-16 лет', formAgeStart: 8, formAgeEnd: 16,
    modifiers: { relationshipGainMultiplier: 0.35, positiveEventChanceBonus: 0.1 } },
  { id: 'introvert', name: 'Интроверт', description: 'Предпочитает одиночество', axis: PersonalityAxis.EXTRAVERSION, threshold: -30,
    positiveEffects: 'Меньше стресса, не нужны люди', negativeEffects: 'Очень сложно строить близкие отношения',
    acquireCondition: 'Оставляли одного когда плакал в 3-7 лет', formAgeStart: 3, formAgeEnd: 7,
    modifiers: { stressGainMultiplier: -0.15, relationshipGainMultiplier: -0.1 } },
  { id: 'extravert', name: 'Экстраверт', description: 'Энергия от общения', axis: PersonalityAxis.EXTRAVERSION, threshold: 50,
    positiveEffects: 'Легко знакомишься со всеми', negativeEffects: 'Не можешь быть один больше нескольких часов',
    acquireCondition: 'Получали внимание когда плакал в 3-7 лет', formAgeStart: 3, formAgeEnd: 7,
    modifiers: { relationshipGainMultiplier: 0.3, energyDrainMultiplier: 0.1 } },
  { id: 'teamPlayer', name: 'Командный игрок', description: 'Отлично работает в коллективе', axis: PersonalityAxis.EXTRAVERSION, threshold: 40,
    positiveEffects: 'Отлично работаешь в коллективе', negativeEffects: 'Никогда не можешь взять ответственность на себя',
    acquireCondition: 'Часто играл в командные игры в 7-14 лет', formAgeStart: 7, formAgeEnd: 14,
    modifiers: { teamEventBonus: 0.2, workEfficiencyMultiplier: -0.05 } },
  { id: 'loner', name: 'Одиночка', description: 'Предпочитает работать один', axis: PersonalityAxis.EXTRAVERSION, threshold: -40,
    positiveEffects: 'Отлично работаешь один', negativeEffects: 'Не можешь работать в команде совсем',
    acquireCondition: 'Всегда играл один в 7-14 лет', formAgeStart: 7, formAgeEnd: 14,
    modifiers: { workEfficiencyMultiplier: 0.15, teamEventBonus: -0.2 } },
  { id: 'selfSufficient', name: 'Самодостаточный', description: 'Не нуждается в других', axis: PersonalityAxis.EXTRAVERSION, threshold: -60,
    positiveEffects: 'Тебе абсолютно не нужен никто', negativeEffects: 'Никогда не попросишь о помощи даже когда умираешь',
    acquireCondition: 'Никто никогда не приходил на помощь в 5-12 лет', formAgeStart: 5, formAgeEnd: 12,
    modifiers: { stressGainMultiplier: -0.2, relationshipGainMultiplier: -0.25 } },
  { id: 'dependent', name: 'Зависимый', description: 'Нуждается в поддержке', axis: PersonalityAxis.EXTRAVERSION, threshold: 60,
    positiveEffects: 'Все хотят о тебе заботиться', negativeEffects: 'Не можешь прожить один ни дня',
    acquireCondition: 'Всегда решали все проблемы за тебя в 5-12 лет', formAgeStart: 5, formAgeEnd: 12,
    modifiers: { relationshipGainMultiplier: 0.2, workEfficiencyMultiplier: -0.15 } },

  // =============================================================================
  // AGREEABLENESS (Доброжелательность)
  // =============================================================================
  { id: 'cooperative', name: 'Кооперативность', description: 'Умеет работать с другими', axis: PersonalityAxis.AGREEABLENESS, threshold: 30,
    positiveEffects: '+15% качество отношений', negativeEffects: 'Сложно отказывать',
    acquireCondition: 'Делился и помогал в 5-12 лет', formAgeStart: 5, formAgeEnd: 12,
    modifiers: { relationshipGainMultiplier: 0.15 } },
  { id: 'compassionate', name: 'Сочувствие', description: 'Понимание других людей', axis: PersonalityAxis.AGREEABLENESS, threshold: 60,
    positiveEffects: '+25% отношения, +15% позитивные события', negativeEffects: 'Больно за чужие страдания',
    acquireCondition: 'Защищал слабых и животных в 5-12 лет', formAgeStart: 5, formAgeEnd: 12,
    modifiers: { positiveEventChanceBonus: 0.15, relationshipGainMultiplier: 0.25 } },
  { id: 'competitive', name: 'Конкурентность', description: 'Любит побеждать', axis: PersonalityAxis.AGREEABLENESS, threshold: -30,
    positiveEffects: '+10% работа, +10% ЗП', negativeEffects: 'Сложно с сотрудничеством',
    acquireCondition: 'Соревновался и побеждал в 7-14 лет', formAgeStart: 7, formAgeEnd: 14,
    modifiers: { workEfficiencyMultiplier: 0.1, salaryMultiplier: 0.1 } },
  { id: 'tough', name: 'Жёсткий', description: 'Никто не может тебя сломать', axis: PersonalityAxis.AGREEABLENESS, threshold: -50,
    positiveEffects: 'Никто не может тебя сломать', negativeEffects: 'Не можешь чувствовать сострадание',
    acquireCondition: 'Часто били и не показывали жалость в 7-12 лет', formAgeStart: 7, formAgeEnd: 12,
    modifiers: { stressGainMultiplier: -0.2, relationshipGainMultiplier: -0.2 } },
  { id: 'soft', name: 'Мягкий', description: 'Все хотят помочь', axis: PersonalityAxis.AGREEABLENESS, threshold: 50,
    positiveEffects: 'Все хотят тебе помочь', negativeEffects: 'Все тебя используют',
    acquireCondition: 'Всегда защищали и жалели в 7-12 лет', formAgeStart: 7, formAgeEnd: 12,
    modifiers: { positiveEventChanceBonus: 0.1, salaryMultiplier: -0.05 } },
  { id: 'vengeful', name: 'Мстительный', description: 'Никогда не забывает обиды', axis: PersonalityAxis.AGREEABLENESS, threshold: -60,
    positiveEffects: 'Все боятся тебя обидеть', negativeEffects: 'Тратишь годы на месть которая ничего не даст',
    acquireCondition: 'Никто не помог когда предали в 12-16 лет', formAgeStart: 12, formAgeEnd: 16,
    modifiers: { stressGainMultiplier: 0.15, relationshipGainMultiplier: -0.15 } },
  { id: 'forgiving', name: 'Прощающий', description: 'Не носит обид внутри', axis: PersonalityAxis.AGREEABLENESS, threshold: 40,
    positiveEffects: 'Никогда не носишь обид внутри', negativeEffects: 'Люди постоянно тебя предают',
    acquireCondition: 'Всегда прощали твои ошибки в 8-14 лет', formAgeStart: 8, formAgeEnd: 14,
    modifiers: { stressGainMultiplier: -0.1, relationshipGainMultiplier: 0.1 } },

  // =============================================================================
  // NEUROTICISM (Нейротизм) — positive threshold = more anxious, negative = calmer
  // =============================================================================
  { id: 'calm', name: 'Спокойствие', description: 'Не поддается панике', axis: PersonalityAxis.NEUROTICISM, threshold: -30,
    positiveEffects: '-20% стресс', negativeEffects: 'Можешь пропустить опасность',
    acquireCondition: 'Спокойная обстановка в 5-14 лет', formAgeStart: 5, formAgeEnd: 14,
    modifiers: { stressGainMultiplier: -0.2 } },
  { id: 'resilient', name: 'Стойкость', description: 'Легко переносит неудачи', axis: PersonalityAxis.NEUROTICISM, threshold: -60,
    positiveEffects: '-30% стресс, -20% штраф от негативных событий', negativeEffects: 'Можешь не заметить проблему',
    acquireCondition: 'Преодолевал трудности в 8-16 лет', formAgeStart: 8, formAgeEnd: 16,
    modifiers: { stressGainMultiplier: -0.3, negativeEventPenaltyReduction: 0.2 } },
  { id: 'anxious', name: 'Тревожность', description: 'Часто волнуется', axis: PersonalityAxis.NEUROTICISM, threshold: 30,
    positiveEffects: 'Замечаешь проблемы раньше', negativeEffects: '+15% стресс',
    acquireCondition: 'Непредсказуемая обстановка в 5-14 лет', formAgeStart: 5, formAgeEnd: 14,
    modifiers: { stressGainMultiplier: 0.15 } },
  { id: 'pessimist', name: 'Пессимист', description: 'Ожидает худшего', axis: PersonalityAxis.NEUROTICISM, threshold: 50,
    positiveEffects: 'Никогда не получаешь неприятных сюрпризов', negativeEffects: 'Никогда не испытываешь настоящей радости',
    acquireCondition: '5+ раз надеялся и разочаровался в 10-16 лет', formAgeStart: 10, formAgeEnd: 16,
    modifiers: { negativeEventPenaltyReduction: 0.1, moodRecoveryMultiplier: -0.15 } },
  { id: 'optimist', name: 'Оптимист', description: 'Верит в лучшее', axis: PersonalityAxis.NEUROTICISM, threshold: -50,
    positiveEffects: 'Всегда есть дополнительный вариант выбора', negativeEffects: 'Часто попадаешь в неприятности из-за самоуверенности',
    acquireCondition: '5+ раз всё закончилось хорошо несмотря на опасения', formAgeStart: 5, formAgeEnd: 16,
    modifiers: { positiveEventChanceBonus: 0.15, negativeEventChance: 0.1 } },

  // =============================================================================
  // Дополнительные черты (смешанные оси)
  // =============================================================================
  { id: 'brave', name: 'Смелость', description: 'Не боится действовать', axis: PersonalityAxis.EXTRAVERSION, threshold: 45,
    positiveEffects: 'Не замораживаешься перед опасностью', negativeEffects: 'Иногда действуешь слишком поспешно',
    acquireCondition: 'Преодолевал страхи в 6-14 лет', formAgeStart: 6, formAgeEnd: 14,
    modifiers: { stressGainMultiplier: -0.1, positiveEventChance: 0.05 } },
  { id: 'shy', name: 'Застенчивость', description: 'Трудно с новыми людьми', axis: PersonalityAxis.EXTRAVERSION, threshold: -35,
    positiveEffects: 'Хороший слушатель', negativeEffects: 'Упускаешь возможности общения',
    acquireCondition: 'Пугался незнакомых в 4-10 лет', formAgeStart: 4, formAgeEnd: 10,
    modifiers: { relationshipGainMultiplier: -0.1, stressGainMultiplier: 0.05 } },
  { id: 'stubborn', name: 'Упрямство', description: 'Не сдаётся', axis: PersonalityAxis.CONSCIENTIOUSNESS, threshold: -50,
    positiveEffects: 'Не сдаёшься перед трудностями', negativeEffects: 'Не слушаешь чужих советов',
    acquireCondition: 'Отказывался подчиняться в 6-14 лет', formAgeStart: 6, formAgeEnd: 14,
    modifiers: { workEfficiencyMultiplier: 0.1, relationshipGainMultiplier: -0.1 } },
  { id: 'flexible', name: 'Гибкость', description: 'Легко адаптируется', axis: PersonalityAxis.OPENNESS, threshold: 35,
    positiveEffects: 'Быстро адаптируешься к изменениям', negativeEffects: 'Можешь потерять свои принципы',
    acquireCondition: 'Часто менял обстановку в 5-14 лет', formAgeStart: 5, formAgeEnd: 14,
    modifiers: { negativeEventPenaltyReduction: 0.1, stressGainMultiplier: -0.05 } },
  { id: 'loyal', name: 'Верность', description: 'Предан друзьям и идеям', axis: PersonalityAxis.AGREEABLENESS, threshold: 45,
    positiveEffects: 'Друзья остаются навсегда', negativeEffects: 'Остаёшься даже когда нужно уйти',
    acquireCondition: 'Не предавал друзей в 8-16 лет', formAgeStart: 8, formAgeEnd: 16,
    modifiers: { relationshipGainMultiplier: 0.2, stressGainMultiplier: 0.05 } },
  { id: 'pragmatic', name: 'Прагматизм', description: 'Руководствуется логикой', axis: PersonalityAxis.CONSCIENTIOUSNESS, threshold: -35,
    positiveEffects: 'Принимаешь рациональные решения', negativeEffects: 'Люди считают тебя холодным',
    acquireCondition: 'Учился решать проблемы логически в 8-16 лет', formAgeStart: 8, formAgeEnd: 16,
    modifiers: { workEfficiencyMultiplier: 0.1, relationshipGainMultiplier: -0.05 } },
  { id: 'dreamer', name: 'Мечтатель', description: 'Живёт в своём мире', axis: PersonalityAxis.OPENNESS, threshold: 45,
    positiveEffects: 'Богатый внутренний мир', negativeEffects: 'Плохо с практическими делами',
    acquireCondition: 'Много фантазировал в 5-12 лет', formAgeStart: 5, formAgeEnd: 12,
    modifiers: { moodRecoveryMultiplier: 0.15, workEfficiencyMultiplier: -0.1 } },
  { id: 'reliable', name: 'Надёжность', description: 'На него можно положиться', axis: PersonalityAxis.CONSCIENTIOUSNESS, threshold: 40,
    positiveEffects: 'Тебе доверяют важные дела', negativeEffects: 'Не можешь отказать и перегружен',
    acquireCondition: 'Выполнял обещания в 8-16 лет', formAgeStart: 8, formAgeEnd: 16,
    modifiers: { promotionChanceBonus: 0.1, stressGainMultiplier: 0.05 } },
  { id: 'rebellious', name: 'Бунтарство', description: 'Не принимает авторитеты', axis: PersonalityAxis.OPENNESS, threshold: -45,
    positiveEffects: 'Мыслишь независимо', negativeEffects: 'Конфликты с начальством',
    acquireCondition: 'Сговорился против учителей в 10-16 лет', formAgeStart: 10, formAgeEnd: 16,
    modifiers: { salaryMultiplier: -0.05, learningSpeedMultiplier: 0.1 } },
  { id: 'diplomatic', name: 'Дипломатичность', description: 'Умеет сглаживать конфликты', axis: PersonalityAxis.AGREEABLENESS, threshold: 35,
    positiveEffects: 'Разряжаешь любую ситуацию', negativeEffects: 'Иногда жертввуешь своими интересами',
    acquireCondition: 'Миррил ссоры в 8-16 лет', formAgeStart: 8, formAgeEnd: 16,
    modifiers: { relationshipGainMultiplier: 0.15, stressGainMultiplier: -0.05 } },
  { id: 'impulsive', name: 'Импульсивность', description: 'Действует не подумав', axis: PersonalityAxis.NEUROTICISM, threshold: 40,
    positiveEffects: 'Быстрые решения', negativeEffects: 'Часто неверные решения',
    acquireCondition: 'Действовал не подумав в 8-16 лет', formAgeStart: 8, formAgeEnd: 16,
    modifiers: { shopPriceMultiplier: 0.02, negativeEventChance: 0.08 } },
  { id: 'patient', name: 'Терпение', description: 'Умеет ждать', axis: PersonalityAxis.NEUROTICISM, threshold: -40,
    positiveEffects: 'Иммунитет к рутине', negativeEffects: 'Можешь упустить момент',
    acquireCondition: 'Терпеливо ждал и получал результат в 8-16 лет', formAgeStart: 8, formAgeEnd: 16,
    modifiers: { routinePenaltyReduction: 0.15, stressGainMultiplier: -0.1 } },
]
